!  +++++++++++++++++++++++ CC_DIVERGENCE_KERNELS ++++++++++++++++++++++++++

! Thread-safe computation kernels for CC divergence routines.
! Each routine takes TYPE(MESH_TYPE) as explicit argument
! instead of relying on MESH_POINTERS.

MODULE CC_DIVERGENCE_KERNELS

USE PRECISION_PARAMETERS
USE TYPES
USE GLOBAL_CONSTANTS
USE MESH_VARIABLES
USE COMPLEX_GEOMETRY, ONLY: CC_FTYPE_RCGAS, CC_FTYPE_CFGAS, &
                            CC_FTYPE_CFINB, CC_FGSC, CC_SOLID

IMPLICIT NONE (TYPE,EXTERNAL)

PRIVATE

PUBLIC :: GET_CC_CELL_DIFFUSIVITY, GET_CC_CELL_CONDUCTIVITY, &
          GET_VELOC_DIVERGENCE_CUTCELL, GET_FN_DIVERGENCE_CUTCELL, &
          SET_EXIMADVFLX_3D, SET_EXIMDIFFLX_3D, &
          SET_EXIMRHOZZLIM_3D, SET_EXIMRHOHSLIM_3D

CONTAINS


! ----------------------- GET_CC_CELL_DIFFUSIVITY -------------------------

SUBROUTINE GET_CC_CELL_DIFFUSIVITY(RHO_CELL,D_Z_N,MU_CELL, &
                                   MU_DNS_CELL,TMP_CELL,D_Z_TEMP)

USE MATH_FUNCTIONS, ONLY: INTERPOLATE1D_UNIFORM
USE MANUFACTURED_SOLUTIONS, ONLY: DIFF_MMS

REAL(EB), INTENT(IN) :: RHO_CELL,D_Z_N(0:I_MAX_TEMP), &
                         MU_CELL,MU_DNS_CELL,TMP_CELL
REAL(EB), INTENT(OUT):: D_Z_TEMP

REAL(EB) :: D_Z_TEMP_DNS

SELECT CASE(SIM_MODE)
CASE(LES_MODE)
   CALL INTERPOLATE1D_UNIFORM(LBOUND(D_Z_N,1),D_Z_N,TMP_CELL, &
                               D_Z_TEMP_DNS)
   D_Z_TEMP = D_Z_TEMP_DNS + &
              MAX(0._EB,MU_CELL-MU_DNS_CELL)*RSC_T/RHO_CELL
CASE(DNS_MODE)
   IF(PERIODIC_TEST==7) THEN
      D_Z_TEMP = DIFF_MMS / RHO_CELL
   ELSE
      CALL INTERPOLATE1D_UNIFORM(LBOUND(D_Z_N,1),D_Z_N,TMP_CELL, &
                                  D_Z_TEMP)
   ENDIF
CASE DEFAULT
   D_Z_TEMP = MU_CELL*RSC_T/RHO_CELL ! VLES
END SELECT

RETURN
END SUBROUTINE GET_CC_CELL_DIFFUSIVITY


! ----------------------- GET_CC_CELL_CONDUCTIVITY -------------------------

SUBROUTINE GET_CC_CELL_CONDUCTIVITY(ZZ_CELL,MU_CELL, &
                                    MU_DNS_CELL,TMP_CELL,KP_CELL)

USE PHYSICAL_FUNCTIONS, ONLY: GET_CONDUCTIVITY,GET_SPECIFIC_HEAT

REAL(EB), INTENT(IN)  :: ZZ_CELL(1:N_TRACKED_SPECIES), &
                          MU_CELL,MU_DNS_CELL,TMP_CELL
REAL(EB), INTENT(OUT) :: KP_CELL

! Local Vars:
REAL(EB) :: CP_CELL

IF (SIM_MODE==DNS_MODE .OR. SIM_MODE==LES_MODE) THEN
   CALL GET_CONDUCTIVITY(ZZ_CELL,KP_CELL,TMP_CELL)
   IF (SIM_MODE==LES_MODE) THEN
      IF (.NOT.CONSTANT_SPECIFIC_HEAT_RATIO) THEN
         CALL GET_SPECIFIC_HEAT(ZZ_CELL,CP_CELL,TMP_CELL)
         KP_CELL = KP_CELL + &
                   MAX(0._EB,MU_CELL-MU_DNS_CELL)*CP_CELL*RPR_T
      ELSE
         KP_CELL = KP_CELL + &
                   MAX(0._EB,MU_CELL-MU_DNS_CELL)*CPOPR
      ENDIF
   ENDIF
ELSE ! VLES
   KP_CELL = MU_CELL*CPOPR
ENDIF

RETURN
END SUBROUTINE GET_CC_CELL_CONDUCTIVITY


! -------------------- GET_VELOC_DIVERGENCE_CUTCELL ------------------------

SUBROUTINE GET_VELOC_DIVERGENCE_CUTCELL(M,ICC,JCC,PRFCT,DIV_JCC)

! ICC,JCC = Indexes of particular cut-cell
! PRFCT   = if US,VS,WS => PRFCT=1, if U,V,W => PRFCT=0
! DIV_JCC = Velocity divergence in cut-cell ICC,JCC

TYPE(MESH_TYPE), INTENT(IN), TARGET :: M
INTEGER, INTENT(IN) :: ICC, JCC
REAL(EB),INTENT(IN) :: PRFCT
REAL(EB),INTENT(OUT):: DIV_JCC

! Local Variables:
INTEGER :: IFACE, IFC, LOWHIGH, X1AXIS, ILH, IFC2, IFACE2, &
           ICFA, I, J, K
REAL(EB):: AF, VELN, FCT

I      = M%CUT_CELL(ICC)%IJK(IAXIS)
J      = M%CUT_CELL(ICC)%IJK(JAXIS)
K      = M%CUT_CELL(ICC)%IJK(KAXIS)

DIV_JCC = 0._EB
IFC_LOOP : DO IFC=1,M%CUT_CELL(ICC)%CCELEM(1,JCC)
   IFACE = M%CUT_CELL(ICC)%CCELEM(IFC+1,JCC)
   AF     = 0._EB
   VELN   = 0._EB
   SELECT CASE(M%CUT_CELL(ICC)%FACE_LIST(1,IFACE))
   CASE(CC_FTYPE_RCGAS) ! REGULAR GASPHASE
      LOWHIGH = M%CUT_CELL(ICC)%FACE_LIST(2,IFACE)
      X1AXIS  = M%CUT_CELL(ICC)%FACE_LIST(3,IFACE)
      ILH     =        LOWHIGH - 1
      FCT     = REAL(2*LOWHIGH - 3, EB)
      SELECT CASE(X1AXIS)
      CASE(IAXIS)
         AF   = M%DY(J)*M%DZ(K)
         VELN = FCT*(PRFCT*M%US(I-1+ILH,J,K) + &
                     (1._EB-PRFCT)*M%U(I-1+ILH,J,K))
      CASE(JAXIS)
         AF   = M%DX(I)*M%DZ(K)
         VELN = FCT*(PRFCT*M%VS(I,J-1+ILH,K) + &
                     (1._EB-PRFCT)*M%V(I,J-1+ILH,K))
      CASE(KAXIS)
         AF   = M%DX(I)*M%DY(J)
         VELN = FCT*(PRFCT*M%WS(I,J,K-1+ILH) + &
                     (1._EB-PRFCT)*M%W(I,J,K-1+ILH))
      END SELECT
   CASE(CC_FTYPE_CFGAS) ! GASPHASE CUT FACE:
      LOWHIGH = M%CUT_CELL(ICC)%FACE_LIST(2,IFACE)
      FCT     = REAL(2*LOWHIGH - 3, EB)
      IFC2    = M%CUT_CELL(ICC)%FACE_LIST(4,IFACE)
      IFACE2  = M%CUT_CELL(ICC)%FACE_LIST(5,IFACE)
      AF      = M%CUT_FACE(IFC2)%AREA(IFACE2)
      VELN    = FCT*((1._EB-PRFCT)* &
                     M%CUT_FACE(IFC2)%VEL( IFACE2) + &
                     PRFCT *M%CUT_FACE(IFC2)%VELS(IFACE2))
   CASE(CC_FTYPE_CFINB) ! INBOUNDARY CUT FACE
      FCT     = 1._EB
      IFC2    = M%CUT_CELL(ICC)%FACE_LIST(4,IFACE)
      IFACE2  = M%CUT_CELL(ICC)%FACE_LIST(5,IFACE)
      ICFA    = M%CUT_FACE(IFC2)%CFACE_INDEX(IFACE2)
      AF      = M%CUT_FACE(IFC2)%AREA(IFACE2)
      VELN    = FCT*((1._EB-PRFCT)* &
                     M%CUT_FACE(IFC2)%VEL( IFACE2) + &
                     PRFCT *M%CUT_FACE(IFC2)%VELS(IFACE2))
   END SELECT
   DIV_JCC = DIV_JCC + AF*VELN
ENDDO IFC_LOOP

DIV_JCC = DIV_JCC / M%CUT_CELL(ICC)%VOLUME(JCC)

END SUBROUTINE GET_VELOC_DIVERGENCE_CUTCELL


! ----------------------- GET_FN_DIVERGENCE_CUTCELL ------------------------

SUBROUTINE GET_FN_DIVERGENCE_CUTCELL(M,ICC,JCC,DIV_FN, &
                                     SUBSTRACT_BAROCLINIC)

! ICC,JCC = Indexes of particular cut-cell
! DIV_FN  = FN divergence in cut-cell ICC,JCC

TYPE(MESH_TYPE), INTENT(IN), TARGET :: M
INTEGER, INTENT(IN) :: ICC, JCC
REAL(EB),INTENT(OUT):: DIV_FN
LOGICAL, INTENT(IN) :: SUBSTRACT_BAROCLINIC

! Local Variables:
INTEGER :: IFACE, IFC, LOWHIGH, X1AXIS, ILH, IFC2, IFACE2, &
           ICFA, I, J, K
REAL(EB):: AF, FN, FCT, SUB_FCT

SUB_FCT = 0._EB; IF (SUBSTRACT_BAROCLINIC) SUB_FCT = 1._EB

I      = M%CUT_CELL(ICC)%IJK(IAXIS)
J      = M%CUT_CELL(ICC)%IJK(JAXIS)
K      = M%CUT_CELL(ICC)%IJK(KAXIS)

DIV_FN = 0._EB
IFC_LOOP : DO IFC=1,M%CUT_CELL(ICC)%CCELEM(1,JCC)
   IFACE = M%CUT_CELL(ICC)%CCELEM(IFC+1,JCC)
   AF     = 0._EB
   FN   = 0._EB
   SELECT CASE(M%CUT_CELL(ICC)%FACE_LIST(1,IFACE))
   CASE(CC_FTYPE_RCGAS) ! REGULAR GASPHASE
      LOWHIGH = M%CUT_CELL(ICC)%FACE_LIST(2,IFACE)
      X1AXIS  = M%CUT_CELL(ICC)%FACE_LIST(3,IFACE)
      ILH     =        LOWHIGH - 1
      FCT     = REAL(2*LOWHIGH - 3, EB)
      SELECT CASE(X1AXIS)
      CASE(IAXIS)
         AF   = M%DY(J)*M%DZ(K)
         FN   = FCT*(M%FVX(I-1+ILH,J,K) - &
                     SUB_FCT*M%FVX_B(I-1+ILH,J,K))
      CASE(JAXIS)
         AF   = M%DX(I)*M%DZ(K)
         FN   = FCT*(M%FVY(I,J-1+ILH,K) - &
                     SUB_FCT*M%FVY_B(I,J-1+ILH,K))
      CASE(KAXIS)
         AF   = M%DX(I)*M%DY(J)
         FN   = FCT*(M%FVZ(I,J,K-1+ILH) - &
                     SUB_FCT*M%FVZ_B(I,J,K-1+ILH))
      END SELECT
   CASE(CC_FTYPE_CFGAS) ! GASPHASE CUT FACE:
      LOWHIGH = M%CUT_CELL(ICC)%FACE_LIST(2,IFACE)
      FCT     = REAL(2*LOWHIGH - 3, EB)
      IFC2    = M%CUT_CELL(ICC)%FACE_LIST(4,IFACE)
      IFACE2  = M%CUT_CELL(ICC)%FACE_LIST(5,IFACE)
      AF      = M%CUT_FACE(IFC2)%AREA(IFACE2)
      FN      = FCT*(M%CUT_FACE(IFC2)%FN( IFACE2) - &
                     SUB_FCT*M%CUT_FACE(IFC2)%FN_B( IFACE2))
   CASE(CC_FTYPE_CFINB) ! INBOUNDARY CUT FACE
      FCT     = 1._EB
      IFC2    = M%CUT_CELL(ICC)%FACE_LIST(4,IFACE)
      IFACE2  = M%CUT_CELL(ICC)%FACE_LIST(5,IFACE)
      ICFA    = M%CUT_FACE(IFC2)%CFACE_INDEX(IFACE2)
      AF      = M%CUT_FACE(IFC2)%AREA(IFACE2)
      FN      = FCT*(M%CUT_FACE(IFC2)%FN( IFACE2) - &
                     SUB_FCT*M%CUT_FACE(IFC2)%FN_B( IFACE2))
   END SELECT
   DIV_FN = DIV_FN + AF*FN
ENDDO IFC_LOOP

DIV_FN = DIV_FN / M%CUT_CELL(ICC)%VOLUME(JCC)

END SUBROUTINE GET_FN_DIVERGENCE_CUTCELL


! ----------------------------- SET_EXIMADVFLX_3D -------------------------

SUBROUTINE SET_EXIMADVFLX_3D(M,UU,VV,WW)

TYPE(MESH_TYPE), INTENT(INOUT), TARGET :: M
REAL(EB), POINTER, DIMENSION(:,:,:) :: UU,VV,WW

! Local Variables:
INTEGER :: N,I,J,K,X1AXIS,IFACE
TYPE(CC_REGFACEZ_TYPE),  POINTER, DIMENSION(:) :: REGFACE_Z

! Loop on scalars:
SPECIES_LOOP : DO N=1,N_TOTAL_SCALARS

   AXIS_DO : DO X1AXIS = IAXIS,KAXIS
      SELECT CASE(X1AXIS)
      CASE(IAXIS)
         REGFACE_Z => M%CC_REGFACE_IAXIS_Z
      CASE(JAXIS)
         REGFACE_Z => M%CC_REGFACE_JAXIS_Z
      CASE(KAXIS)
         REGFACE_Z => M%CC_REGFACE_KAXIS_Z
      END SELECT
      IFACE_DO : DO IFACE=1,M%CC_NREGFACE_Z(X1AXIS)
         I  = REGFACE_Z(IFACE)%IJK(IAXIS)
         J  = REGFACE_Z(IFACE)%IJK(JAXIS)
         K  = REGFACE_Z(IFACE)%IJK(KAXIS)
         ! Load Advective flux in REG face container:
         REGFACE_Z(IFACE)%RHOZZ_U(N) = 0._EB
         SELECT CASE(X1AXIS)
         CASE(IAXIS)
            REGFACE_Z(IFACE)%RHOZZ_U(N) = &
               M%FX(I,J,K,N)*UU(I,J,K)*M%R(I)
         CASE(JAXIS)
            REGFACE_Z(IFACE)%RHOZZ_U(N) = &
               M%FY(I,J,K,N)*VV(I,J,K)
         CASE(KAXIS)
            REGFACE_Z(IFACE)%RHOZZ_U(N) = &
               M%FZ(I,J,K,N)*WW(I,J,K)
         END SELECT
      ENDDO IFACE_DO
   ENDDO AXIS_DO

ENDDO SPECIES_LOOP

RETURN
END SUBROUTINE SET_EXIMADVFLX_3D


! ----------------------------- SET_EXIMDIFFLX_3D -------------------------

SUBROUTINE SET_EXIMDIFFLX_3D(M,RHO_D_DZDX,RHO_D_DZDY,RHO_D_DZDZ)

TYPE(MESH_TYPE), INTENT(INOUT), TARGET :: M
REAL(EB), INTENT(IN), POINTER, DIMENSION(:,:,:,:) :: &
   RHO_D_DZDX,RHO_D_DZDY,RHO_D_DZDZ

! Local Variables:
INTEGER :: N,I,J,K,X1AXIS,IFACE
TYPE(CC_REGFACEZ_TYPE),  POINTER, DIMENSION(:) :: REGFACE_Z

! First, set all diffusive fluxes to zero on CC_SOLID faces:
! IAXIS:
X1AXIS = IAXIS
DO K=1,M%KBAR
   DO J=1,M%JBAR
      DO I=0,M%IBAR
         IF (M%FCVAR(I,J,K,CC_FGSC,X1AXIS) /= CC_SOLID ) CYCLE
         RHO_D_DZDX(I,J,K,1:N_TOTAL_SCALARS) = 0._EB
      ENDDO
   ENDDO
ENDDO
! JAXIS:
X1AXIS = JAXIS
DO K=1,M%KBAR
   DO J=0,M%JBAR
      DO I=1,M%IBAR
         IF (M%FCVAR(I,J,K,CC_FGSC,X1AXIS) /= CC_SOLID ) CYCLE
         RHO_D_DZDY(I,J,K,1:N_TOTAL_SCALARS) = 0._EB
      ENDDO
   ENDDO
ENDDO
! KAXIS:
X1AXIS = KAXIS
DO K=0,M%KBAR
   DO J=1,M%JBAR
      DO I=1,M%IBAR
         IF (M%FCVAR(I,J,K,CC_FGSC,X1AXIS) /= CC_SOLID ) CYCLE
         RHO_D_DZDZ(I,J,K,1:N_TOTAL_SCALARS) = 0._EB
      ENDDO
   ENDDO
ENDDO

! Loop on scalars:
SPECIES_LOOP : DO N=1,N_TOTAL_SCALARS

   AXIS_DO : DO X1AXIS = IAXIS,KAXIS
      SELECT CASE(X1AXIS)
      CASE(IAXIS)
         REGFACE_Z => M%CC_REGFACE_IAXIS_Z
      CASE(JAXIS)
         REGFACE_Z => M%CC_REGFACE_JAXIS_Z
      CASE(KAXIS)
         REGFACE_Z => M%CC_REGFACE_KAXIS_Z
      END SELECT
      IFACE_DO : DO IFACE=1,M%CC_NREGFACE_Z(X1AXIS)
         I  = REGFACE_Z(IFACE)%IJK(IAXIS)
         J  = REGFACE_Z(IFACE)%IJK(JAXIS)
         K  = REGFACE_Z(IFACE)%IJK(KAXIS)
         SELECT CASE(X1AXIS)
         CASE(IAXIS)
            REGFACE_Z(IFACE)%RHO_D_DZDN(N) = &
               RHO_D_DZDX(I,J,K,N)
         CASE(JAXIS)
            REGFACE_Z(IFACE)%RHO_D_DZDN(N) = &
               RHO_D_DZDY(I,J,K,N)
         CASE(KAXIS)
            REGFACE_Z(IFACE)%RHO_D_DZDN(N) = &
               RHO_D_DZDZ(I,J,K,N)
         END SELECT
      ENDDO IFACE_DO
   ENDDO AXIS_DO

ENDDO SPECIES_LOOP

RETURN
END SUBROUTINE SET_EXIMDIFFLX_3D


! --------------------------- SET_EXIMRHOZZLIM_3D -------------------------

SUBROUTINE SET_EXIMRHOZZLIM_3D(M,N)

! Get flux limited \bar{rho Za} in EXIM boundary faces.

TYPE(MESH_TYPE), INTENT(INOUT), TARGET :: M
INTEGER, INTENT(IN) :: N

! Local Variables:
INTEGER :: I,J,K,X1AXIS
REAL(EB), POINTER, DIMENSION(:,:,:,:) :: FX_ZZ,FY_ZZ,FZ_ZZ
INTEGER :: IFACE,IW
TYPE(CC_REGFACEZ_TYPE),  POINTER, DIMENSION(:) :: REGFACE_Z

FX_ZZ=>M%SWORK1
FY_ZZ=>M%SWORK2
FZ_ZZ=>M%SWORK3

AXIS_DO : DO X1AXIS = IAXIS,KAXIS
   SELECT CASE(X1AXIS)
   CASE(IAXIS)
      REGFACE_Z => M%CC_REGFACE_IAXIS_Z
   CASE(JAXIS)
      REGFACE_Z => M%CC_REGFACE_JAXIS_Z
   CASE(KAXIS)
      REGFACE_Z => M%CC_REGFACE_KAXIS_Z
   END SELECT
   IFACE_DO : DO IFACE=1,M%CC_NREGFACE_Z(X1AXIS)
      IW = REGFACE_Z(IFACE)%IWC
      IF((IW > 0) .AND. &
         .NOT.(M%WALL(IW)%BOUNDARY_TYPE==INTERPOLATED_BOUNDARY &
         .OR. M%WALL(IW)%BOUNDARY_TYPE==PERIODIC_BOUNDARY)) &
         CYCLE IFACE_DO
      I  = REGFACE_Z(IFACE)%IJK(IAXIS)
      J  = REGFACE_Z(IFACE)%IJK(JAXIS)
      K  = REGFACE_Z(IFACE)%IJK(KAXIS)
      ! Load Diffusive flux in EXIM boundary face container:
      REGFACE_Z(IFACE)%FN_ZZ(N) = 0._EB
      IF (REGFACE_Z(IFACE)%IWC > 0) THEN
         IF (M%WALL(REGFACE_Z(IFACE)%IWC)%BOUNDARY_TYPE== &
             NULL_BOUNDARY) CYCLE
         REGFACE_Z(IFACE)%FN_ZZ(N) = &
            M%BOUNDARY_PROP1(M%WALL(REGFACE_Z(IFACE)%IWC) &
            %B1_INDEX)%RHO_F * &
            M%BOUNDARY_PROP1(M%WALL(REGFACE_Z(IFACE)%IWC) &
            %B1_INDEX)%ZZ_F(N)
      ELSE
         SELECT CASE(X1AXIS)
         CASE(IAXIS)
            REGFACE_Z(IFACE)%FN_ZZ(N) = FX_ZZ(I,J,K,N)
         CASE(JAXIS)
            REGFACE_Z(IFACE)%FN_ZZ(N) = FY_ZZ(I,J,K,N)
         CASE(KAXIS)
            REGFACE_Z(IFACE)%FN_ZZ(N) = FZ_ZZ(I,J,K,N)
         END SELECT
      ENDIF
   ENDDO IFACE_DO
ENDDO AXIS_DO

RETURN
END SUBROUTINE SET_EXIMRHOZZLIM_3D


! --------------------------- SET_EXIMRHOHSLIM_3D -------------------------

SUBROUTINE SET_EXIMRHOHSLIM_3D(M)

! Get flux limited \bar{rho hs} in EXIM boundary faces.

USE PHYSICAL_FUNCTIONS, ONLY: GET_SENSIBLE_ENTHALPY

TYPE(MESH_TYPE), INTENT(INOUT), TARGET :: M

! Local Variables:
INTEGER :: I,J,K,X1AXIS
REAL(EB), POINTER, DIMENSION(:,:,:) :: FX_H_S,FY_H_S,FZ_H_S
REAL(EB) :: H_S,ZZ_GET(1:N_TRACKED_SPECIES),TMP_F_GAS,VELC2
INTEGER :: IFACE,IW
TYPE(CC_REGFACEZ_TYPE),  POINTER, DIMENSION(:) :: REGFACE_Z

FX_H_S=>M%WORK2
FY_H_S=>M%WORK3
FZ_H_S=>M%WORK4

AXIS_DO : DO X1AXIS = IAXIS,KAXIS
   SELECT CASE(X1AXIS)
   CASE(IAXIS)
      REGFACE_Z => M%CC_REGFACE_IAXIS_Z
   CASE(JAXIS)
      REGFACE_Z => M%CC_REGFACE_JAXIS_Z
   CASE(KAXIS)
      REGFACE_Z => M%CC_REGFACE_KAXIS_Z
   END SELECT
   IFACE_DO : DO IFACE=1,M%CC_NREGFACE_Z(X1AXIS)
      IW = REGFACE_Z(IFACE)%IWC
      IF((IW > 0) .AND. &
         .NOT.(M%WALL(IW)%BOUNDARY_TYPE==INTERPOLATED_BOUNDARY &
         .OR. M%WALL(IW)%BOUNDARY_TYPE==PERIODIC_BOUNDARY)) &
         CYCLE IFACE_DO
      I  = REGFACE_Z(IFACE)%IJK(IAXIS)
      J  = REGFACE_Z(IFACE)%IJK(JAXIS)
      K  = REGFACE_Z(IFACE)%IJK(KAXIS)
      ! Load Diffusive flux in REG boundary face container:
      REGFACE_Z(IFACE)%FN_H_S = 0._EB
      IF (REGFACE_Z(IFACE)%IWC > 0) THEN
         IW = REGFACE_Z(IFACE)%IWC
         IF (M%WALL(IW)%BOUNDARY_TYPE==NULL_BOUNDARY) &
            CYCLE IFACE_DO
         IF (PREDICTOR) THEN
            VELC2 = M%BOUNDARY_PROP1(M%WALL(IW)%B1_INDEX) &
                    %U_NORMAL_S
         ELSE
            VELC2 = M%BOUNDARY_PROP1(M%WALL(IW)%B1_INDEX) &
                    %U_NORMAL
         ENDIF
         IF (M%WALL(IW)%BOUNDARY_TYPE==SOLID_BOUNDARY .AND. &
             VELC2>0._EB) THEN
            TMP_F_GAS = M%TMP( &
               M%BOUNDARY_COORD(M%WALL(IW)%BC_INDEX)%IIG, &
               M%BOUNDARY_COORD(M%WALL(IW)%BC_INDEX)%JJG, &
               M%BOUNDARY_COORD(M%WALL(IW)%BC_INDEX)%KKG)
         ELSE
            TMP_F_GAS = M%BOUNDARY_PROP1(M%WALL(IW)%B1_INDEX) &
                        %TMP_F
         ENDIF
         ZZ_GET(1:N_TRACKED_SPECIES) = &
            M%BOUNDARY_PROP1(M%WALL(IW)%B1_INDEX) &
            %ZZ_F(1:N_TRACKED_SPECIES)
         CALL GET_SENSIBLE_ENTHALPY(ZZ_GET,H_S,TMP_F_GAS)
         REGFACE_Z(IFACE)%FN_H_S = &
            M%BOUNDARY_PROP1(M%WALL(IW)%B1_INDEX)%RHO_F*H_S
      ELSE
         SELECT CASE(X1AXIS)
         CASE(IAXIS)
            REGFACE_Z(IFACE)%FN_H_S = FX_H_S(I,J,K)
         CASE(JAXIS)
            REGFACE_Z(IFACE)%FN_H_S = FY_H_S(I,J,K)
         CASE(KAXIS)
            REGFACE_Z(IFACE)%FN_H_S = FZ_H_S(I,J,K)
         END SELECT
      ENDIF
   ENDDO IFACE_DO
ENDDO AXIS_DO

RETURN
END SUBROUTINE SET_EXIMRHOHSLIM_3D


END MODULE CC_DIVERGENCE_KERNELS
