
!  +++++++++++++++++++++++ CC_SCALARS_DATA ++++++++++++++++++++++++++

! Shared declarations for the CC_SCALARS family of modules.
! All mutable module-level state, parameters, and convenience pointers
! used across the cut-cell / immersed-boundary routines live here.

MODULE CC_SCALARS_DATA

USE PRECISION_PARAMETERS
USE GLOBAL_CONSTANTS
USE MESH_VARIABLES
USE TYPES

IMPLICIT NONE (TYPE,EXTERNAL)

! Debug Flags:
LOGICAL, PARAMETER :: DEBUG_CC_INTERPOLATION=.FALSE.
LOGICAL, PARAMETER :: DEBUG_MATVEC_DATA=.FALSE.
LOGICAL, PARAMETER :: DEBUG_CC_SCALAR_TRANSPORT=.FALSE.
LOGICAL, PARAMETER :: TIME_CC_IBM=.FALSE.
INTEGER :: LU_DB_CCIB

! Forcing and Inseparable pressure residual computation parameters:
REAL(EB), PARAMETER:: A_THRESH_FORCING     = 0.05_EB
REAL(EB), PARAMETER:: STM_THRESH_EXTRP     = 0.005_EB
REAL(EB), PARAMETER:: V_THRESH_INSPRES     = 0.005_EB

! Local integers:
INTEGER, SAVE :: ILO_CELL,IHI_CELL,JLO_CELL,JHI_CELL,KLO_CELL,KHI_CELL
INTEGER, SAVE :: ILO_FACE,IHI_FACE,JLO_FACE,JHI_FACE,KLO_FACE,KHI_FACE
INTEGER, SAVE :: NXB, NYB, NZB

! Allocatable real arrays
! Grid position containers:
REAL(EB), SAVE, TARGET, ALLOCATABLE, DIMENSION(:) :: XFACE,YFACE,ZFACE,XCELL,YCELL,ZCELL, &
          DXFACE,DYFACE,DZFACE,DXCELL,DYCELL,DZCELL

REAL(EB), POINTER, DIMENSION(:) :: X1FACEP,X2FACEP,X3FACEP,  &
                   X2CELLP,X3CELLP

! Scalar transport variables:
INTEGER, ALLOCATABLE, DIMENSION(:) :: NUNKZ_LOC, NUNKZ_TOT, UNKZ_IND, UNKZ_ILC
INTEGER :: NUNKZ_LOCAL,NUNKZ_TOTAL

INTEGER, PARAMETER :: NNZ_ROW_Z = 15

INTEGER, ALLOCATABLE, DIMENSION(:)    :: NNZ_D_MAT_Z
INTEGER, ALLOCATABLE, DIMENSION(:,:)  :: JD_MAT_Z

REAL(EB),ALLOCATABLE, DIMENSION(:)   :: M_MAT_Z
INTEGER, ALLOCATABLE, DIMENSION(:)   :: JM_MAT_Z

REAL(EB), ALLOCATABLE, DIMENSION(:)  :: F_Z, RZ_Z, RZ_ZS, P_0_CV, TMP_0_CV, RHO_0_CV, ZCEN_CV
REAL(EB), ALLOCATABLE, DIMENSION(:,:):: DELTA_UNKZ
REAL(EB), ALLOCATABLE, DIMENSION(:,:):: F_Z0, RZ_Z0

REAL(EB), TARGET, DIMENSION(0:3,0:3,0:3) :: F_WORK
REAL(EB), TARGET, DIMENSION(-1:3,-1:3,-1:3) :: U_WORK,Z_WORK
REAL(EB), POINTER, DIMENSION(:,:,:) :: U_TEMP,Z_TEMP,F_TEMP

! Types of interpolation:
INTEGER, PARAMETER :: CC_LINEAR_INTERPOLATION    = 1
INTEGER, PARAMETER :: CC_QUADRATIC_INTERPOLATION = 2
INTEGER, PARAMETER :: CC_WLS_INTERPOLATION       = 3
INTEGER, SAVE      :: STENCIL_INTERPOLATION       = CC_LINEAR_INTERPOLATION

! IBEDGE stress definition stencil variables:
REAL(EB), SAVE :: THRES_FCT_EP = 0.49999_EB
INTEGER, PARAMETER  :: N_INT_EP_FVARS=1
INTEGER, PARAMETER  :: N_INT_EP_CVARS=1

! Rotated Cube verification case wave number:
INTEGER,  PARAMETER :: N_SPEC_BACKG = 1
INTEGER,  PARAMETER :: N_SPEC_NEUMN = 2
REAL(EB), PARAMETER :: GAM = PI/2._EB, AMP_Z=0.1_EB, MEAN_Z=0.15_EB
REAL(EB), PARAMETER :: NWAVE = 1._EB
REAL(EB), PARAMETER :: DISPXY(1:2,1) = RESHAPE((/ -PI/2._EB, -PI/2._EB /),(/2,1/))
REAL(EB), PARAMETER :: DISPL  = PI
REAL(EB) :: ROTANG, ROTMAT(2,2), TROTMAT(2,2)

! Convenience pointers (module-level, not thread-safe):
TYPE(WALL_TYPE),           POINTER :: WC
TYPE(CFACE_TYPE),          POINTER :: CFA
TYPE(CC_CUTCELL_TYPE),     POINTER :: CC
TYPE(CC_CUTFACE_TYPE),     POINTER :: CF
TYPE(CC_RCFACE_TYPE),      POINTER :: RCF
TYPE(BOUNDARY_COORD_TYPE), POINTER :: BC
TYPE(EXTERNAL_WALL_TYPE),  POINTER :: EWC
TYPE(BOUNDARY_PROP1_TYPE), POINTER :: B1

! Baroclininc torque linking variables.
REAL(EB), SAVE, ALLOCATABLE, DIMENSION(:) :: F_LINK,A_LINK

END MODULE CC_SCALARS_DATA
