
!  +++++++++++++++++++++++ CC_SCALARS ++++++++++++++++++++++++++


! Routines related to cut-cells, scalar transport and immersed boundary methods
!
MODULE CC_SCALARS

USE CC_SCALARS_DATA
USE CC_DIVERGENCE, ONLY: GET_CC_CELL_CONDUCTIVITY
USE COMPLEX_GEOMETRY
USE PRECISION_PARAMETERS
USE GLOBAL_CONSTANTS
USE MESH_VARIABLES
USE MESH_POINTERS
USE COMP_FUNCTIONS, ONLY: CURRENT_TIME

IMPLICIT NONE (TYPE,EXTERNAL)

PRIVATE

PUBLIC :: ADD_Q_DOT_CUTCELLS, CCCOMPUTE_RADIATION, &
          CC_H_INTERP, CC_RHO0W_INTERP, &
          CFACE_THERMAL_GASVARS, &
          GET_BOUND_VEL, GET_MUDNS_CFACE, GET_UVWGAS_CFACE, &
          GET_PRES_CFACE, GET_PRES_CFACE_TEST, &
          GET_CUTFACE_BAROCLINIC_TORQUE, GET_RCFACE_BAROCLINIC_TORQUE

CONTAINS




! --------------------------- GET_CUTFACE_BAROCLINIC_TORQUE ------------------------

SUBROUTINE GET_CUTFACE_BAROCLINIC_TORQUE(PRFCT,CF,JCF,IDX,WG1,WG2,II1,JJ1,KK1,II2,JJ2,KK2,FCF_B,HP)

! Assumes POINT_TO_MESH(NM) has been called.

REAL(EB),INTENT(IN) :: PRFCT
TYPE(CC_CUTFACE_TYPE), INTENT(IN), POINTER :: CF
INTEGER, INTENT(IN) :: JCF,II1,JJ1,KK1,II2,JJ2,KK2
REAL(EB),INTENT(INOUT) :: IDX,WG1,WG2
REAL(EB),INTENT(OUT):: FCF_B
REAL(EB), POINTER, DIMENSION(:,:,:), INTENT(IN) :: HP

INTEGER :: ICC,JCC,X1AXIS
REAL(EB):: X1F,RHO1,RHO2,P1,P2,RHOF

X1AXIS = CF%IJK(KAXIS+1)
IDX=1._EB/(CF%XCENHIGH(X1AXIS,JCF)-CF%XCENLOW(X1AXIS,JCF))
! Interpolation weights:
X1F = CF%XYZCEN(X1AXIS,JCF)
WG1 = IDX*(CF%XCENHIGH(X1AXIS,JCF)-X1F)
WG2 = IDX*(X1F-CF%XCENLOW(X1AXIS, JCF))
! Cut-cell pressure on low side:
ICC = CF%CELL_LIST(2,LOW_IND,JCF); JCC = CF%CELL_LIST(3,LOW_IND,JCF);
RHO1= PRFCT*CUT_CELL(ICC)%RHO(JCC)+(1._EB-PRFCT)*CUT_CELL(ICC)%RHOS(JCC)
P1  = RHO1*(HP(II1,JJ1,KK1)-KRES(II1,JJ1,KK1))
! Cut-cell pressure on high side:
ICC = CF%CELL_LIST(2,HIGH_IND,JCF); JCC = CF%CELL_LIST(3,HIGH_IND,JCF);
RHO2= PRFCT*CUT_CELL(ICC)%RHO(JCC)+(1._EB-PRFCT)*CUT_CELL(ICC)%RHOS(JCC)
P2  = RHO2*(HP(II2,JJ2,KK2)-KRES(II2,JJ2,KK2))
! Face density
RHOF= WG1*RHO1 + WG2*RHO2
! Baroclinic Term -p Grad(1/rho):
FCF_B = IDX * ( P2*(1._EB/RHOF-1._EB/RHO2) - P1*(1._EB/RHOF-1._EB/RHO1) )
!FCF_B = - (P1*RHO2+P2*RHO1)/(RHO1+RHO2) * IDX * (1._EB/RHO2-1._EB/RHO1)

RETURN
END SUBROUTINE GET_CUTFACE_BAROCLINIC_TORQUE

! -------------------------- GET_RCFACE_BAROCLINIC_TORQUE --------------------------

SUBROUTINE GET_RCFACE_BAROCLINIC_TORQUE(PRFCT,ICF,WG1,WG2,FRC_B,HP,RHOP)

! Assumes POINT_TO_MESH(NM) has been called.

REAL(EB),INTENT(IN)   :: PRFCT
INTEGER, INTENT(IN)   :: ICF
REAL(EB),INTENT(INOUT):: WG1,WG2
REAL(EB),INTENT(OUT)  :: FRC_B
REAL(EB), POINTER, DIMENSION(:,:,:), INTENT(IN) :: HP,RHOP

INTEGER :: ICC,JCC,I,J,K,X1AXIS,II1,II2,JJ1,JJ2,KK1,KK2
REAL(EB):: IDX,X1F,RHO1,RHO2,P1,P2,RHOF

I = RC_FACE(ICF)%IJK(IAXIS); J = RC_FACE(ICF)%IJK(JAXIS); K = RC_FACE(ICF)%IJK(KAXIS)
X1AXIS = RC_FACE(ICF)%IJK(KAXIS+1)
II1 = I; JJ1 = J; KK1 = K
II2 = I; JJ2 = J; KK2 = K
SELECT CASE(X1AXIS)
CASE(IAXIS); X1F=X(I); IDX = RDXN(I); II2 = II2+1
CASE(JAXIS); X1F=Y(J); IDX = RDYN(J); JJ2 = JJ2+1
CASE(KAXIS); X1F=Z(K); IDX = RDZN(K); KK2 = KK2+1
END SELECT
IDX=1._EB/(RC_FACE(ICF)%XCEN(X1AXIS,HIGH_IND)-RC_FACE(ICF)%XCEN(X1AXIS,LOW_IND))
! Interpolation weights:
WG1 = IDX*(RC_FACE(ICF)%XCEN(X1AXIS,HIGH_IND)-X1F)
WG2 = IDX*(X1F-RC_FACE(ICF)%XCEN(X1AXIS, LOW_IND))
RHO1 = RHOP(II1,JJ1,KK1); RHO2 = RHOP(II2,JJ2,KK2)
IF(RC_FACE(ICF)%CELL_LIST(1,LOW_IND)==CC_FTYPE_CFGAS) THEN
   ICC = RC_FACE(ICF)%CELL_LIST(2,LOW_IND); JCC = RC_FACE(ICF)%CELL_LIST(3,LOW_IND)
   RHO1= PRFCT*CUT_CELL(ICC)%RHO(JCC)+(1._EB-PRFCT)*CUT_CELL(ICC)%RHOS(JCC)
ENDIF
IF(RC_FACE(ICF)%CELL_LIST(1,HIGH_IND)==CC_FTYPE_CFGAS) THEN
   ICC = RC_FACE(ICF)%CELL_LIST(2,HIGH_IND); JCC = RC_FACE(ICF)%CELL_LIST(3,HIGH_IND)
   RHO2= PRFCT*CUT_CELL(ICC)%RHO(JCC)+(1._EB-PRFCT)*CUT_CELL(ICC)%RHOS(JCC)
ENDIF
P1   = RHO1*(HP(II1,JJ1,KK1)-KRES(II1,JJ1,KK1))
P2   = RHO2*(HP(II2,JJ2,KK2)-KRES(II2,JJ2,KK2))
! Face density
RHOF = WG1*RHO1 + WG2*RHO2
! Baroclinic torque:
FRC_B = IDX * ( P2*(1._EB/RHOF-1._EB/RHO2) - P1*(1._EB/RHOF-1._EB/RHO1) )
!FRC_B = - (P1*RHO2+P2*RHO1)/(RHO1+RHO2) * IDX * (1._EB/RHO2-1._EB/RHO1)

RETURN
END SUBROUTINE GET_RCFACE_BAROCLINIC_TORQUE







! -------------------------------- ADD_Q_DOT_CUTCELLS ------------------------------

SUBROUTINE ADD_Q_DOT_CUTCELLS(NM,QCOMB,QRAD,QPRES,SP_ENTH)

! This routine assumes POINT_TO_MESH(NM) has already been called for mesh NM.

USE PHYSICAL_FUNCTIONS, ONLY : GET_SENSIBLE_ENTHALPY

INTEGER, INTENT(IN) :: NM
REAL(EB), INTENT(INOUT) :: QCOMB,QRAD,QPRES,SP_ENTH

! Local Variables:
INTEGER :: ICC, JCC, I, J, K
REAL(EB):: VC,ZZ_GET(1:N_TRACKED_SPECIES),H_S

DO ICC=1,MESHES(NM)%N_CUTCELL_MESH
   I = CUT_CELL(ICC)%IJK(IAXIS)
   J = CUT_CELL(ICC)%IJK(JAXIS)
   K = CUT_CELL(ICC)%IJK(KAXIS)
   VC = DX(I)*DY(J)*DZ(K)
   QPRES = QPRES + 0.5_EB*(D_PBAR_DT_S(PRESSURE_ZONE(I,J,K))+D_PBAR_DT(PRESSURE_ZONE(I,J,K)))*VC
   DO JCC=1,CUT_CELL(ICC)%NCELL
      QCOMB = QCOMB + CUT_CELL(ICC)%Q(JCC)*CUT_CELL(ICC)%VOLUME(JCC)
      QRAD  = QRAD  + CUT_CELL(ICC)%QR(JCC)*CUT_CELL(ICC)%VOLUME(JCC)
      ZZ_GET(1:N_TRACKED_SPECIES) = CUT_CELL(ICC)%ZZ(1:N_TRACKED_SPECIES,JCC)
      CALL GET_SENSIBLE_ENTHALPY(ZZ_GET,H_S,CUT_CELL(ICC)%TMP(JCC))
      SP_ENTH = SP_ENTH + CUT_CELL(ICC)%RHO(JCC)*H_S*CUT_CELL(ICC)%VOLUME(JCC)
   ENDDO
ENDDO

RETURN
END SUBROUTINE ADD_Q_DOT_CUTCELLS






! ---------------------------------- GET_MUDNS_CFACE --------------------------------

SUBROUTINE GET_MUDNS_CFACE(MU_WALL,IND1,IND2)

USE PHYSICAL_FUNCTIONS, ONLY : GET_VISCOSITY

REAL(EB), INTENT(OUT)::  MU_WALL
INTEGER, INTENT(IN) :: IND1,IND2

! Local Variables:
INTEGER :: ICC, IIG, JJG, KKG

! Underlying cell value:
ICC = CUT_FACE(IND1)%CELL_LIST(2,LOW_IND,IND2)
IIG = CUT_CELL(ICC)%IJK(1)
JJG = CUT_CELL(ICC)%IJK(2)
KKG = CUT_CELL(ICC)%IJK(3)
MU_WALL = MU_DNS(IIG,JJG,KKG)

RETURN
END SUBROUTINE GET_MUDNS_CFACE

! ---------------------------------- GET_UVWGAS_CFACE --------------------------------

SUBROUTINE GET_UVWGAS_CFACE(M,U_CELL,V_CELL,W_CELL,IND1,IND2,UP,VP,WP,PREDFCT)

TYPE(MESH_TYPE), INTENT(IN), TARGET :: M
INTEGER, INTENT(IN) :: IND1,IND2
REAL(EB),INTENT(OUT):: U_CELL,V_CELL,W_CELL
REAL(EB), POINTER, DIMENSION(:,:,:), INTENT(IN) :: UP,VP,WP
REAL(EB), INTENT(IN) :: PREDFCT

! Local Variables:
REAL(EB):: AF,VELN, U_AREA, V_AREA, W_AREA, NX, NY, NZ
INTEGER :: ICC, JCC, I, J, K, NFCELL, ICCF, IFACE, LOWHIGH, X1AXIS, ILH, IFC2, IFACE2, IBOD, IWSEL

U_CELL=0._EB; V_CELL=0._EB; W_CELL=0._EB
U_AREA= 0._EB; V_AREA= 0._EB; W_AREA= 0._EB
! Finally U velocity: Compute the Area average component on each direction:
ICC = M%CUT_FACE(IND1)%CELL_LIST(2,LOW_IND,IND2)
JCC = M%CUT_FACE(IND1)%CELL_LIST(3,LOW_IND,IND2)
I = M%CUT_CELL(ICC)%IJK(IAXIS)
J = M%CUT_CELL(ICC)%IJK(JAXIS)
K = M%CUT_CELL(ICC)%IJK(KAXIS)
NFCELL=M%CUT_CELL(ICC)%CCELEM(1,JCC)
DO ICCF=1,NFCELL
   IFACE=M%CUT_CELL(ICC)%CCELEM(ICCF+1,JCC)
   SELECT CASE(M%CUT_CELL(ICC)%FACE_LIST(1,IFACE))
   CASE(CC_FTYPE_RCGAS) ! REGULAR GASPHASE
      LOWHIGH = M%CUT_CELL(ICC)%FACE_LIST(2,IFACE)
      X1AXIS  = M%CUT_CELL(ICC)%FACE_LIST(3,IFACE)
      ILH     = LOWHIGH - 1
      SELECT CASE(X1AXIS)
      CASE(IAXIS)
         AF     = M%DY(J)*M%DZ(K)
         U_CELL = U_CELL + AF*UP(I-1+ILH,J,K); U_AREA = U_AREA + AF
      CASE(JAXIS)
         AF     = M%DX(I)*M%DZ(K)
         V_CELL = V_CELL + AF*VP(I,J-1+ILH,K); V_AREA = V_AREA + AF
      CASE(KAXIS)
         AF     = M%DX(I)*M%DY(J)
         W_CELL = W_CELL + AF*WP(I,J,K-1+ILH); W_AREA = W_AREA + AF
      END SELECT

   CASE(CC_FTYPE_CFGAS)
      LOWHIGH = M%CUT_CELL(ICC)%FACE_LIST(2,IFACE)
      IFC2    = M%CUT_CELL(ICC)%FACE_LIST(4,IFACE)
      IFACE2  = M%CUT_CELL(ICC)%FACE_LIST(5,IFACE)
      X1AXIS  = M%CUT_FACE(IFC2)%IJK(KAXIS+1)
      AF      = M%CUT_FACE(IFC2)%AREA(IFACE2)
      VELN    =        PREDFCT *M%CUT_FACE(IFC2)%VEL( IFACE2) + &
                  (1._EB-PREDFCT)*M%CUT_FACE(IFC2)%VELS(IFACE2)

      SELECT CASE(X1AXIS)
      CASE(IAXIS); U_CELL= U_CELL + AF*VELN; U_AREA = U_AREA + AF
      CASE(JAXIS); V_CELL= V_CELL + AF*VELN; V_AREA = V_AREA + AF
      CASE(KAXIS); W_CELL= W_CELL + AF*VELN; W_AREA = W_AREA + AF
      END SELECT

   CASE(CC_FTYPE_CFINB)
      IFC2    = M%CUT_CELL(ICC)%FACE_LIST(4,IFACE)
      IFACE2  = M%CUT_CELL(ICC)%FACE_LIST(5,IFACE)

      AF      = M%CUT_FACE(IFC2)%AREA(IFACE2)
      ! Normal velocity defined into the body. We want velocity in direction of normal out of bod.
      VELN    = -1._EB*(       PREDFCT *M%CUT_FACE(IFC2)%VEL( IFACE2) + &
                        (1._EB-PREDFCT)*M%CUT_FACE(IFC2)%VELS(IFACE2))

      ! Fetch normal out of body on surface triangle this cface lives in:
      IBOD =M%CUT_FACE(IFC2)%BODTRI(1,IFACE2)
      IWSEL=M%CUT_FACE(IFC2)%BODTRI(2,IFACE2)
      NX = GEOMETRY(IBOD)%FACES_NORMAL(IAXIS,IWSEL)
      NY = GEOMETRY(IBOD)%FACES_NORMAL(JAXIS,IWSEL)
      NZ = GEOMETRY(IBOD)%FACES_NORMAL(KAXIS,IWSEL)
      U_CELL = U_CELL + AF*VELN*NX; U_AREA = U_AREA + AF*ABS(NX)
      V_CELL = V_CELL + AF*VELN*NY; V_AREA = V_AREA + AF*ABS(NY)
      W_CELL = W_CELL + AF*VELN*NZ; W_AREA = W_AREA + AF*ABS(NZ)
   END SELECT
ENDDO
! Normalize by area:
IF(U_AREA > TWENTY_EPSILON_EB) U_CELL = U_CELL / U_AREA
IF(V_AREA > TWENTY_EPSILON_EB) V_CELL = V_CELL / V_AREA
IF(W_AREA > TWENTY_EPSILON_EB) W_CELL = W_CELL / W_AREA

RETURN
END SUBROUTINE GET_UVWGAS_CFACE

! ----------------------------------- GET_PRES_CFACE ---------------------------------

SUBROUTINE GET_PRES_CFACE(PRESS,IND1,IND2,CFA)

TYPE(CFACE_TYPE), INTENT(IN) :: CFA
INTEGER,  INTENT( IN) :: IND1, IND2
REAL(EB), INTENT(OUT) :: PRESS

! Local Variables:
INTEGER :: ICC, IIG, JJG, KKG
TYPE(BOUNDARY_PROP1_TYPE), POINTER :: B1

B1 => BOUNDARY_PROP1(CFA%B1_INDEX)
! Underlying cell values corresponding to cut-cell:
ICC = CUT_FACE(IND1)%CELL_LIST(2,LOW_IND,IND2)
IIG = CUT_CELL(ICC)%IJK(IAXIS)
JJG = CUT_CELL(ICC)%IJK(JAXIS)
KKG = CUT_CELL(ICC)%IJK(KAXIS)
PRESS=B1%RHO_G*(H(IIG,JJG,KKG)-KRES(IIG,JJG,KKG))

RETURN
END SUBROUTINE GET_PRES_CFACE

! ----------------------------------- GET_PRES_CFACE_TEST ---------------------------------

SUBROUTINE GET_PRES_CFACE_TEST(PRESS,IND1,IND2,CFA)

TYPE(CFACE_TYPE), INTENT(IN) :: CFA
INTEGER,  INTENT( IN) :: IND1, IND2
REAL(EB), INTENT(OUT) :: PRESS
TYPE(BOUNDARY_PROP1_TYPE), POINTER :: B1

! Local Variables:
INTEGER :: VIND, EP, INT_NPE_LO, INT_NPE_HI, INPE, ICC, IIG, JJG, KKG

! Cell-centered variables:
VIND=0;  EP  =1
INT_NPE_LO  = CUT_FACE(IND1)%INT_NPE( LOW_IND,VIND,EP,IND2)
INT_NPE_HI  = CUT_FACE(IND1)%INT_NPE(HIGH_IND,VIND,EP,IND2)
IF (INT_NPE_HI > 0) THEN
   PRESS=0._EB
   DO INPE=INT_NPE_LO+1,INT_NPE_LO+INT_NPE_HI
      ! PRESS = PRESS + CUT_FACE(IND1)%INT_COEF(INPE)*CUT_FACE(IND1)%INT_CVARS( INT_P_IND,INPE)
      PRESS = PRESS + CUT_FACE(IND1)%INT_COEF(INPE)* &
      CUT_FACE(IND1)%INT_CVARS( INT_RHO_IND,INPE)*CUT_FACE(IND1)%INT_CVARS( INT_H_IND,INPE)
   ENDDO
ELSE
   B1 => BOUNDARY_PROP1(CFA%B1_INDEX)
   ! Underlying cell approximate value:
   ICC = CUT_FACE(IND1)%CELL_LIST(2,LOW_IND,IND2)
   IIG = CUT_CELL(ICC)%IJK(1)
   JJG = CUT_CELL(ICC)%IJK(2)
   KKG = CUT_CELL(ICC)%IJK(3)
   PRESS=B1%RHO_G*H(IIG,JJG,KKG)
ENDIF

RETURN
END SUBROUTINE GET_PRES_CFACE_TEST

! ------------------------------- CFACE_THERMAL_GASVARS ------------------------------

SUBROUTINE CFACE_THERMAL_GASVARS(M,ICF,SF,B1,T)
USE MATH_FUNCTIONS, ONLY: EVALUATE_RAMP
TYPE(MESH_TYPE), INTENT(INOUT), TARGET :: M
TYPE(SURFACE_TYPE), POINTER :: SF
TYPE(BOUNDARY_PROP1_TYPE) :: B1
INTEGER, INTENT(IN) :: ICF
REAL(EB),INTENT(IN) :: T

! Local Variables:
INTEGER :: IND1, IND2, ICC, JCC, I ,J ,K
REAL(EB):: PREDFCT,U_CAVG,V_CAVG,W_CAVG,K_G
REAL(EB), POINTER, DIMENSION(:,:,:) :: UP,VP,WP
TYPE(CFACE_TYPE),          POINTER :: CFA
TYPE(BOUNDARY_COORD_TYPE), POINTER :: BC

CFA => M%CFACE(ICF)
BC => M%BOUNDARY_COORD(CFA%BC_INDEX)
! Load indexes {ICF,IFACE} in CUT_FACE, for CFACE {ICFACE}:
IND1=CFA%CUT_FACE_IND1
IND2=CFA%CUT_FACE_IND2

IF (PREDICTOR) THEN
   PREDFCT=1._EB
   UP => M%U ! Corrector final velocities.
   VP => M%V
   WP => M%W
ELSE
   PREDFCT=0._EB
   UP => M%US ! Predictor final velocities.
   VP => M%VS
   WP => M%WS
ENDIF
SELECT CASE(M%CUT_FACE(IND1)%CELL_LIST(1,LOW_IND,IND2))
CASE(CC_FTYPE_CFGAS) ! Cut-cell -> use value from CUT_CELL data struct:

   ICC = M%CUT_FACE(IND1)%CELL_LIST(2,LOW_IND,IND2)
   JCC = M%CUT_FACE(IND1)%CELL_LIST(3,LOW_IND,IND2)

   I = M%CUT_CELL(ICC)%IJK(IAXIS)
   J = M%CUT_CELL(ICC)%IJK(JAXIS)
   K = M%CUT_CELL(ICC)%IJK(KAXIS)

   ! ADD CUT_CELL properties:
   IF (SF%TMP_GAS_FRONT > 0._EB) THEN
      B1%TMP_G = TMPA + EVALUATE_RAMP(T-T_BEGIN,SF%RAMP(TIME_TGF)%INDEX)*(SF%TMP_GAS_FRONT-TMPA)
   ELSE
      B1%TMP_G = M%CUT_CELL(ICC)%TMP(JCC)
   ENDIF
   CFA%RSUM_G= M%CUT_CELL(ICC)%RSUM(JCC)

   ! Mixture density and Species mass fractions:
   B1%RHO_G = PREDFCT*M%CUT_CELL(ICC)%RHOS(JCC) + (1._EB-PREDFCT)*M%CUT_CELL(ICC)%RHO(JCC)
   B1%ZZ_G(1:N_TRACKED_SPECIES) = PREDFCT *M%CUT_CELL(ICC)%ZZS(1:N_TRACKED_SPECIES,JCC) + &
                              (1._EB-PREDFCT)*M%CUT_CELL(ICC)% ZZ(1:N_TRACKED_SPECIES,JCC)

   ! Viscosity, Use MU from bearing cartesian cell:
   CFA%MU_G = M%MU(I,J,K)

   ! Gas conductivity:
   CALL GET_CC_CELL_CONDUCTIVITY(B1%ZZ_G(1:N_TRACKED_SPECIES),M%MU(I,J,K),M%MU_DNS(I,J,K),B1%TMP_G,K_G)
   B1%K_G = K_G

   CALL GET_UVWGAS_CFACE(M,U_CAVG,V_CAVG,W_CAVG,IND1,IND2,UP,VP,WP,PREDFCT)

   ! U_TANG use the norm of CC centroid area averaged velocity:
   B1%U_TANG = SQRT( U_CAVG**2._EB + V_CAVG**2._EB + W_CAVG**2._EB )

END SELECT

END SUBROUTINE CFACE_THERMAL_GASVARS



! ----------------------------- CC_RHO0W_INTERP ------------------------------

SUBROUTINE CC_RHO0W_INTERP

! Local Variables:
REAL(EB), POINTER, DIMENSION(:,:,:) :: WP
INTEGER :: NM, ICC, NCELL, ICELL
INTEGER :: I, J ,K, INBFC_CCCEN(1:3)
REAL(EB):: XYZ_PP(MAX_DIM)
REAL(EB):: TNOW
INTEGER :: INPE,INT_NPE_LO,INT_NPE_HI,EP,VIND
REAL(EB):: RHO0_EP,RHO0_BP,WCEN_EP,WCEN_BP,COEF_EP,COEF_BP

! This routines interpolates RHO_0 and W velocity component to cut-cell centers,
! It is used when stratification is .TRUE.

IF (.NOT. STRATIFICATION) RETURN
IF (PERIODIC_TEST == 103 .OR. PERIODIC_TEST == 11 .OR. PERIODIC_TEST==7) RETURN

TNOW = CURRENT_TIME()

MESH_LOOP : DO NM=1,NMESHES

   IF (PROCESS(NM)/=MY_RANK) CYCLE

   CALL POINT_TO_MESH(NM)

   IF (PREDICTOR) THEN
      WP => WS ! End of step velocities.
   ELSE
      WP => W
   ENDIF

   VIND = 0
   ICC_LOOP_3 : DO ICC=1,MESHES(NM)%N_CUTCELL_MESH
      NCELL  = CUT_CELL(ICC)%NCELL
      I      = CUT_CELL(ICC)%IJK(IAXIS)
      J      = CUT_CELL(ICC)%IJK(JAXIS)
      K      = CUT_CELL(ICC)%IJK(KAXIS)
      RHO0_BP = RHO_0(K)
      DO ICELL=1,NCELL
         RHO0_EP = 0._EB
         WCEN_EP = 0._EB
         DO EP=1,INT_N_EXT_PTS  ! External point for cell ICELL
            INT_NPE_LO = CUT_CELL(ICC)%INT_NPE(LOW_IND,VIND,EP,ICELL)
            INT_NPE_HI = CUT_CELL(ICC)%INT_NPE(HIGH_IND,VIND,EP,ICELL)
            DO INPE=INT_NPE_LO+1,INT_NPE_LO+INT_NPE_HI
               RHO0_EP = RHO0_EP + CUT_CELL(ICC)%INT_COEF(INPE)* &
                                   CUT_CELL(ICC)%INT_CCVARS(INT_RHO0_IND,INPE)
               WCEN_EP = WCEN_EP + CUT_CELL(ICC)%INT_COEF(INPE)* &
                                   CUT_CELL(ICC)%INT_CCVARS(INT_WCEN_IND,INPE)
            ENDDO
         ENDDO

         XYZ_PP(IAXIS:KAXIS) = CUT_CELL(ICC)%INT_XYZBF(IAXIS:KAXIS,ICELL)
         INBFC_CCCEN(1:3)    = CUT_CELL(ICC)%INT_INBFC(1:3,ICELL)

         CALL GET_BOUND_VEL(KAXIS,INBFC_CCCEN,XYZ_PP,WCEN_BP)

         COEF_EP = 0._EB
         IF (ABS(CUT_CELL(ICC)%INT_XN(1,ICELL)) > TWENTY_EPSILON_EB) &
         COEF_EP = CUT_CELL(ICC)%INT_XN(0,ICELL)/CUT_CELL(ICC)%INT_XN(1,ICELL)
         COEF_BP = 1._EB - COEF_EP

         !CUT_CELL(ICC)%RHO_0(ICELL) = COEF_BP*RHO0_BP + COEF_EP*RHO0_EP
         CUT_CELL(ICC)%WVEL(ICELL)  = COEF_BP*WCEN_BP + COEF_EP*WCEN_EP

      ENDDO
   ENDDO ICC_LOOP_3

   NULLIFY(WP)

ENDDO MESH_LOOP

T_USED(14) = T_USED(14) + CURRENT_TIME() - TNOW
RETURN
END SUBROUTINE CC_RHO0W_INTERP

! ------------------------------- CC_H_INTERP --------------------------------

SUBROUTINE CC_H_INTERP

! Local Variables:
REAL(EB), POINTER, DIMENSION(:,:,:) :: UP,VP,WP,HP
INTEGER :: NM, ICC, NCELL, I, J ,K
REAL(EB):: VCRT
LOGICAL :: VOLFLG

! This routine interpolates H to cut cells/Cartesian cells at the end of step.
! Makes use of dH/dXn boundary condition on immersed solid surfaces.

! Interpolate H in cut-cells:
MESH_LOOP : DO NM=LOWER_MESH_INDEX,UPPER_MESH_INDEX

   CALL POINT_TO_MESH(NM)

   IF (PREDICTOR) THEN
      HP => H
      UP => US ! End of step velocities.
      VP => VS
      WP => WS
   ELSE
      HP => HS
      UP => U ! End of step velocities.
      VP => V
      WP => W
   ENDIF

   ! Interpolate to cut-cells. Cut-cell loop:
   ICC_LOOP : DO ICC=1,MESHES(NM)%N_CUTCELL_MESH

      NCELL  = CUT_CELL(ICC)%NCELL

      I      = CUT_CELL(ICC)%IJK(IAXIS)
      J      = CUT_CELL(ICC)%IJK(JAXIS)
      K      = CUT_CELL(ICC)%IJK(KAXIS)
      VCRT   = DX(I)*DY(J)*DZ(K)

      VOLFLG = .FALSE.
      IF(NCELL > 0) VOLFLG = ABS(VCRT-CUT_CELL(ICC)%VOLUME(1)) < LOOSEPS*VCRT
      IF(PERIODIC_TEST == 103 .OR. PERIODIC_TEST == 11 .OR. PERIODIC_TEST==7 .OR. VOLFLG) THEN
         IF (PREDICTOR) THEN
            CUT_CELL(ICC)%H(1:NCELL) = HP(I,J,K)
         ELSE
            CUT_CELL(ICC)%HS(1:NCELL) = HP(I,J,K)
         ENDIF
         CYCLE
      ENDIF

      ! Unstructured projection:
      IF (.NOT.ONE_UNKH_PER_CUTCELL) THEN
         IF (PREDICTOR) THEN
            CUT_CELL(ICC)%H(1:NCELL) = HP(I,J,K) ! Use underlying value of HP.
         ELSE
            CUT_CELL(ICC)%HS(1:NCELL) = HP(I,J,K)
         ENDIF
      ENDIF

   ENDDO ICC_LOOP

   ! Finally set HP to zero inside immersed solids:
   WHERE(MESHES(NM)%CCVAR(0:IBP1,0:JBP1,0:KBP1,CC_CGSC)==CC_SOLID) HP(0:IBP1,0:JBP1,0:KBP1) = 0._EB

   ! Set velocities on solid faces to zero:
   WHERE(MESHES(NM)%FCVAR(0:IBAR,1:JBAR,1:KBAR,CC_FGSC,IAXIS)==CC_SOLID) UP(0:IBAR,1:JBAR,1:KBAR) = 0._EB
   WHERE(MESHES(NM)%FCVAR(1:IBAR,0:JBAR,1:KBAR,CC_FGSC,JAXIS)==CC_SOLID) VP(1:IBAR,0:JBAR,1:KBAR) = 0._EB
   WHERE(MESHES(NM)%FCVAR(1:IBAR,1:JBAR,0:KBAR,CC_FGSC,KAXIS)==CC_SOLID) WP(1:IBAR,1:JBAR,0:KBAR) = 0._EB

   NULLIFY(UP,VP,WP,HP)

ENDDO MESH_LOOP

RETURN
END SUBROUTINE CC_H_INTERP


! ----------------------------- CCCOMPUTE_RADIATION --------------------------------

SUBROUTINE CCCOMPUTE_RADIATION(T,NM,ITER)

! This is a temporary container where to add QR=-CHI_R*Q

INTEGER, INTENT(IN) :: NM,ITER
REAL(EB), INTENT(IN) :: T

! Local Variables:
INTEGER ICC, JCC, I, J, K, NCELL
REAL(EB):: DUMMY1
INTEGER :: DUMMY2
REAL(EB) :: TNOW

DUMMY1=T
DUMMY2=ITER

TNOW = CURRENT_TIME()

IF(.NOT.RADIATION) THEN
   IF (N_REACTIONS>0) THEN
      DO ICC=1,MESHES(NM)%N_CUTCELL_MESH
         DO JCC=1,CUT_CELL(ICC)%NCELL
            CUT_CELL(ICC)%QR(JCC) = -CUT_CELL(ICC)%CHI_R(JCC)*CUT_CELL(ICC)%Q(JCC)
         ENDDO
      ENDDO
   ENDIF
ELSE
   ! Solution for QR in underlaying Cartesian cell, coming from RADIATION_FVM
   DO ICC=1,MESHES(NM)%N_CUTCELL_MESH
      I = CUT_CELL(ICC)%IJK(IAXIS)
      J = CUT_CELL(ICC)%IJK(JAXIS)
      K = CUT_CELL(ICC)%IJK(KAXIS)
      NCELL = CUT_CELL(ICC)%NCELL
      DO JCC=1,CUT_CELL(ICC)%NCELL
         CUT_CELL(ICC)%QR(JCC) = QR(I,J,K)
      ENDDO
   ENDDO
ENDIF

T_USED(14) = T_USED(14) + CURRENT_TIME() - TNOW
IF (TIME_CC_IBM) T_CC_USED(CCCOMPUTE_RADIATION_TIME_INDEX) = T_CC_USED(CCCOMPUTE_RADIATION_TIME_INDEX) + CURRENT_TIME() - TNOW
RETURN
END SUBROUTINE CCCOMPUTE_RADIATION


! ------------------------------- GET_BOUND_VEL ---------------------------------

SUBROUTINE GET_BOUND_VEL(X1AXIS,INBFC_CFCEN,XYZ_PP,VELX1)

INTEGER, INTENT(IN) :: X1AXIS,INBFC_CFCEN(1:3)
REAL(EB),INTENT(IN) :: XYZ_PP(IAXIS:KAXIS)
REAL(EB),INTENT(OUT):: VELX1

! Local Variables
REAL(EB) :: DUMMY
INTEGER  :: IND1,IND2,ICF

VELX1 = 0._EB
! This routine computes boundary velocity of a boundary point on INBFC_CFCEN(1:3) INBOUNDARY cut-face
! with coordinates XYZ_PP. Will make use of velocity field defined on GEOMETRY.

! For now Set to CFACEs U_NORMAL or U_NORMAL_S depending on predictor or corrector:
DUMMY = XYZ_PP(X1AXIS) ! Dummy to avoid compilation warning on currently unused point location within cut-face.

! Inboundary cut-face indexes:
! INBFC_CFCEN(1) is either a point inside the Cartesian cell CC_FTYPE_CFINB, or a point in a Cartesian cell
! vertex CC_FTYPE_SVERT:
IND1=INBFC_CFCEN(2)
IND2=INBFC_CFCEN(3)
IF(IND1<=0 .OR. IND2<=0) RETURN ! If boundary cut-face undefined, with VELX1 set to 0._EB.
IF(CUT_FACE(IND1)%STATUS/=CC_INBOUNDARY) RETURN ! Return if face is not inboundary face.

ICF = CUT_FACE(IND1)%CFACE_INDEX(IND2)

IF (ICF <=0) RETURN ! This uses VELX1 = 0._EB when the inboundary cut-face used in the interpolation is located on
                    ! a ghost cell (no CFACEs are defined in ghost cells).

CFA => CFACE(ICF)
B1 => BOUNDARY_PROP1(CFA%B1_INDEX)
BC => BOUNDARY_COORD(CFA%BC_INDEX)
! Velocity into Gas Region, component along X1AXIS:
IF (PREDICTOR) THEN
   VELX1 = -B1%U_NORMAL * BC%NVEC(X1AXIS)
ELSE
   VELX1 = -B1%U_NORMAL_S* BC%NVEC(X1AXIS)
ENDIF

RETURN
END SUBROUTINE GET_BOUND_VEL


END MODULE CC_SCALARS
