!  +++++++++++++++++++++++ CC_PRESSURE_KERNELS ++++++++++++++++++++++++++

! Thread-safe computation kernels for CC pressure routines.
! Each routine takes TYPE(MESH_TYPE) as explicit argument
! instead of relying on MESH_POINTERS.

MODULE CC_PRESSURE_KERNELS

USE PRECISION_PARAMETERS
USE TYPES
USE GLOBAL_CONSTANTS
USE MESH_VARIABLES
USE COMPLEX_GEOMETRY, ONLY: CC_FTYPE_CFGAS, CC_CGSC, CC_SOLID, &
                            CC_GASPHASE, CC_IDCC, CC_IDRC, CC_UNKZ, &
                            CC_UNDEFINED, CC_FGSC, NM_START
USE CC_SCALARS_DATA, ONLY: UNKZ_IND, P_0_CV

IMPLICIT NONE (TYPE,EXTERNAL)

PRIVATE

PUBLIC :: ADD_LINKEDCELL_D_PBAR_DT, ADD_CUTCELL_D_PBAR_DT, &
          ADD_LINKEDCELL_PSUM, ADD_CUTCELL_PSUM, &
          GET_CC_UNKH, GET_CC_IROW, GET_CFACE_OPEN_BC_COEF

CONTAINS


! -------------------- ADD_LINKEDCELL_D_PBAR_DT -------------------

SUBROUTINE ADD_LINKEDCELL_D_PBAR_DT(M,I,J,K, &
   PBAR_K,D_PBAR_DT_ZONE,RTRM_CV,DIVG)

TYPE(MESH_TYPE), INTENT(IN), TARGET :: M
INTEGER, INTENT(IN)    :: I,J,K
REAL(EB),INTENT(IN)    :: PBAR_K,D_PBAR_DT_ZONE,RTRM_CV
REAL(EB),INTENT(INOUT) :: DIVG

REAL(EB):: P_BAR_CV
P_BAR_CV = PBAR_K - M%P_0(K) + &
   P_0_CV(M%CCVAR(I,J,K,CC_UNKZ)-UNKZ_IND(NM_START))

DIVG = DIVG - (1._EB/P_BAR_CV-RTRM_CV)*D_PBAR_DT_ZONE

END SUBROUTINE ADD_LINKEDCELL_D_PBAR_DT


! --------------------- ADD_CUTCELL_D_PBAR_DT ---------------------

SUBROUTINE ADD_CUTCELL_D_PBAR_DT(M,I,J,K, &
   PBAR_K,D_PBAR_DT_ZONE)

TYPE(MESH_TYPE), INTENT(INOUT), TARGET :: M
INTEGER, INTENT(IN)    :: I,J,K
REAL(EB),INTENT(IN)    :: PBAR_K,D_PBAR_DT_ZONE

TYPE(CC_CUTCELL_TYPE), POINTER :: CC
INTEGER :: JCC
REAL(EB):: P_BAR_CV

CC => M%CUT_CELL(M%CCVAR(I,J,K,CC_IDCC))

IF(PREDICTOR) THEN
   DO JCC=1,CC%NCELL
      P_BAR_CV = PBAR_K - M%P_0(K) + &
         P_0_CV(CC%UNKZ(JCC)-UNKZ_IND(NM_START))
      CC%DS(JCC) = CC%DS(JCC) - &
         (1._EB/P_BAR_CV-CC%RTRM(JCC))*D_PBAR_DT_ZONE
   ENDDO
ELSE
   DO JCC=1,CC%NCELL
      P_BAR_CV = PBAR_K - M%P_0(K) + &
         P_0_CV(CC%UNKZ(JCC)-UNKZ_IND(NM_START))
      CC%D(JCC) = CC%D(JCC) - &
         (1._EB/P_BAR_CV-CC%RTRM(JCC))*D_PBAR_DT_ZONE
   ENDDO
ENDIF

END SUBROUTINE ADD_CUTCELL_D_PBAR_DT


! ----------------------- ADD_LINKEDCELL_PSUM ---------------------

SUBROUTINE ADD_LINKEDCELL_PSUM(M,I,J,K, &
   VC,PBAR_K,RTRM_CV,PSUM_CV)

TYPE(MESH_TYPE), INTENT(IN), TARGET :: M
INTEGER, INTENT(IN)    :: I,J,K
REAL(EB),INTENT(IN)    :: VC,PBAR_K,RTRM_CV
REAL(EB),INTENT(INOUT) :: PSUM_CV

REAL(EB):: P_BAR_CV
P_BAR_CV = PBAR_K - M%P_0(K) + &
   P_0_CV(M%CCVAR(I,J,K,CC_UNKZ)-UNKZ_IND(NM_START))
PSUM_CV = PSUM_CV + VC*(1._EB/P_BAR_CV-RTRM_CV)

END SUBROUTINE ADD_LINKEDCELL_PSUM


! ----------------------- ADD_CUTCELL_PSUM ------------------------

SUBROUTINE ADD_CUTCELL_PSUM(M,I,J,K,PBAR_K,PSUM_CV)

TYPE(MESH_TYPE), INTENT(IN), TARGET :: M
INTEGER, INTENT(IN)    :: I,J,K
REAL(EB),INTENT(IN)    :: PBAR_K
REAL(EB),INTENT(INOUT) :: PSUM_CV

TYPE(CC_CUTCELL_TYPE), POINTER :: CC
INTEGER :: JCC
REAL(EB):: P_BAR_CV

CC => M%CUT_CELL(M%CCVAR(I,J,K,CC_IDCC))
DO JCC=1,CC%NCELL
   P_BAR_CV = PBAR_K - M%P_0(K) + &
      P_0_CV(CC%UNKZ(JCC)-UNKZ_IND(NM_START))
   PSUM_CV = PSUM_CV + &
      CC%VOLUME(JCC)*(1._EB/P_BAR_CV-CC%RTRM(JCC))
ENDDO

END SUBROUTINE ADD_CUTCELL_PSUM


! ----------------------------- GET_CC_UNKH -----------------------

SUBROUTINE GET_CC_UNKH(M,I,J,K,IUNKH)

TYPE(MESH_TYPE), INTENT(IN), TARGET :: M
INTEGER, INTENT(IN) :: I,J,K
INTEGER, INTENT(OUT):: IUNKH

! Local variable:
INTEGER :: ICC

IUNKH    = CC_UNDEFINED ! This is < 0.
! Check cut-cell:
ICC = M%CCVAR(I,J,K,CC_IDCC)
! If there is a cut-cell ICC then CUT_CELL(ICC)%UNKH(1) has
! been populated.
IF (ICC > 0) IUNKH = M%CUT_CELL(ICC)%UNKH(1)

RETURN
END SUBROUTINE GET_CC_UNKH


! ----------------------------- GET_CC_IROW -----------------------

SUBROUTINE GET_CC_IROW(M,I,J,K,IPZ,IROW)

TYPE(MESH_TYPE), INTENT(IN), TARGET :: M
INTEGER, INTENT(IN) :: I,J,K,IPZ
INTEGER, INTENT(OUT):: IROW

! Local variable:
INTEGER :: ICC
IROW = CC_UNDEFINED ! This is < 0.
ICC  = M%CCVAR(I,J,K,CC_IDCC)
IF (ICC > 0) IROW = M%CUT_CELL(ICC)%UNKH(1) - &
   ZONE_SOLVE(IPZ)%UNKH_IND(NM_START)

RETURN
END SUBROUTINE GET_CC_IROW


! ---------------------- GET_CFACE_OPEN_BC_COEF -------------------

SUBROUTINE GET_CFACE_OPEN_BC_COEF(M,ICF,IOR,IDX,BIJ)

TYPE(MESH_TYPE), INTENT(IN), TARGET :: M
INTEGER, INTENT(IN) :: ICF,IOR
REAL(EB),INTENT(INOUT):: IDX
REAL(EB),INTENT(OUT):: BIJ

INTEGER :: JCF,X1AXIS

BIJ = 0._EB; X1AXIS=ABS(IOR)
DO JCF=1,M%CUT_FACE(ICF)%NFACE
   IDX = 1._EB / &
      (M%CUT_FACE(ICF)%XCENHIGH(X1AXIS,JCF) - &
       M%CUT_FACE(ICF)%XCENLOW(X1AXIS,JCF))
   BIJ = BIJ + IDX*M%CUT_FACE(ICF)%AREA(JCF)
ENDDO

RETURN
END SUBROUTINE GET_CFACE_OPEN_BC_COEF

END MODULE CC_PRESSURE_KERNELS
