!> \brief ISO_C_BINDING wrappers for FDS subroutines
!> These wrappers allow C++ code (Hedgehog tasks) to call Fortran physics routines.

MODULE FDS_C_INTERFACE

USE ISO_C_BINDING
USE FDS_DRIVER
USE PRECISION_PARAMETERS
USE GLOBAL_CONSTANTS
USE MESH_VARIABLES
USE DIVG
USE PRES
USE MASS
USE PART
USE VEGE
USE VELO
USE RAD
USE WALL_ROUTINES
USE FIRE
USE TURBULENCE, ONLY: SYNTHETIC_TURBULENCE
USE CC_VELOCITY, ONLY: CC_END_STEP,CC_RESTORE_UVW_UNLINKED, &
   CC_VELOCITY_BC, CC_PROJECT_VELOCITY
USE CC_DENSITY_MOD, ONLY: CC_DENSITY
USE SOOT_ROUTINES, ONLY: CALC_AGGLOMERATION
USE HVAC_ROUTINES
USE DUMP
USE COMP_FUNCTIONS, ONLY: CURRENT_TIME
USE CONTROL_FUNCTIONS

IMPLICIT NONE (TYPE,EXTERNAL)

CONTAINS

!==============================================================================
! Initialization and finalization
!==============================================================================

SUBROUTINE C_FDS_SET_INPUT_FILE(FNAME, FLEN) BIND(C, NAME="fds_set_input_file")
    INTEGER(C_INT), VALUE :: FLEN
    CHARACTER(KIND=C_CHAR), DIMENSION(FLEN), INTENT(IN) :: FNAME
    INTEGER :: J
    FN_INPUT = ' '
    DO J=1,MIN(FLEN,LEN(FN_INPUT))
       FN_INPUT(J:J) = FNAME(J)
    ENDDO
END SUBROUTINE C_FDS_SET_INPUT_FILE

SUBROUTINE C_FDS_INIT(T_OUT, DT_OUT, NMESHES_OUT) BIND(C, NAME="fds_initialize_all")
    REAL(C_DOUBLE), INTENT(OUT) :: T_OUT, DT_OUT
    INTEGER(C_INT), INTENT(OUT) :: NMESHES_OUT
    REAL(EB) :: T_LOCAL, DT_LOCAL
    T_LOCAL = 0._EB
    DT_LOCAL = 0._EB
    CALL FDS_INIT(T_LOCAL, DT_LOCAL)
    T_OUT = T_LOCAL
    DT_OUT = DT_LOCAL
    NMESHES_OUT = NMESHES
END SUBROUTINE C_FDS_INIT

SUBROUTINE C_FDS_FINALIZE(T, DT) BIND(C, NAME="fds_finalize_all")
    REAL(C_DOUBLE), VALUE :: T, DT
    CALL FDS_FINALIZE(T, DT)
END SUBROUTINE C_FDS_FINALIZE

!==============================================================================
! State setters
!==============================================================================

SUBROUTINE C_FDS_SET_PREDICTOR(FLAG) BIND(C, NAME="fds_set_predictor")
    INTEGER(C_INT), VALUE :: FLAG
    PREDICTOR = (FLAG /= 0)
    CORRECTOR = (FLAG == 0)
END SUBROUTINE C_FDS_SET_PREDICTOR

SUBROUTINE C_FDS_SET_ICYC(VAL) BIND(C, NAME="fds_set_icyc")
    INTEGER(C_INT), VALUE :: VAL
    ICYC = VAL
END SUBROUTINE C_FDS_SET_ICYC

FUNCTION C_FDS_GET_T_END() RESULT(T_END_OUT) BIND(C, NAME="fds_get_t_end")
    REAL(C_DOUBLE) :: T_END_OUT
    T_END_OUT = T_END
END FUNCTION C_FDS_GET_T_END

FUNCTION C_FDS_GET_NMESHES() RESULT(NMESHES_OUT) BIND(C, NAME="fds_get_nmeshes")
    INTEGER(C_INT) :: NMESHES_OUT
    NMESHES_OUT = NMESHES
END FUNCTION C_FDS_GET_NMESHES

FUNCTION C_FDS_GET_LOWER_MESH_INDEX() RESULT(LOWER_OUT) BIND(C, NAME="fds_get_lower_mesh_index")
    INTEGER(C_INT) :: LOWER_OUT
    LOWER_OUT = LOWER_MESH_INDEX
END FUNCTION C_FDS_GET_LOWER_MESH_INDEX

FUNCTION C_FDS_GET_UPPER_MESH_INDEX() RESULT(UPPER_OUT) BIND(C, NAME="fds_get_upper_mesh_index")
    INTEGER(C_INT) :: UPPER_OUT
    UPPER_OUT = UPPER_MESH_INDEX
END FUNCTION C_FDS_GET_UPPER_MESH_INDEX

FUNCTION C_FDS_GET_KBAR(NM) RESULT(KBAR_OUT) BIND(C, NAME="fds_get_kbar")
    INTEGER(C_INT), VALUE :: NM
    INTEGER(C_INT) :: KBAR_OUT
    KBAR_OUT = MESHES(NM)%KBAR
END FUNCTION C_FDS_GET_KBAR

FUNCTION C_FDS_IS_CC_IBM() RESULT(FLAG) BIND(C, NAME="fds_is_cc_ibm")
    INTEGER(C_INT) :: FLAG
    IF (CC_IBM) THEN
        FLAG = 1
    ELSE
        FLAG = 0
    ENDIF
END FUNCTION C_FDS_IS_CC_IBM

! Pressure iteration state queries
FUNCTION C_FDS_USE_PRESSURE_SUBGRAPH() RESULT(FLAG) BIND(C, NAME="fds_use_pressure_subgraph")
    ! Returns 1 if conditions are met for parallel pressure sub-graph (FFT or ULMAT, non-CC_IBM, no tunnel).
    ! Requires >= 2 local meshes: single-mesh cases have no parallelism to exploit and the sub-graph
    ! loop overhead dominates. When block decomposition lands, this threshold should be revisited.
    INTEGER(C_INT) :: FLAG
    FLAG = 0
    IF (CC_IBM) RETURN
    IF (TUNNEL_PRECONDITIONER) RETURN
    IF (PRES_FLAG /= FFT_FLAG .AND. PRES_FLAG /= ULMAT_FLAG) RETURN
    IF (UPPER_MESH_INDEX - LOWER_MESH_INDEX + 1 < 2) RETURN
    FLAG = 1
END FUNCTION C_FDS_USE_PRESSURE_SUBGRAPH

FUNCTION C_FDS_ITERATE_PRESSURE() RESULT(FLAG) BIND(C, NAME="fds_iterate_pressure")
    INTEGER(C_INT) :: FLAG
    IF (ITERATE_PRESSURE) THEN; FLAG = 1; ELSE; FLAG = 0; ENDIF
END FUNCTION C_FDS_ITERATE_PRESSURE

FUNCTION C_FDS_GET_PRES_FLAG() RESULT(FLAG) BIND(C, NAME="fds_get_pres_flag")
    INTEGER(C_INT) :: FLAG
    FLAG = PRES_FLAG
END FUNCTION C_FDS_GET_PRES_FLAG

SUBROUTINE C_FDS_ZERO_Q_M_DOT() BIND(C, NAME="fds_zero_q_m_dot")
    Q_DOT = 0._EB
    M_DOT = 0._EB
END SUBROUTINE C_FDS_ZERO_Q_M_DOT

FUNCTION C_FDS_ADJUST_DT(T_IN, DT_IN) RESULT(DT_OUT) BIND(C, NAME="fds_adjust_dt")
    REAL(C_DOUBLE), VALUE :: T_IN, DT_IN
    REAL(C_DOUBLE) :: DT_OUT
    DT_OUT = DT_IN
    ! Replicate the DT adjustment logic from the top of MAIN_LOOP
    IF (ALL(CHANGE_TIME_STEP_INDEX==1)) DT_OUT = MINVAL(DT_NEW)
    IF (ANY(CHANGE_TIME_STEP_INDEX==-1)) DT_OUT = MINVAL(DT_NEW)
    ! Clip final time step
    IF ((T_IN+DT_OUT+DT_END_FILL)>T_END) DT_OUT = MAX(T_END-T_IN+TWENTY_EPSILON_EB,DT_END_MINIMUM)
END FUNCTION C_FDS_ADJUST_DT

!==============================================================================
! Predictor phase subroutines
!==============================================================================

SUBROUTINE C_FDS_INSERT_PARTICLES(T, NM) BIND(C, NAME="fds_insert_particles")
    REAL(C_DOUBLE), VALUE :: T
    INTEGER(C_INT), VALUE :: NM
    CALL INSERT_ALL_PARTICLES(T, NM)
END SUBROUTINE C_FDS_INSERT_PARTICLES

SUBROUTINE C_FDS_COMPUTE_VISCOSITY(NM, ESTIMATED) BIND(C, NAME="fds_compute_viscosity")
    INTEGER(C_INT), VALUE :: NM, ESTIMATED
    CALL COMPUTE_VISCOSITY(NM, APPLY_TO_ESTIMATED_VARIABLES=(ESTIMATED/=0))
END SUBROUTINE C_FDS_COMPUTE_VISCOSITY

SUBROUTINE C_FDS_MASS_FINITE_DIFF(NM) BIND(C, NAME="fds_mass_finite_differences")
    INTEGER(C_INT), VALUE :: NM
    CALL MASS_FINITE_DIFFERENCES_NEW(NM)
END SUBROUTINE C_FDS_MASS_FINITE_DIFF

SUBROUTINE C_FDS_DENSITY(T, DT, NM) BIND(C, NAME="fds_density")
    REAL(C_DOUBLE), VALUE :: T, DT
    INTEGER(C_INT), VALUE :: NM
    CALL DENSITY(T, DT, NM)
END SUBROUTINE C_FDS_DENSITY

SUBROUTINE C_FDS_CC_DENSITY(T, DT) BIND(C, NAME="fds_cc_density")
    REAL(C_DOUBLE), VALUE :: T, DT
    IF (CC_IBM) CALL CC_DENSITY(T, DT)
END SUBROUTINE C_FDS_CC_DENSITY

SUBROUTINE C_FDS_VISCOSITY_BC(NM, ESTIMATED) BIND(C, NAME="fds_viscosity_bc")
    INTEGER(C_INT), VALUE :: NM, ESTIMATED
    CALL VISCOSITY_BC(NM, APPLY_TO_ESTIMATED_VARIABLES=(ESTIMATED/=0))
END SUBROUTINE C_FDS_VISCOSITY_BC

SUBROUTINE C_FDS_VELOCITY_FLUX(T, DT, NM, ESTIMATED) BIND(C, NAME="fds_velocity_flux")
    REAL(C_DOUBLE), VALUE :: T, DT
    INTEGER(C_INT), VALUE :: NM, ESTIMATED
    IF (.NOT.CYLINDRICAL) CALL VELOCITY_FLUX(T, DT, NM, APPLY_TO_ESTIMATED_VARIABLES=(ESTIMATED/=0))
    IF (     CYLINDRICAL) CALL VELOCITY_FLUX_CYLINDRICAL(T, NM, APPLY_TO_ESTIMATED_VARIABLES=(ESTIMATED/=0))
END SUBROUTINE C_FDS_VELOCITY_FLUX

SUBROUTINE C_FDS_WALL_BC(T, DT, NM) BIND(C, NAME="fds_wall_bc")
    REAL(C_DOUBLE), VALUE :: T, DT
    INTEGER(C_INT), VALUE :: NM
    CALL WALL_BC(T, DT, NM)
END SUBROUTINE C_FDS_WALL_BC

SUBROUTINE C_FDS_PARTICLE_MOMENTUM(DT, NM) BIND(C, NAME="fds_particle_momentum")
    REAL(C_DOUBLE), VALUE :: DT
    INTEGER(C_INT), VALUE :: NM
    IF (PARTICLE_DRAG) CALL PARTICLE_MOMENTUM_TRANSFER(DT, NM)
END SUBROUTINE C_FDS_PARTICLE_MOMENTUM

SUBROUTINE C_FDS_DIVERGENCE_PART_1(T, DT, NM) BIND(C, NAME="fds_divergence_part_1")
    REAL(C_DOUBLE), VALUE :: T, DT
    INTEGER(C_INT), VALUE :: NM
    CALL DIVERGENCE_PART_1(T, DT, NM)
END SUBROUTINE C_FDS_DIVERGENCE_PART_1

SUBROUTINE C_FDS_DIVERGENCE_PART_2(DT, NM) BIND(C, NAME="fds_divergence_part_2")
    REAL(C_DOUBLE), VALUE :: DT
    INTEGER(C_INT), VALUE :: NM
    CALL DIVERGENCE_PART_2(DT, NM)
END SUBROUTINE C_FDS_DIVERGENCE_PART_2

SUBROUTINE C_FDS_INIT_CHANGE_TIME_STEP(DT) BIND(C, NAME="fds_init_change_time_step")
    REAL(C_DOUBLE), VALUE :: DT
    CHANGE_TIME_STEP_INDEX = 0
    DT_NEW = DT
END SUBROUTINE C_FDS_INIT_CHANGE_TIME_STEP

SUBROUTINE C_FDS_SET_FIRST_PASS(FLAG) BIND(C, NAME="fds_set_first_pass")
    INTEGER(C_INT), VALUE :: FLAG
    FIRST_PASS = (FLAG /= 0)
END SUBROUTINE C_FDS_SET_FIRST_PASS

SUBROUTINE C_FDS_CHECK_CHANGE_TIME_STEP(NEED_RETRY, DT_OUT) BIND(C, NAME="fds_check_change_time_step")
    INTEGER(C_INT), INTENT(OUT) :: NEED_RETRY
    REAL(C_DOUBLE), INTENT(OUT) :: DT_OUT
    ! In original main.f90 (lines 753-758):
    ! If ANY mesh has CHANGE_TIME_STEP_INDEX==-1, DT = MINVAL(DT_NEW) and retry
    ! Otherwise exit (time step increase handled at next MAIN_LOOP iteration)
    IF (ANY(CHANGE_TIME_STEP_INDEX==-1)) THEN
        DT_OUT = MINVAL(DT_NEW)
        NEED_RETRY = 1
    ELSE
        DT_OUT = 0._EB  ! unused
        NEED_RETRY = 0
    ENDIF
END SUBROUTINE C_FDS_CHECK_CHANGE_TIME_STEP

SUBROUTINE C_FDS_CC_RESTORE_UVW(NM) BIND(C, NAME="fds_cc_restore_uvw_unlinked")
    INTEGER(C_INT), VALUE :: NM
    IF (CC_IBM) CALL CC_RESTORE_UVW_UNLINKED(NM, ASSIGN_UNLINKED_VEL=.TRUE.)
END SUBROUTINE C_FDS_CC_RESTORE_UVW

SUBROUTINE C_FDS_VELOCITY_PREDICTOR(T_PLUS_DT, DT, NM) BIND(C, NAME="fds_velocity_predictor")
    REAL(C_DOUBLE), VALUE :: T_PLUS_DT, DT
    INTEGER(C_INT), VALUE :: NM
    CALL VELOCITY_PREDICTOR(T_PLUS_DT, DT, DT_NEW, NM)
END SUBROUTINE C_FDS_VELOCITY_PREDICTOR

SUBROUTINE C_FDS_STOP_CHECK_ZERO() BIND(C, NAME="fds_stop_check_zero")
    CALL STOP_CHECK_DRIVER(0, 0._EB, 0._EB)
END SUBROUTINE C_FDS_STOP_CHECK_ZERO

SUBROUTINE C_FDS_VELOCITY_CORRECTOR(T, DT, NM) BIND(C, NAME="fds_velocity_corrector")
    REAL(C_DOUBLE), VALUE :: T, DT
    INTEGER(C_INT), VALUE :: NM
    CALL VELOCITY_CORRECTOR(T, DT, NM)
END SUBROUTINE C_FDS_VELOCITY_CORRECTOR

SUBROUTINE C_FDS_MATCH_VELOCITY(NM) BIND(C, NAME="fds_match_velocity")
    INTEGER(C_INT), VALUE :: NM
    CALL MATCH_VELOCITY(NM)
END SUBROUTINE C_FDS_MATCH_VELOCITY

SUBROUTINE C_FDS_MATCH_VELOCITY_KERNEL(NM, IS_PREDICTOR) &
    BIND(C, NAME="fds_match_velocity_kernel")
    USE VELO_KERNELS, ONLY: MATCH_VELOCITY_KERNEL
    USE CC_VELOCITY, ONLY: CC_MATCH_VELOCITY
    INTEGER(C_INT), VALUE :: NM, IS_PREDICTOR
    IF (SOLID_PHASE_ONLY) RETURN
    IF (CC_IBM) THEN
       CALL CC_MATCH_VELOCITY(NM, (IS_PREDICTOR/=0), .TRUE.)
    ELSE
       CALL MATCH_VELOCITY_KERNEL(MESHES(NM), NM, &
                                   PREDICTOR_FLAG=(IS_PREDICTOR/=0))
    ENDIF
END SUBROUTINE C_FDS_MATCH_VELOCITY_KERNEL

SUBROUTINE C_FDS_VELOCITY_BC(T, NM, ESTIMATED) BIND(C, NAME="fds_velocity_bc")
    REAL(C_DOUBLE), VALUE :: T
    INTEGER(C_INT), VALUE :: NM, ESTIMATED
    CALL VELOCITY_BC(T, NM, APPLY_TO_ESTIMATED_VARIABLES=(ESTIMATED/=0))
END SUBROUTINE C_FDS_VELOCITY_BC

SUBROUTINE C_FDS_VELOCITY_BC_PREPROCESSING(NM, T, APPLY_TO_ESTIMATED) &
    BIND(C, NAME="fds_velocity_bc_preprocessing")
    INTEGER(C_INT), VALUE :: NM, APPLY_TO_ESTIMATED
    REAL(C_DOUBLE), VALUE :: T
    IF (SOLID_PHASE_ONLY) RETURN
    CALL VELOCITY_BC_PREPROCESSING(MESHES(NM), NM, T, &
                                    APPLY_TO_ESTIMATED_VARIABLES=(APPLY_TO_ESTIMATED/=0))
END SUBROUTINE C_FDS_VELOCITY_BC_PREPROCESSING

RECURSIVE SUBROUTINE C_FDS_VELOCITY_BC_PROCESS_EDGES_KERNEL(NM, T, APPLY_TO_ESTIMATED) &
    BIND(C, NAME="fds_velocity_bc_process_edges_kernel")
    USE VELO_KERNELS, ONLY: VELOCITY_BC_PROCESS_EDGES_KERNEL
    INTEGER(C_INT), VALUE :: NM, APPLY_TO_ESTIMATED
    REAL(C_DOUBLE), VALUE :: T
    IF (SOLID_PHASE_ONLY) RETURN
    CALL VELOCITY_BC_PROCESS_EDGES_KERNEL(MESHES(NM), NM, T, &
                                           APPLY_TO_ESTIMATED_VARIABLES=(APPLY_TO_ESTIMATED/=0))
END SUBROUTINE C_FDS_VELOCITY_BC_PROCESS_EDGES_KERNEL

SUBROUTINE C_FDS_SET_DRAG_UVWMAX(NM, VAL) BIND(C, NAME="fds_set_drag_uvwmax")
    INTEGER(C_INT), VALUE :: NM
    REAL(C_DOUBLE), VALUE :: VAL
    MESHES(NM)%DRAG_UVWMAX = VAL
END SUBROUTINE C_FDS_SET_DRAG_UVWMAX

RECURSIVE SUBROUTINE C_FDS_VELOCITY_BC_PROCESS_EDGES_BLOCK_KERNEL(NM, T, APPLY_TO_ESTIMATED, K1, K2, DRAG_OUT) &
    BIND(C, NAME="fds_velocity_bc_process_edges_block_kernel")
    USE VELO_KERNELS, ONLY: VELOCITY_BC_PROCESS_EDGES_KERNEL
    INTEGER(C_INT), VALUE :: NM, APPLY_TO_ESTIMATED, K1, K2
    REAL(C_DOUBLE), VALUE :: T
    REAL(C_DOUBLE), INTENT(INOUT) :: DRAG_OUT
    IF (SOLID_PHASE_ONLY) RETURN
    DRAG_OUT = 0._EB
    CALL VELOCITY_BC_PROCESS_EDGES_KERNEL(MESHES(NM), NM, T, &
         APPLY_TO_ESTIMATED_VARIABLES=(APPLY_TO_ESTIMATED/=0), &
         K1_IN=K1, K2_IN=K2, DRAG_UVWMAX_LOCAL=DRAG_OUT)
END SUBROUTINE C_FDS_VELOCITY_BC_PROCESS_EDGES_BLOCK_KERNEL

SUBROUTINE C_FDS_SYNTHETIC_TURBULENCE_IF_ENABLED(DT, T, NM) &
    BIND(C, NAME="fds_synthetic_turbulence_if_enabled")
    REAL(C_DOUBLE), VALUE :: DT, T
    INTEGER(C_INT), VALUE :: NM
    IF (SYNTHETIC_EDDY_METHOD) CALL SYNTHETIC_TURBULENCE(DT, T, NM)
END SUBROUTINE C_FDS_SYNTHETIC_TURBULENCE_IF_ENABLED

!==============================================================================
! Corrector phase subroutines
!==============================================================================

SUBROUTINE C_FDS_COMBUSTION_BC(NM) BIND(C, NAME="fds_combustion_bc")
    INTEGER(C_INT), VALUE :: NM
    IF (N_REACTIONS>0 .OR. INIT_HRRPUV) CALL COMBUSTION_BC(NM)
END SUBROUTINE C_FDS_COMBUSTION_BC

SUBROUTINE C_FDS_COMBUSTION_LOAD_BALANCED(T, DT) BIND(C, NAME="fds_combustion")
    REAL(C_DOUBLE), VALUE :: T, DT
    IF (N_REACTIONS > 0 .OR. INIT_HRRPUV) CALL COMBUSTION_LOAD_BALANCED(T, DT)
END SUBROUTINE C_FDS_COMBUSTION_LOAD_BALANCED

SUBROUTINE C_FDS_COMBUSTION_KERNEL(NM, T, DT) BIND(C, NAME="fds_combustion_kernel")
    INTEGER(C_INT), VALUE :: NM
    REAL(C_DOUBLE), VALUE :: T, DT
    IF (N_REACTIONS > 0 .OR. INIT_HRRPUV) CALL COMBUSTION_GENERAL_KERNEL(NM, T, DT)
END SUBROUTINE C_FDS_COMBUSTION_KERNEL

SUBROUTINE C_FDS_SOOT_OXIDATION_LOOP(DT_VAL) BIND(C, NAME="fds_soot_oxidation_loop")
    USE SOOT_ROUTINES, ONLY: SOOT_SURFACE_OXIDATION
    USE MESH_POINTERS
    REAL(C_DOUBLE), VALUE :: DT_VAL
    INTEGER :: NM
    IF (DEPOSITION .AND. SOOT_OXIDATION) THEN
        DO NM=LOWER_MESH_INDEX,UPPER_MESH_INDEX
            CALL POINT_TO_MESH(NM)
            CALL SOOT_SURFACE_OXIDATION(DT_VAL, NM)
        ENDDO
    ENDIF
END SUBROUTINE C_FDS_SOOT_OXIDATION_LOOP

SUBROUTINE C_FDS_CONDENSATION(DT, NM) BIND(C, NAME="fds_condensation")
    REAL(C_DOUBLE), VALUE :: DT
    INTEGER(C_INT), VALUE :: NM
    IF (ANY(SPECIES_MIXTURE%CONDENSATION_SMIX_INDEX>0)) CALL CONDENSATION_EVAPORATION(DT, NM)
END SUBROUTINE C_FDS_CONDENSATION

SUBROUTINE C_FDS_PARTICLE_MASS_ENERGY(T, DT, NM) BIND(C, NAME="fds_particle_mass_energy")
    REAL(C_DOUBLE), VALUE :: T, DT
    INTEGER(C_INT), VALUE :: NM
    CALL PARTICLE_MASS_ENERGY_TRANSFER(T, DT, NM)
END SUBROUTINE C_FDS_PARTICLE_MASS_ENERGY

SUBROUTINE C_FDS_PARTICLE_MASS_ENERGY_KERNEL(NM, T, DT) BIND(C, NAME="fds_particle_mass_energy_kernel")
    INTEGER(C_INT), VALUE :: NM
    REAL(C_DOUBLE), VALUE :: T, DT
    CALL PARTICLE_MASS_ENERGY_KERNEL(NM, T, DT)
END SUBROUTINE C_FDS_PARTICLE_MASS_ENERGY_KERNEL

SUBROUTINE C_FDS_REMOVE_PARTICLES(T, NM) BIND(C, NAME="fds_remove_particles")
    USE MESH_POINTERS, ONLY: POINT_TO_MESH
    REAL(C_DOUBLE), VALUE :: T
    INTEGER(C_INT), VALUE :: NM
    CALL POINT_TO_MESH(NM)
    CALL REMOVE_PARTICLES(T, NM)
END SUBROUTINE C_FDS_REMOVE_PARTICLES

SUBROUTINE C_FDS_MOVE_PARTICLES(T, DT, NM) BIND(C, NAME="fds_move_particles")
    REAL(C_DOUBLE), VALUE :: T, DT
    INTEGER(C_INT), VALUE :: NM
    CALL MOVE_PARTICLES(T, DT, NM)
END SUBROUTINE C_FDS_MOVE_PARTICLES

SUBROUTINE C_FDS_COMPUTE_RADIATION(T, NM, RAD_ITER) BIND(C, NAME="fds_compute_radiation")
    REAL(C_DOUBLE), VALUE :: T
    INTEGER(C_INT), VALUE :: NM, RAD_ITER
    CALL COMPUTE_RADIATION(T, NM, RAD_ITER)
END SUBROUTINE C_FDS_COMPUTE_RADIATION

RECURSIVE SUBROUTINE C_FDS_COMPUTE_RADIATION_KERNEL(NM, T, RAD_ITER, &
    RAD_Q_SUM_OUT, KFST4_SUM_OUT) BIND(C, NAME="fds_compute_radiation_kernel")
    USE RAD, ONLY: COMPUTE_RADIATION_KERNEL
    USE MESH_VARIABLES, ONLY: MESHES
    INTEGER(C_INT), VALUE :: NM, RAD_ITER
    REAL(C_DOUBLE), VALUE :: T
    REAL(C_DOUBLE), INTENT(INOUT) :: RAD_Q_SUM_OUT, KFST4_SUM_OUT
    CALL COMPUTE_RADIATION_KERNEL(MESHES(NM), NM, T, RAD_ITER, &
        RAD_Q_SUM_OUT, KFST4_SUM_OUT)
END SUBROUTINE C_FDS_COMPUTE_RADIATION_KERNEL

SUBROUTINE C_FDS_AGGLOMERATION(DT, NM) BIND(C, NAME="fds_agglomeration")
    REAL(C_DOUBLE), VALUE :: DT
    INTEGER(C_INT), VALUE :: NM
    IF (N_AGGLOMERATION_SPECIES > 0) CALL CALC_AGGLOMERATION(MESHES(NM), DT, NM)
END SUBROUTINE C_FDS_AGGLOMERATION

SUBROUTINE C_FDS_CC_END_STEP(T, DT, DIAG) BIND(C, NAME="fds_cc_end_step")
    REAL(C_DOUBLE), VALUE :: T, DT
    INTEGER(C_INT), VALUE :: DIAG
    IF (CC_IBM) CALL CC_END_STEP(T, DT, (DIAG/=0))
END SUBROUTINE C_FDS_CC_END_STEP

SUBROUTINE C_FDS_CHECK_DIVERGENCE(NM) BIND(C, NAME="fds_check_divergence")
    INTEGER(C_INT), VALUE :: NM
    CALL CHECK_DIVERGENCE(NM)
END SUBROUTINE C_FDS_CHECK_DIVERGENCE

!==============================================================================
! Thread-safe kernel wrappers (bypass orchestration, call kernels directly)
! RECURSIVE keyword ensures thread-safety (does not propagate to callees)
!==============================================================================

RECURSIVE SUBROUTINE C_FDS_VELOCITY_CORRECTOR_KERNEL(NM, T, DT) BIND(C, NAME="fds_velocity_corrector_kernel")
    USE VELO_KERNELS, ONLY: VELOCITY_CORRECTOR_KERNEL
    USE MESH_VARIABLES, ONLY: MESHES
    INTEGER(C_INT), VALUE :: NM
    REAL(C_DOUBLE), VALUE :: T, DT
    ! Call kernel directly without POINT_TO_MESH - thread-safe
    CALL VELOCITY_CORRECTOR_KERNEL(MESHES(NM), DT)
END SUBROUTINE C_FDS_VELOCITY_CORRECTOR_KERNEL

RECURSIVE SUBROUTINE C_FDS_VELOCITY_PREDICTOR_BLOCK_KERNEL(NM, DT, K1, K2) &
    BIND(C, NAME="fds_velocity_predictor_block_kernel")
    USE VELO_KERNELS, ONLY: VELOCITY_PREDICTOR_BLOCK_KERNEL
    USE MESH_VARIABLES, ONLY: MESHES
    INTEGER(C_INT), VALUE :: NM, K1, K2
    REAL(C_DOUBLE), VALUE :: DT
    CALL VELOCITY_PREDICTOR_BLOCK_KERNEL(MESHES(NM), DT, K1, K2)
END SUBROUTINE C_FDS_VELOCITY_PREDICTOR_BLOCK_KERNEL

RECURSIVE SUBROUTINE C_FDS_VELOCITY_CORRECTOR_BLOCK_KERNEL(NM, DT, K1, K2) &
    BIND(C, NAME="fds_velocity_corrector_block_kernel")
    USE VELO_KERNELS, ONLY: VELOCITY_CORRECTOR_BLOCK_KERNEL
    USE MESH_VARIABLES, ONLY: MESHES
    INTEGER(C_INT), VALUE :: NM, K1, K2
    REAL(C_DOUBLE), VALUE :: DT
    CALL VELOCITY_CORRECTOR_BLOCK_KERNEL(MESHES(NM), DT, K1, K2)
END SUBROUTINE C_FDS_VELOCITY_CORRECTOR_BLOCK_KERNEL

RECURSIVE SUBROUTINE C_FDS_VELOCITY_PREDICTOR_KERNEL(NM, T, DT) BIND(C, NAME="fds_velocity_predictor_kernel")
    USE VELO_KERNELS, ONLY: VELOCITY_PREDICTOR_KERNEL, &
                            CHECK_STABILITY_KERNEL
    USE MESH_VARIABLES, ONLY: MESHES
    INTEGER(C_INT), VALUE :: NM
    REAL(C_DOUBLE), VALUE :: T, DT
    IF (SOLID_PHASE_ONLY) RETURN
    ! Call kernels directly without POINT_TO_MESH - thread-safe
    CALL VELOCITY_PREDICTOR_KERNEL(MESHES(NM), DT)
    CALL CHECK_STABILITY_KERNEL( &
        MESHES(NM), DT, DT_NEW(NM), T, NM)
    ! Instability check (matches velo.f90:613-614)
    IF (DT_NEW(NM)<DT_INITIAL*LIMITING_DT_RATIO &
        .AND. (T+DT_NEW(NM)<(T_END-TWENTY_EPSILON_EB))) &
        STOP_STATUS = INSTABILITY_STOP
END SUBROUTINE C_FDS_VELOCITY_PREDICTOR_KERNEL

!> Velocity predictor kernel only (no CFL check).
!> Used for CC_IBM cases where CHECK_STABILITY must run AFTER
!> CC_PROJECT_VELOCITY and WALL_VELOCITY_NO_GRADH.
RECURSIVE SUBROUTINE C_FDS_VELOCITY_PREDICTOR_KERNEL_ONLY(NM, DT) &
    BIND(C, NAME="fds_velocity_predictor_kernel_only")
    USE VELO_KERNELS, ONLY: VELOCITY_PREDICTOR_KERNEL
    USE MESH_VARIABLES, ONLY: MESHES
    INTEGER(C_INT), VALUE :: NM
    REAL(C_DOUBLE), VALUE :: DT
    IF (SOLID_PHASE_ONLY) RETURN
    CALL VELOCITY_PREDICTOR_KERNEL(MESHES(NM), DT)
END SUBROUTINE C_FDS_VELOCITY_PREDICTOR_KERNEL_ONLY

!> Standalone CFL stability check.
!> Used after CC_PROJECT_VELOCITY + WALL_VELOCITY_NO_GRADH for CC_IBM.
SUBROUTINE C_FDS_CHECK_STABILITY_KERNEL(NM, T, DT) &
    BIND(C, NAME="fds_check_stability_kernel_only")
    USE VELO_KERNELS, ONLY: CHECK_STABILITY_KERNEL
    USE MESH_VARIABLES, ONLY: MESHES
    INTEGER(C_INT), VALUE :: NM
    REAL(C_DOUBLE), VALUE :: T, DT
    IF (SOLID_PHASE_ONLY) RETURN
    CALL CHECK_STABILITY_KERNEL( &
        MESHES(NM), DT, DT_NEW(NM), T, NM)
    IF (DT_NEW(NM)<DT_INITIAL*LIMITING_DT_RATIO &
        .AND. (T+DT_NEW(NM)<(T_END-TWENTY_EPSILON_EB))) &
        STOP_STATUS = INSTABILITY_STOP
END SUBROUTINE C_FDS_CHECK_STABILITY_KERNEL

RECURSIVE SUBROUTINE C_FDS_CHECK_DIVERGENCE_KERNEL(NM) BIND(C, NAME="fds_check_divergence_kernel")
    USE DIVG_KERNELS, ONLY: CHECK_DIVERGENCE_KERNEL
    USE MESH_VARIABLES, ONLY: MESHES
    INTEGER(C_INT), VALUE :: NM
    ! Call kernel directly without POINT_TO_MESH - thread-safe
    CALL CHECK_DIVERGENCE_KERNEL(MESHES(NM))
END SUBROUTINE C_FDS_CHECK_DIVERGENCE_KERNEL

RECURSIVE SUBROUTINE C_FDS_DIVERGENCE_PART_2_KERNEL(NM, DT) BIND(C, NAME="fds_divergence_part_2_kernel")
    USE DIVG_KERNELS, ONLY: DIVERGENCE_PART_2_KERNEL
    USE MESH_VARIABLES, ONLY: MESHES
    INTEGER(C_INT), VALUE :: NM
    REAL(C_DOUBLE), VALUE :: DT
    ! Call kernel directly without POINT_TO_MESH - thread-safe
    CALL DIVERGENCE_PART_2_KERNEL(MESHES(NM), DT, NM)
END SUBROUTINE C_FDS_DIVERGENCE_PART_2_KERNEL

RECURSIVE SUBROUTINE C_FDS_DIVERGENCE_PART_2_PREPROCESSING(NM, DT) &
    BIND(C, NAME="fds_divergence_part_2_preprocessing")
    USE DIVG_KERNELS, ONLY: DIVERGENCE_PART_2_PREPROCESSING
    USE MESH_VARIABLES, ONLY: MESHES
    INTEGER(C_INT), VALUE :: NM
    REAL(C_DOUBLE), VALUE :: DT
    CALL DIVERGENCE_PART_2_PREPROCESSING(MESHES(NM), DT, NM)
END SUBROUTINE C_FDS_DIVERGENCE_PART_2_PREPROCESSING

RECURSIVE SUBROUTINE C_FDS_DIVERGENCE_PART_2_BLOCK_KERNEL(NM, DT, K1, K2) &
    BIND(C, NAME="fds_divergence_part_2_block_kernel")
    USE DIVG_KERNELS, ONLY: DIVERGENCE_PART_2_BLOCK_KERNEL
    USE MESH_VARIABLES, ONLY: MESHES
    INTEGER(C_INT), VALUE :: NM, K1, K2
    REAL(C_DOUBLE), VALUE :: DT
    CALL DIVERGENCE_PART_2_BLOCK_KERNEL(MESHES(NM), DT, NM, K1, K2)
END SUBROUTINE C_FDS_DIVERGENCE_PART_2_BLOCK_KERNEL

FUNCTION C_FDS_DIVERGENCE_PART_2_CAN_BLOCK_DECOMPOSE() RESULT(RES) &
    BIND(C, NAME="fds_divergence_part_2_can_block_decompose")
    USE GLOBAL_CONSTANTS, ONLY: CC_IBM
    INTEGER(C_INT) :: RES
    IF (CC_IBM) THEN
       RES = 0
    ELSE
       RES = 1
    ENDIF
END FUNCTION C_FDS_DIVERGENCE_PART_2_CAN_BLOCK_DECOMPOSE

RECURSIVE SUBROUTINE C_FDS_COMPUTE_VISCOSITY_KERNEL(NM, ESTIMATED) BIND(C, NAME="fds_compute_viscosity_kernel")
    USE VELO_KERNELS, ONLY: COMPUTE_VISCOSITY_KERNEL
    USE MESH_VARIABLES, ONLY: MESHES
    INTEGER(C_INT), VALUE :: NM, ESTIMATED
    CALL COMPUTE_VISCOSITY_KERNEL(MESHES(NM), NM, &
        APPLY_TO_ESTIMATED_VARIABLES=(ESTIMATED/=0))
END SUBROUTINE C_FDS_COMPUTE_VISCOSITY_KERNEL

RECURSIVE SUBROUTINE C_FDS_COMPUTE_VISCOSITY_BLOCK_KERNEL(NM, ESTIMATED, K1, K2) &
    BIND(C, NAME="fds_compute_viscosity_block_kernel")
    USE VELO_KERNELS, ONLY: COMPUTE_VISCOSITY_BLOCK_KERNEL
    USE MESH_VARIABLES, ONLY: MESHES
    INTEGER(C_INT), VALUE :: NM, ESTIMATED, K1, K2
    CALL COMPUTE_VISCOSITY_BLOCK_KERNEL(MESHES(NM), NM, &
        APPLY_TO_ESTIMATED_VARIABLES=(ESTIMATED/=0), K1=K1, K2=K2)
END SUBROUTINE C_FDS_COMPUTE_VISCOSITY_BLOCK_KERNEL

RECURSIVE SUBROUTINE C_FDS_COMPUTE_VISCOSITY_POST_BLOCK(NM, ESTIMATED) &
    BIND(C, NAME="fds_compute_viscosity_post_block")
    USE VELO_KERNELS, ONLY: COMPUTE_VISCOSITY_POST_BLOCK
    USE MESH_VARIABLES, ONLY: MESHES
    INTEGER(C_INT), VALUE :: NM, ESTIMATED
    CALL COMPUTE_VISCOSITY_POST_BLOCK(MESHES(NM), NM, &
        APPLY_TO_ESTIMATED_VARIABLES=(ESTIMATED/=0))
END SUBROUTINE C_FDS_COMPUTE_VISCOSITY_POST_BLOCK

FUNCTION C_FDS_COMPUTE_VISCOSITY_CAN_BLOCK() RESULT(CAN) &
    BIND(C, NAME="fds_compute_viscosity_can_block_decompose")
    INTEGER(C_INT) :: CAN
    CAN = 1
    ! DEARDORFF needs FILL_EDGES + TEST_FILTER (full mesh)
    ! DYNSMAG needs VARDEN_DYNSMAG_KERNEL (full mesh)
    IF (TURB_MODEL==DEARDORFF .OR. TURB_MODEL==DYNSMAG) CAN = 0
END FUNCTION C_FDS_COMPUTE_VISCOSITY_CAN_BLOCK

SUBROUTINE C_FDS_CUTFACE_VELOCITIES(NM, ESTIMATED, CUTFACES_FLAG) &
    BIND(C, NAME="fds_cutface_velocities")
    USE CC_VELOCITY_KERNELS, ONLY: CUTFACE_VELOCITIES
    USE MESH_VARIABLES, ONLY: MESHES
    INTEGER(C_INT), VALUE :: NM, ESTIMATED, CUTFACES_FLAG
    REAL(EB), POINTER, DIMENSION(:,:,:) :: UU, VV, WW
    IF (ESTIMATED /= 0) THEN
        UU => MESHES(NM)%US; VV => MESHES(NM)%VS; WW => MESHES(NM)%WS
    ELSE
        UU => MESHES(NM)%U; VV => MESHES(NM)%V; WW => MESHES(NM)%W
    ENDIF
    CALL CUTFACE_VELOCITIES(MESHES(NM), UU, VV, WW, &
        CUTFACES=(CUTFACES_FLAG/=0))
END SUBROUTINE C_FDS_CUTFACE_VELOCITIES

SUBROUTINE C_FDS_CC_VELOCITY_FLUX_POST(NM, T, DT, ESTIMATED) &
    BIND(C, NAME="fds_cc_velocity_flux_post")
    USE CC_VELOCITY_KERNELS, ONLY: CUTFACE_VELOCITIES, CC_VELOCITY_FLUX
    USE MATH_FUNCTIONS, ONLY: EVALUATE_RAMP
    USE MESH_VARIABLES, ONLY: MESHES
    INTEGER(C_INT), VALUE :: NM, ESTIMATED
    REAL(C_DOUBLE), VALUE :: T, DT
    REAL(EB) :: GX(0:IBAR_MAX), GY(0:IBAR_MAX), GZ(0:IBAR_MAX)
    REAL(EB), POINTER, DIMENSION(:,:,:) :: UU, VV, WW, RHOP
    LOGICAL :: EST_FLAG
    INTEGER :: I
    TYPE(MESH_TYPE), POINTER :: M
    M => MESHES(NM)
    EST_FLAG = (ESTIMATED /= 0)
    IF (EST_FLAG) THEN
        UU => M%US; VV => M%VS; WW => M%WS; RHOP => M%RHOS
    ELSE
        UU => M%U; VV => M%V; WW => M%W; RHOP => M%RHO
    ENDIF
    ! Recompute gravity vectors (same as VELOCITY_FLUX_KERNEL)
    IF (.NOT.SPATIAL_GRAVITY_VARIATION) THEN
        GX(0:M%IBAR) = EVALUATE_RAMP(T,I_RAMP_GX)*GVEC(1)
        GY(0:M%IBAR) = EVALUATE_RAMP(T,I_RAMP_GY)*GVEC(2)
        GZ(0:M%IBAR) = EVALUATE_RAMP(T,I_RAMP_GZ)*GVEC(3)
    ELSE
        DO I=0,M%IBAR
            GX(I) = EVALUATE_RAMP(M%X(I),I_RAMP_GX)*GVEC(1)
            GY(I) = EVALUATE_RAMP(M%X(I),I_RAMP_GY)*GVEC(2)
            GZ(I) = EVALUATE_RAMP(M%X(I),I_RAMP_GZ)*GVEC(3)
        ENDDO
    ENDIF
    CALL CUTFACE_VELOCITIES(M, UU, VV, WW, CUTFACES=.FALSE.)
    CALL CC_VELOCITY_FLUX(M, DT, EST_FLAG, RHOP, &
        CORRECT_GRAV=.TRUE., GX=GX, GY=GY, GZ=GZ)
END SUBROUTINE C_FDS_CC_VELOCITY_FLUX_POST

RECURSIVE SUBROUTINE C_FDS_MASS_FINITE_DIFF_KERNEL(NM) BIND(C, NAME="fds_mass_finite_differences_kernel")
    USE MASS_KERNELS, ONLY: MASS_FINITE_DIFFERENCES_NEW_KERNEL
    USE MESH_VARIABLES, ONLY: MESHES
    INTEGER(C_INT), VALUE :: NM
    CALL MASS_FINITE_DIFFERENCES_NEW_KERNEL(MESHES(NM))
END SUBROUTINE C_FDS_MASS_FINITE_DIFF_KERNEL

RECURSIVE SUBROUTINE C_FDS_DENSITY_KERNEL(NM, T, DT) BIND(C, NAME="fds_density_kernel")
    USE MASS_KERNELS, ONLY: DENSITY_KERNEL
    USE MESH_VARIABLES, ONLY: MESHES
    INTEGER(C_INT), VALUE :: NM
    REAL(C_DOUBLE), VALUE :: T, DT
    CALL DENSITY_KERNEL(MESHES(NM), T, DT, NM)
END SUBROUTINE C_FDS_DENSITY_KERNEL

RECURSIVE SUBROUTINE C_FDS_DIVERGENCE_PART_1_KERNEL(NM, T, DT) BIND(C, NAME="fds_divergence_part_1_kernel")
    USE DIVG_KERNELS, ONLY: DIVERGENCE_PART_1_KERNEL
    USE MESH_VARIABLES, ONLY: MESHES
    INTEGER(C_INT), VALUE :: NM
    REAL(C_DOUBLE), VALUE :: T, DT
    CALL DIVERGENCE_PART_1_KERNEL(MESHES(NM), T, DT, NM)
END SUBROUTINE C_FDS_DIVERGENCE_PART_1_KERNEL

RECURSIVE SUBROUTINE C_FDS_VELOCITY_FLUX_KERNEL(NM, T, DT, &
    ESTIMATED) BIND(C, NAME="fds_velocity_flux_kernel")
    USE VELO_KERNELS, ONLY: VELOCITY_FLUX_KERNEL
    USE CC_VELOCITY_KERNELS, ONLY: CUTFACE_VELOCITIES, &
        CC_VELOCITY_FLUX
    USE MESH_VARIABLES, ONLY: MESHES
    INTEGER(C_INT), VALUE :: NM, ESTIMATED
    REAL(C_DOUBLE), VALUE :: T, DT
    LOGICAL :: EST_FLAG
    REAL(EB) :: GX(0:IBAR_MAX), GY(0:IBAR_MAX)
    REAL(EB) :: GZ(0:IBAR_MAX)
    REAL(EB), POINTER, DIMENSION(:,:,:) :: UU,VV,WW,RHOP
    EST_FLAG = (ESTIMATED /= 0)
    IF (CC_IBM) THEN
        IF (EST_FLAG) THEN
            UU => MESHES(NM)%US
            VV => MESHES(NM)%VS
            WW => MESHES(NM)%WS
            RHOP => MESHES(NM)%RHOS
        ELSE
            UU => MESHES(NM)%U
            VV => MESHES(NM)%V
            WW => MESHES(NM)%W
            RHOP => MESHES(NM)%RHO
        ENDIF
        CALL CUTFACE_VELOCITIES(MESHES(NM), UU, VV, WW, &
            CUTFACES=.TRUE.)
    ENDIF
    CALL VELOCITY_FLUX_KERNEL(MESHES(NM), T, DT, NM, &
        EST_FLAG, GX, GY, GZ)
    IF (CC_IBM) THEN
        CALL CUTFACE_VELOCITIES(MESHES(NM), UU, VV, WW, &
            CUTFACES=.FALSE.)
        CALL CC_VELOCITY_FLUX(MESHES(NM), DT, EST_FLAG, &
            RHOP, CORRECT_GRAV=.TRUE., &
            GX=GX, GY=GY, GZ=GZ)
    ENDIF
END SUBROUTINE C_FDS_VELOCITY_FLUX_KERNEL

RECURSIVE SUBROUTINE C_FDS_VELOCITY_FLUX_BLOCK_KERNEL(NM, T, DT, &
    ESTIMATED, K1, K2) BIND(C, NAME="fds_velocity_flux_block_kernel")
    USE VELO_KERNELS, ONLY: VELOCITY_FLUX_BLOCK_KERNEL
    USE MESH_VARIABLES, ONLY: MESHES
    INTEGER(C_INT), VALUE :: NM, ESTIMATED, K1, K2
    REAL(C_DOUBLE), VALUE :: T, DT
    CALL VELOCITY_FLUX_BLOCK_KERNEL(MESHES(NM), T, DT, NM, &
        APPLY_TO_ESTIMATED_VARIABLES=(ESTIMATED/=0), K1=K1, K2=K2)
END SUBROUTINE C_FDS_VELOCITY_FLUX_BLOCK_KERNEL

FUNCTION C_FDS_VELOCITY_FLUX_CAN_BLOCK(NM) RESULT(CAN) &
    BIND(C, NAME="fds_velocity_flux_can_block_decompose")
    USE PHYSICAL_FUNCTIONS, ONLY: COMPUTE_WIND_COMPONENTS
    INTEGER(C_INT), VALUE :: NM
    INTEGER(C_INT) :: CAN
    CAN = 1
    IF (CTRL_DIRECT_FORCE) CAN = 0
    IF (ANY(ABS(OVEC)>TWENTY_EPSILON_EB)) CAN = 0
    IF (PATCH_VELOCITY) CAN = 0
    IF (OPEN_WIND_BOUNDARY) CAN = 0
    IF (PERIODIC_TEST==7 .OR. PERIODIC_TEST==21 .OR. &
        PERIODIC_TEST==22 .OR. PERIODIC_TEST==23) CAN = 0
END FUNCTION C_FDS_VELOCITY_FLUX_CAN_BLOCK

SUBROUTINE C_FDS_VISCOSITY_BC_KERNEL(NM, ESTIMATED) &
    BIND(C, NAME="fds_viscosity_bc_kernel")
    USE VELO_KERNELS, ONLY: VISCOSITY_BC_KERNEL
    USE MESH_VARIABLES, ONLY: MESHES
    INTEGER(C_INT), VALUE :: NM, ESTIMATED
    CALL VISCOSITY_BC_KERNEL(MESHES(NM), NM, APPLY_TO_ESTIMATED_VARIABLES=(ESTIMATED/=0))
END SUBROUTINE C_FDS_VISCOSITY_BC_KERNEL

SUBROUTINE C_FDS_COMBUSTION_BC_KERNEL(NM) &
    BIND(C, NAME="fds_combustion_bc_kernel")
    USE FIRE_KERNELS, ONLY: COMBUSTION_BC_KERNEL
    USE MESH_VARIABLES, ONLY: MESHES
    INTEGER(C_INT), VALUE :: NM
    IF (N_REACTIONS>0 .OR. INIT_HRRPUV) CALL COMBUSTION_BC_KERNEL(MESHES(NM), NM)
END SUBROUTINE C_FDS_COMBUSTION_BC_KERNEL

RECURSIVE SUBROUTINE C_FDS_CONDENSATION_KERNEL(NM, DT) &
    BIND(C, NAME="fds_condensation_kernel")
    USE FIRE_KERNELS, ONLY: CONDENSATION_EVAPORATION_KERNEL
    USE MESH_VARIABLES, ONLY: MESHES
    INTEGER(C_INT), VALUE :: NM
    REAL(C_DOUBLE), VALUE :: DT
    IF (ANY(SPECIES_MIXTURE%CONDENSATION_SMIX_INDEX>0)) &
        CALL CONDENSATION_EVAPORATION_KERNEL(MESHES(NM), DT, NM)
END SUBROUTINE C_FDS_CONDENSATION_KERNEL

RECURSIVE SUBROUTINE C_FDS_PARTICLE_MOMENTUM_KERNEL(NM, DT) BIND(C, NAME="fds_particle_momentum_kernel")
    USE PART_KERNELS, ONLY: PARTICLE_MOMENTUM_TRANSFER_KERNEL
    USE MESH_VARIABLES, ONLY: MESHES
    INTEGER(C_INT), VALUE :: NM
    REAL(C_DOUBLE), VALUE :: DT
    IF (PARTICLE_DRAG) CALL PARTICLE_MOMENTUM_TRANSFER_KERNEL(MESHES(NM), DT, NM)
END SUBROUTINE C_FDS_PARTICLE_MOMENTUM_KERNEL

RECURSIVE SUBROUTINE C_FDS_PARTICLE_MOMENTUM_BLOCK_KERNEL(NM, DT, K1, K2) &
    BIND(C, NAME="fds_particle_momentum_block_kernel")
    USE PART_KERNELS, ONLY: PARTICLE_MOMENTUM_BLOCK_KERNEL
    USE MESH_VARIABLES, ONLY: MESHES
    INTEGER(C_INT), VALUE :: NM, K1, K2
    REAL(C_DOUBLE), VALUE :: DT
    IF (PARTICLE_DRAG) CALL PARTICLE_MOMENTUM_BLOCK_KERNEL(MESHES(NM), DT, K1, K2)
END SUBROUTINE C_FDS_PARTICLE_MOMENTUM_BLOCK_KERNEL

SUBROUTINE C_FDS_WALL_BC_PREPROCESSING(NM, T, DT_BC, CALL_HT_1D) &
    BIND(C, NAME="fds_wall_bc_preprocessing")
    USE WALL_ROUTINES, ONLY: WALL_BC_PREPROCESSING
    INTEGER(C_INT), VALUE :: NM, CALL_HT_1D
    REAL(C_DOUBLE), VALUE :: T, DT_BC
    LOGICAL :: HT_1D_FLAG
    HT_1D_FLAG = (CALL_HT_1D /= 0)
    CALL WALL_BC_PREPROCESSING(NM, T, DT_BC, HT_1D_FLAG)
END SUBROUTINE C_FDS_WALL_BC_PREPROCESSING

!> Thread-safe version of WALL_BC_PREPROCESSING using kernel routines.
!> Can be called from parallel kernel tasks (no POINT_TO_MESH dependency).
SUBROUTINE C_FDS_WALL_BC_PREPROCESSING_KERNEL(NM, T, DT_BC, CALL_HT_1D) &
    BIND(C, NAME="fds_wall_bc_preprocessing_kernel")
    USE WALL_KERNELS, ONLY: NEAR_SURFACE_GAS_VARIABLES_KERNEL, ASSIGN_GHOST_VALUE_KERNEL
    USE PHYSICAL_FUNCTIONS, ONLY: HEAT_TRANSFER_COEFFICIENT
    USE MESH_VARIABLES, ONLY: MESHES
    INTEGER(C_INT), VALUE :: NM, CALL_HT_1D
    REAL(C_DOUBLE), VALUE :: T, DT_BC
    LOGICAL :: HT_1D_FLAG, PRED_FLAG
    INTEGER :: IW, ITW
    TYPE(MESH_TYPE), POINTER :: M
    TYPE(WALL_TYPE), POINTER :: WC
    TYPE(THIN_WALL_TYPE), POINTER :: TW
    TYPE(SURFACE_TYPE), POINTER :: SF
    TYPE(BOUNDARY_COORD_TYPE), POINTER :: BC
    TYPE(BOUNDARY_PROP1_TYPE), POINTER :: B1

    HT_1D_FLAG = (CALL_HT_1D /= 0)
    PRED_FLAG = PREDICTOR
    M => MESHES(NM)

    DO IW=1,M%N_EXTERNAL_WALL_CELLS+M%N_INTERNAL_WALL_CELLS
       WC => M%WALL(IW)
       BC => M%BOUNDARY_COORD(WC%BC_INDEX)
       B1 => M%BOUNDARY_PROP1(WC%B1_INDEX)
       IF (IW<=M%N_EXTERNAL_WALL_CELLS) CALL ASSIGN_GHOST_VALUE_KERNEL(M,IW,BC,B1,PRED_FLAG)
       IF (WC%BOUNDARY_TYPE==NULL_BOUNDARY) CYCLE
       SF => SURFACE(WC%SURF_INDEX)
       CALL NEAR_SURFACE_GAS_VARIABLES_KERNEL(M,T,SF,BC,B1,WALL_INDEX=IW)
       IF (HT_1D_FLAG .AND. SF%THERMAL_BC_INDEX==THERMALLY_THICK) &
          B1%HEAT_TRANS_COEF = HEAT_TRANSFER_COEFFICIENT(M,T,B1%TMP_G-B1%TMP_F,SF,WALL_INDEX_IN=IW)
    ENDDO

    IF (M%N_THIN_WALL_CELLS>0 .AND. HT_1D_FLAG) THEN
       DO ITW=1,M%N_THIN_WALL_CELLS
          TW => M%THIN_WALL(ITW)
          BC => M%BOUNDARY_COORD(TW%BC_INDEX)
          B1 => M%BOUNDARY_PROP1(TW%B1_INDEX)
          SF => SURFACE(TW%SURF_INDEX)
          CALL NEAR_SURFACE_GAS_VARIABLES_KERNEL(M,T,SF,BC,B1,TW=TW,THIN_WALL_INDEX=ITW)
          IF (TW%WALL_INDEX_M>0) THEN
             B1%HEAT_TRANS_COEF = HEAT_TRANSFER_COEFFICIENT(M,T,B1%TMP_G-B1%TMP_F,SF,WALL_INDEX_IN=TW%WALL_INDEX_M)
          ELSEIF (TW%WALL_INDEX_P>0) THEN
             B1%HEAT_TRANS_COEF = HEAT_TRANSFER_COEFFICIENT(M,T,B1%TMP_G-B1%TMP_F,SF,WALL_INDEX_IN=TW%WALL_INDEX_P)
          ELSE
             B1%HEAT_TRANS_COEF = 0._EB
          ENDIF
       ENDDO
    ENDIF
END SUBROUTINE C_FDS_WALL_BC_PREPROCESSING_KERNEL

RECURSIVE SUBROUTINE C_FDS_WALL_BC_PROCESS_CELLS_KERNEL(NM, T, DT, DT_BC, CALL_HT_1D) &
    BIND(C, NAME="fds_wall_bc_process_cells_kernel")
    USE WALL_ROUTINES, ONLY: WALL_BC_PROCESS_CELLS_KERNEL
    USE MESH_VARIABLES, ONLY: MESHES
    INTEGER(C_INT), VALUE :: NM, CALL_HT_1D
    REAL(C_DOUBLE), VALUE :: T, DT, DT_BC
    LOGICAL :: HT_1D_FLAG
    HT_1D_FLAG = (CALL_HT_1D /= 0)
    CALL WALL_BC_PROCESS_CELLS_KERNEL(MESHES(NM), NM, PREDICTOR, T, DT, DT_BC, HT_1D_FLAG)
END SUBROUTINE C_FDS_WALL_BC_PROCESS_CELLS_KERNEL

RECURSIVE SUBROUTINE C_FDS_WALL_BC_PROCESS_CELLS_BLOCK_KERNEL(NM, T, DT, DT_BC, CALL_HT_1D, K1, K2) &
    BIND(C, NAME="fds_wall_bc_process_cells_block_kernel")
    USE WALL_ROUTINES, ONLY: WALL_BC_PROCESS_CELLS_BLOCK_KERNEL
    USE MESH_VARIABLES, ONLY: MESHES
    USE MESH_POINTERS
    INTEGER(C_INT), VALUE :: NM, CALL_HT_1D, K1, K2
    REAL(C_DOUBLE), VALUE :: T, DT, DT_BC
    LOGICAL :: HT_1D_FLAG
    HT_1D_FLAG = (CALL_HT_1D /= 0)
    CALL POINT_TO_MESH(NM)
    CALL WALL_BC_PROCESS_CELLS_BLOCK_KERNEL(MESHES(NM), NM, PREDICTOR, T, DT, DT_BC, HT_1D_FLAG, K1, K2)
END SUBROUTINE C_FDS_WALL_BC_PROCESS_CELLS_BLOCK_KERNEL

FUNCTION C_FDS_WALL_BC_CAN_BLOCK_DECOMPOSE() RESULT(CAN) &
    BIND(C, NAME="fds_wall_bc_can_block_decompose")
    INTEGER(C_INT) :: CAN
    CAN = 1
END FUNCTION C_FDS_WALL_BC_CAN_BLOCK_DECOMPOSE

SUBROUTINE C_FDS_WALL_BC_FINALIZE(NM, T, DT_BC, CALL_HT_1D) &
    BIND(C, NAME="fds_wall_bc_finalize")
    USE WALL_ROUTINES, ONLY: WALL_BC_FINALIZE
    INTEGER(C_INT), VALUE :: NM, CALL_HT_1D
    REAL(C_DOUBLE), VALUE :: T, DT_BC
    LOGICAL :: HT_1D_FLAG
    HT_1D_FLAG = (CALL_HT_1D /= 0)
    CALL WALL_BC_FINALIZE(NM, T, DT_BC, HT_1D_FLAG)
END SUBROUTINE C_FDS_WALL_BC_FINALIZE

SUBROUTINE C_FDS_CC_VELOCITY_BC(T, NM, ESTIMATED) &
    BIND(C, NAME="fds_cc_velocity_bc")
    REAL(C_DOUBLE), VALUE :: T
    INTEGER(C_INT), VALUE :: NM, ESTIMATED
    IF (CC_IBM) CALL CC_VELOCITY_BC(T, NM, &
        APPLY_TO_ESTIMATED_VARIABLES=(ESTIMATED/=0), &
        DO_IBEDGES=.TRUE.)
END SUBROUTINE C_FDS_CC_VELOCITY_BC

SUBROUTINE C_FDS_CC_PROJECT_VELOCITY(NM, DT, STORE_FLAG) &
    BIND(C, NAME="fds_cc_project_velocity")
    USE MESH_POINTERS
    INTEGER(C_INT), VALUE :: NM, STORE_FLAG
    REAL(C_DOUBLE), VALUE :: DT
    IF (CC_IBM) THEN
        CALL POINT_TO_MESH(NM)
        CALL CC_PROJECT_VELOCITY(NM, DT, &
            STORE_FLG=(STORE_FLAG/=0))
    ENDIF
END SUBROUTINE C_FDS_CC_PROJECT_VELOCITY

!> Apply WALL_VELOCITY_NO_GRADH for sparse pressure solvers.
!> Must be called after CC_PROJECT_VELOCITY in VELOCITY_PREDICTOR/CORRECTOR.
!> Only active for GLMAT/UGLMAT/ULMAT solvers; no-op for FFT.
SUBROUTINE C_FDS_WALL_VELOCITY_NO_GRADH(NM, DT, STORE_FLAG) &
    BIND(C, NAME="fds_wall_velocity_no_gradh")
    USE MESH_POINTERS
    INTEGER(C_INT), VALUE :: NM, STORE_FLAG
    REAL(C_DOUBLE), VALUE :: DT
    CALL POINT_TO_MESH(NM)
    SELECT CASE(PRES_FLAG)
        CASE(GLMAT_FLAG,UGLMAT_FLAG,ULMAT_FLAG)
            CALL WALL_VELOCITY_NO_GRADH(DT, (STORE_FLAG/=0))
    END SELECT
END SUBROUTINE C_FDS_WALL_VELOCITY_NO_GRADH

!==============================================================================
! Output subroutines
!==============================================================================

SUBROUTINE C_FDS_UPDATE_GLOBAL_OUTPUTS(T, DT, NM) BIND(C, NAME="fds_update_global_outputs")
    REAL(C_DOUBLE), VALUE :: T, DT
    INTEGER(C_INT), VALUE :: NM
    CALL UPDATE_GLOBAL_OUTPUTS(T, DT, NM)
END SUBROUTINE C_FDS_UPDATE_GLOBAL_OUTPUTS

SUBROUTINE C_FDS_DUMP_MESH_OUTPUTS(T, DT, NM) BIND(C, NAME="fds_dump_mesh_outputs")
    REAL(C_DOUBLE), VALUE :: T, DT
    INTEGER(C_INT), VALUE :: NM
    CALL DUMP_MESH_OUTPUTS(T, DT, NM)
END SUBROUTINE C_FDS_DUMP_MESH_OUTPUTS

SUBROUTINE C_FDS_EXCHANGE_GLOBAL_OUTPUTS(T, DT) BIND(C, NAME="fds_exchange_global_outputs")
    REAL(C_DOUBLE), VALUE :: T, DT
    CALL EXCHANGE_GLOBAL_OUTPUTS_DRIVER(T, DT)
END SUBROUTINE C_FDS_EXCHANGE_GLOBAL_OUTPUTS

SUBROUTINE C_FDS_UPDATE_CONTROLS(T, DT) BIND(C, NAME="fds_update_controls")
    REAL(C_DOUBLE), VALUE :: T, DT
    LOGICAL :: CTRL_STOP_LOCAL
    CTRL_STOP_LOCAL = .FALSE.
    CALL UPDATE_CONTROLS(T, DT, CTRL_STOP_LOCAL, .FALSE.)
    IF (CTRL_STOP_LOCAL) STOP_STATUS = CTRL_STOP
END SUBROUTINE C_FDS_UPDATE_CONTROLS

SUBROUTINE C_FDS_DUMP_GLOBAL_OUTPUTS(T, DT) BIND(C, NAME="fds_dump_global_outputs")
    REAL(C_DOUBLE), VALUE :: T, DT
    CALL DUMP_GLOBAL_OUTPUTS_DRIVER(T, DT)
END SUBROUTINE C_FDS_DUMP_GLOBAL_OUTPUTS

SUBROUTINE C_FDS_WRITE_STRINGS(T, DT) BIND(C, NAME="fds_write_strings")
    REAL(C_DOUBLE), VALUE :: T, DT
    CALL WRITE_STRINGS_DRIVER(T, DT)
END SUBROUTINE C_FDS_WRITE_STRINGS

SUBROUTINE C_FDS_WRITE_DIAGNOSTICS(T, DT) BIND(C, NAME="fds_write_diagnostics")
    REAL(C_DOUBLE), VALUE :: T, DT
    CALL WRITE_DIAGNOSTICS_DRIVER(T, DT)
END SUBROUTINE C_FDS_WRITE_DIAGNOSTICS

SUBROUTINE C_FDS_FLUSH_OUTPUT_FILES() BIND(C, NAME="fds_flush_output_files")
    ! Flush all open Fortran I/O units to ensure outputs are written to disk
    ! This is needed before timeout kills the process in case of graph termination hang
    CALL FLUSH()
END SUBROUTINE C_FDS_FLUSH_OUTPUT_FILES

SUBROUTINE C_FDS_SET_DIAGNOSTICS(ICYC_IN, T_IN, DT_IN) BIND(C, NAME="fds_set_diagnostics")
    REAL(C_DOUBLE), VALUE :: T_IN, DT_IN
    INTEGER(C_INT), VALUE :: ICYC_IN
    CALL SET_DIAGNOSTICS_DRIVER(ICYC_IN, T_IN, DT_IN)
END SUBROUTINE C_FDS_SET_DIAGNOSTICS

!==============================================================================
! Barrier / exchange subroutines (called from state managers)
!==============================================================================

SUBROUTINE C_FDS_MESH_EXCHANGE(CODE) BIND(C, NAME="fds_mesh_exchange")
    INTEGER(C_INT), VALUE :: CODE
    CALL MESH_EXCHANGE_DRIVER(CODE, 0._EB, 0._EB)
END SUBROUTINE C_FDS_MESH_EXCHANGE

SUBROUTINE C_FDS_POST_RECEIVES(CODE) BIND(C, NAME="fds_post_receives")
    INTEGER(C_INT), VALUE :: CODE
    CALL POST_RECEIVES_DRIVER(CODE, 0._EB, 0._EB)
END SUBROUTINE C_FDS_POST_RECEIVES

SUBROUTINE C_FDS_PRESSURE_ITERATION(T, DT) BIND(C, NAME="fds_pressure_iteration")
    REAL(C_DOUBLE), VALUE :: T, DT
    CALL PRESSURE_ITERATION_SCHEME_DRIVER(T, DT)
END SUBROUTINE C_FDS_PRESSURE_ITERATION

! --- Pressure iteration kernel routines (for sub-graph parallelization) ---

SUBROUTINE C_FDS_NO_FLUX_KERNEL(NM, DT) BIND(C, NAME="fds_no_flux_kernel")
    USE VELO_KERNELS, ONLY: NO_FLUX_KERNEL
    INTEGER(C_INT), VALUE :: NM
    REAL(C_DOUBLE), VALUE :: DT
    CALL NO_FLUX_KERNEL(MESHES(NM), DT)
END SUBROUTINE C_FDS_NO_FLUX_KERNEL

SUBROUTINE C_FDS_MATCH_VELOCITY_FLUX_KERNEL(NM) BIND(C, NAME="fds_match_velocity_flux_kernel")
    USE VELO_KERNELS, ONLY: MATCH_VELOCITY_FLUX_KERNEL
    INTEGER(C_INT), VALUE :: NM
    CALL MATCH_VELOCITY_FLUX_KERNEL(MESHES(NM), NM)
END SUBROUTINE C_FDS_MATCH_VELOCITY_FLUX_KERNEL

SUBROUTINE C_FDS_PRESSURE_SOLVER_COMPUTE_RHS_KERNEL(NM, T, DT) &
    BIND(C, NAME="fds_pressure_solver_compute_rhs_kernel")
    USE PRES_KERNELS, ONLY: PK_COMPUTE_RHS => PRESSURE_SOLVER_COMPUTE_RHS
    INTEGER(C_INT), VALUE :: NM
    REAL(C_DOUBLE), VALUE :: T, DT
    CALL PK_COMPUTE_RHS(MESHES(NM), T, DT, NM)
END SUBROUTINE C_FDS_PRESSURE_SOLVER_COMPUTE_RHS_KERNEL

SUBROUTINE C_FDS_PRESSURE_SOLVER_FFT_KERNEL(NM) BIND(C, NAME="fds_pressure_solver_fft_kernel")
    USE PRES_KERNELS, ONLY: PK_FFT => PRESSURE_SOLVER_FFT
    INTEGER(C_INT), VALUE :: NM
    CALL PK_FFT(MESHES(NM), NM)
END SUBROUTINE C_FDS_PRESSURE_SOLVER_FFT_KERNEL

SUBROUTINE C_FDS_PRESSURE_CHECK_RESIDUALS_KERNEL(NM) &
    BIND(C, NAME="fds_pressure_check_residuals_kernel")
    USE PRES_KERNELS, ONLY: PK_CHECK_RESIDUALS => PRESSURE_SOLVER_CHECK_RESIDUALS
    INTEGER(C_INT), VALUE :: NM
    CALL PK_CHECK_RESIDUALS(MESHES(NM), NM)
END SUBROUTINE C_FDS_PRESSURE_CHECK_RESIDUALS_KERNEL

SUBROUTINE C_FDS_COMPUTE_VELOCITY_ERROR_KERNEL(NM, DT) &
    BIND(C, NAME="fds_compute_velocity_error_kernel")
    USE PRES_KERNELS, ONLY: COMPUTE_VELOCITY_ERROR_KERNEL
    INTEGER(C_INT), VALUE :: NM
    REAL(C_DOUBLE), VALUE :: DT
    CALL COMPUTE_VELOCITY_ERROR_KERNEL(MESHES(NM), DT, NM)
END SUBROUTINE C_FDS_COMPUTE_VELOCITY_ERROR_KERNEL

SUBROUTINE C_FDS_ULMAT_SOLVER_KERNEL(NM, T, DT) &
    BIND(C, NAME="fds_ulmat_solver_kernel")
    USE LOCMAT_SOLVER, ONLY: ULMAT_SOLVER_KERNEL
    INTEGER(C_INT), VALUE :: NM
    REAL(C_DOUBLE), VALUE :: T, DT
    CALL ULMAT_SOLVER_KERNEL(MESHES(NM), NM, T, DT)
END SUBROUTINE C_FDS_ULMAT_SOLVER_KERNEL

SUBROUTINE C_FDS_ULMAT_CHECK_RESIDUALS_KERNEL(NM) &
    BIND(C, NAME="fds_ulmat_check_residuals_kernel")
    USE PRES_KERNELS, ONLY: PRESSURE_SOLVER_CHECK_RESIDUALS_U_KERNEL
    INTEGER(C_INT), VALUE :: NM
    CALL PRESSURE_SOLVER_CHECK_RESIDUALS_U_KERNEL(MESHES(NM), NM)
END SUBROUTINE C_FDS_ULMAT_CHECK_RESIDUALS_KERNEL

SUBROUTINE C_FDS_INIT_DIV_INTEGRALS() BIND(C, NAME="fds_initialize_divergence_integrals")
    CALL INITIALIZE_DIVERGENCE_INTEGRALS_DRIVER()
END SUBROUTINE C_FDS_INIT_DIV_INTEGRALS

SUBROUTINE C_FDS_EXCHANGE_DIV_INFO() BIND(C, NAME="fds_exchange_divergence_info")
    CALL EXCHANGE_DIVERGENCE_INFO_DRIVER(0._EB, 0._EB)
END SUBROUTINE C_FDS_EXCHANGE_DIV_INFO

SUBROUTINE C_FDS_ACCUMULATE_RAD_SUMS(RAD_Q_PARTIAL, KFST4_PARTIAL) &
    BIND(C, NAME="fds_accumulate_rad_sums")
    REAL(C_DOUBLE), VALUE :: RAD_Q_PARTIAL, KFST4_PARTIAL
    RAD_Q_SUM = RAD_Q_SUM + RAD_Q_PARTIAL
    KFST4_SUM = KFST4_SUM + KFST4_PARTIAL
END SUBROUTINE C_FDS_ACCUMULATE_RAD_SUMS

SUBROUTINE C_FDS_CREATE_REMOVE_OBST(T, DT) BIND(C, NAME="fds_create_or_remove_obstructions")
    REAL(C_DOUBLE), VALUE :: T, DT
    CALL CREATE_OR_REMOVE_OBSTRUCTIONS_DRIVER(T, DT)
END SUBROUTINE C_FDS_CREATE_REMOVE_OBST

SUBROUTINE C_FDS_GLOBAL_MATRIX_REASSIGN(FORCE) BIND(C, NAME="fds_global_matrix_reassign")
    INTEGER(C_INT), VALUE :: FORCE
    CALL GLOBAL_MATRIX_REASSIGN_DRIVER(FORCE_REASSIGN=(FORCE/=0), T=0._EB, DT=0._EB)
END SUBROUTINE C_FDS_GLOBAL_MATRIX_REASSIGN

SUBROUTINE C_FDS_RTE_CORRECTION() BIND(C, NAME="fds_rte_source_correction")
    IF (RTE_SOURCE_CORRECTION) CALL CALCULATE_RTE_SOURCE_CORRECTION_FACTOR_DRIVER()
END SUBROUTINE C_FDS_RTE_CORRECTION

SUBROUTINE C_FDS_STOP_CHECK(END_CODE, T, DT) BIND(C, NAME="fds_stop_check")
    INTEGER(C_INT), VALUE :: END_CODE
    REAL(C_DOUBLE), VALUE :: T, DT
    CALL STOP_CHECK_DRIVER(END_CODE, T, DT)
END SUBROUTINE C_FDS_STOP_CHECK

FUNCTION C_FDS_GET_STOP_STATUS() RESULT(STATUS_OUT) BIND(C, NAME="fds_get_stop_status")
    INTEGER(C_INT) :: STATUS_OUT
    STATUS_OUT = STOP_STATUS
END FUNCTION C_FDS_GET_STOP_STATUS

SUBROUTINE C_FDS_SYNTHETIC_TURBULENCE(DT, T, NM) BIND(C, NAME="fds_synthetic_turbulence")
    REAL(C_DOUBLE), VALUE :: DT, T
    INTEGER(C_INT), VALUE :: NM
    IF (SYNTHETIC_EDDY_METHOD) CALL SYNTHETIC_TURBULENCE(DT, T, NM)
END SUBROUTINE C_FDS_SYNTHETIC_TURBULENCE

SUBROUTINE C_FDS_HVAC_CALC(T, DT, FIRST) BIND(C, NAME="fds_hvac_calc")
    REAL(C_DOUBLE), VALUE :: T, DT
    INTEGER(C_INT), VALUE :: FIRST
    IF (HVAC_SOLVE) CALL HVAC_CALC(T, DT, (FIRST/=0))
END SUBROUTINE C_FDS_HVAC_CALC

SUBROUTINE C_FDS_SET_BAROCLINIC(NM) BIND(C, NAME="fds_set_baroclinic_false")
    INTEGER(C_INT), VALUE :: NM
    IF (.NOT.SOLID_PHASE_ONLY .AND. .NOT.FREEZE_VELOCITY) MESHES(NM)%BAROCLINIC_TERMS_ATTACHED = .FALSE.
END SUBROUTINE C_FDS_SET_BAROCLINIC

!==============================================================================
! WALL_BC helper functions
!==============================================================================

FUNCTION C_FDS_COMPUTE_WALL_BC_DT_BC(T) RESULT(DT_BC_OUT) BIND(C, NAME="fds_compute_wall_bc_dt_bc")
    USE MESH_VARIABLES, ONLY: MESHES
    REAL(C_DOUBLE), VALUE :: T
    REAL(C_DOUBLE) :: DT_BC_OUT
    ! Compute DT_BC same way as WALL_BC does (wall.f90:96)
    ! BC_CLOCK is mesh-specific, use first mesh (all meshes have same BC_CLOCK value)
    DT_BC_OUT = T - MESHES(1)%BC_CLOCK
END FUNCTION C_FDS_COMPUTE_WALL_BC_DT_BC

SUBROUTINE C_FDS_INCREMENT_WALL_COUNTER() BIND(C, NAME="fds_increment_wall_counter")
    USE GLOBAL_CONSTANTS, ONLY: WALL_COUNTER
    ! Increment WALL_COUNTER BEFORE checking CALL_HT_1D (main.f90:868)
    WALL_COUNTER = WALL_COUNTER + 1
END SUBROUTINE C_FDS_INCREMENT_WALL_COUNTER

FUNCTION C_FDS_CHECK_CALL_HT_1D() RESULT(CALL_HT_1D_OUT) BIND(C, NAME="fds_check_call_ht_1d")
    USE GLOBAL_CONSTANTS, ONLY: WALL_COUNTER, WALL_INCREMENT
    INTEGER(C_INT) :: CALL_HT_1D_OUT
    ! Check if we should call 1-D heat transfer (wall.f90:95-98)
    IF (.NOT.INITIALIZATION_PHASE .AND. CORRECTOR) THEN
        IF (WALL_COUNTER == WALL_INCREMENT) THEN
            CALL_HT_1D_OUT = 1
        ELSE
            CALL_HT_1D_OUT = 0
        ENDIF
    ELSE
        CALL_HT_1D_OUT = 0
    ENDIF
END FUNCTION C_FDS_CHECK_CALL_HT_1D

SUBROUTINE C_FDS_RESET_WALL_COUNTER() BIND(C, NAME="fds_reset_wall_counter")
    USE GLOBAL_CONSTANTS, ONLY: WALL_COUNTER, WALL_INCREMENT
    ! Reset WALL_COUNTER AFTER WALL_BC loop (main.f90:872)
    IF (WALL_COUNTER == WALL_INCREMENT) WALL_COUNTER = 0
END SUBROUTINE C_FDS_RESET_WALL_COUNTER

SUBROUTINE C_FDS_UPDATE_BC_CLOCK(T) BIND(C, NAME="fds_update_bc_clock")
    USE MESH_VARIABLES, ONLY: MESHES
    REAL(C_DOUBLE), VALUE :: T
    INTEGER :: NM
    ! Update BC_CLOCK and HT_3D_SWEEP_DIRECTION (wall.f90:97-100)
    ! These are mesh-specific variables, update for all local meshes
    DO NM = LOWER_MESH_INDEX, UPPER_MESH_INDEX
        MESHES(NM)%BC_CLOCK = T
        MESHES(NM)%HT_3D_SWEEP_DIRECTION = MESHES(NM)%HT_3D_SWEEP_DIRECTION + 1
        IF (MESHES(NM)%HT_3D_SWEEP_DIRECTION > 3) MESHES(NM)%HT_3D_SWEEP_DIRECTION = 1
    ENDDO
END SUBROUTINE C_FDS_UPDATE_BC_CLOCK

!==============================================================================
! Pressure iteration sub-graph helper functions
!==============================================================================

!> Initialize pressure iteration state at start of each time step's pressure loop.
SUBROUTINE C_FDS_PRESSURE_ITERATION_INIT() BIND(C, NAME="fds_pressure_iteration_init")
    PRESSURE_ITERATIONS = 0
    IF (BAROCLINIC) THEN
       ITERATE_BAROCLINIC_TERM = .TRUE.
    ELSE
       ITERATE_BAROCLINIC_TERM = .FALSE.
    ENDIF
END SUBROUTINE C_FDS_PRESSURE_ITERATION_INIT

!> Increment PRESSURE_ITERATIONS and TOTAL_PRESSURE_ITERATIONS counters.
SUBROUTINE C_FDS_PRESSURE_ITERATION_INCREMENT() BIND(C, NAME="fds_pressure_iteration_increment")
    PRESSURE_ITERATIONS = PRESSURE_ITERATIONS + 1
    TOTAL_PRESSURE_ITERATIONS = TOTAL_PRESSURE_ITERATIONS + 1
END SUBROUTINE C_FDS_PRESSURE_ITERATION_INCREMENT

!> Return current PRESSURE_ITERATIONS count.
FUNCTION C_FDS_GET_PRESSURE_ITERATIONS() RESULT(ITERS) BIND(C, NAME="fds_get_pressure_iterations")
    INTEGER(C_INT) :: ITERS
    ITERS = PRESSURE_ITERATIONS
END FUNCTION C_FDS_GET_PRESSURE_ITERATIONS

!> Call BAROCLINIC_CORRECTION for a single mesh (no-op if not applicable).
SUBROUTINE C_FDS_BAROCLINIC_CORRECTION(T, NM) BIND(C, NAME="fds_baroclinic_correction")
    REAL(C_DOUBLE), VALUE :: T
    INTEGER(C_INT), VALUE :: NM
    IF (.NOT.SOLID_PHASE_ONLY .AND. .NOT.FREEZE_VELOCITY .AND. BAROCLINIC) &
        CALL BAROCLINIC_CORRECTION(T, NM)
END SUBROUTINE C_FDS_BAROCLINIC_CORRECTION

!> Zero WALL_WORK1 for a single mesh (called on first pressure iteration).
SUBROUTINE C_FDS_PRESSURE_ITERATION_ZERO_WALL_WORK1(NM) &
    BIND(C, NAME="fds_pressure_iteration_zero_wall_work1")
    INTEGER(C_INT), VALUE :: NM
    MESHES(NM)%WALL_WORK1 = 0._EB
END SUBROUTINE C_FDS_PRESSURE_ITERATION_ZERO_WALL_WORK1

!> MPI error reduction and velocity error file output for pressure convergence check.
SUBROUTINE C_FDS_PRESSURE_ITERATION_CHECK_CONVERGENCE(T, DT) &
    BIND(C, NAME="fds_pressure_iteration_check_convergence")
    USE COMP_FUNCTIONS, ONLY: CURRENT_TIME
    REAL(C_DOUBLE), VALUE :: T, DT
    REAL(EB) :: TNOW
    INTEGER :: NM_MAX_V, NM_MAX_P, IERR

    IF (N_MPI_PROCESSES>1) THEN
       TNOW = CURRENT_TIME()
       REAL_BUFFER_10(  1,LOWER_MESH_INDEX:UPPER_MESH_INDEX) = &
           VELOCITY_ERROR_MAX(LOWER_MESH_INDEX:UPPER_MESH_INDEX)
       REAL_BUFFER_10(  2,LOWER_MESH_INDEX:UPPER_MESH_INDEX) = &
           PRESSURE_ERROR_MAX(LOWER_MESH_INDEX:UPPER_MESH_INDEX)
       REAL_BUFFER_10(3:5,LOWER_MESH_INDEX:UPPER_MESH_INDEX) = &
           VELOCITY_ERROR_MAX_LOC(1:3,LOWER_MESH_INDEX:UPPER_MESH_INDEX)
       REAL_BUFFER_10(6:8,LOWER_MESH_INDEX:UPPER_MESH_INDEX) = &
           PRESSURE_ERROR_MAX_LOC(1:3,LOWER_MESH_INDEX:UPPER_MESH_INDEX)
       CALL MPI_ALLGATHERV(MPI_IN_PLACE,0,MPI_DATATYPE_NULL, &
                           REAL_BUFFER_10(1:10,1:NMESHES), &
                           COUNTS_10,DISPLS_10,MPI_DOUBLE_PRECISION, &
                           MPI_COMM_WORLD,IERR)
       VELOCITY_ERROR_MAX(:)         =     REAL_BUFFER_10(1,:)
       PRESSURE_ERROR_MAX(:)         =     REAL_BUFFER_10(2,:)
       VELOCITY_ERROR_MAX_LOC(1:3,:) = INT(REAL_BUFFER_10(3:5,:))
       PRESSURE_ERROR_MAX_LOC(1:3,:) = INT(REAL_BUFFER_10(6:8,:))
       T_USED(11)=T_USED(11) + CURRENT_TIME() - TNOW
    ENDIF

    IF (MY_RANK==0 .AND. VELOCITY_ERROR_FILE) THEN
       NM_MAX_V = MAXLOC(VELOCITY_ERROR_MAX,DIM=1)
       NM_MAX_P = MAXLOC(PRESSURE_ERROR_MAX,DIM=1)
       WRITE(LU_VELOCITY_ERROR, &
           '(E16.8,A,7(I7,A),E16.8,A,4(I7,A),E16.8)') &
           T,',',ICYC,',',PRESSURE_ITERATIONS,',', &
           TOTAL_PRESSURE_ITERATIONS,',', &
           NM_MAX_V,',',VELOCITY_ERROR_MAX_LOC(1,NM_MAX_V),',', &
           VELOCITY_ERROR_MAX_LOC(2,NM_MAX_V),',', &
           VELOCITY_ERROR_MAX_LOC(3,NM_MAX_V),',', &
           MAXVAL(VELOCITY_ERROR_MAX),',', &
           NM_MAX_P,',',PRESSURE_ERROR_MAX_LOC(1,NM_MAX_P),',', &
           PRESSURE_ERROR_MAX_LOC(2,NM_MAX_P),',', &
           PRESSURE_ERROR_MAX_LOC(3,NM_MAX_P),',', &
           MAXVAL(PRESSURE_ERROR_MAX)
    ENDIF

    IF (MAXVAL(PRESSURE_ERROR_MAX)<PRESSURE_TOLERANCE) &
        ITERATE_BAROCLINIC_TERM = .FALSE.
END SUBROUTINE C_FDS_PRESSURE_ITERATION_CHECK_CONVERGENCE

!> Check whether the pressure iteration loop should exit.
!> Returns 1 if converged (or max iterations reached or suspended).
FUNCTION C_FDS_PRESSURE_ITERATION_CONVERGED() RESULT(FLAG) &
    BIND(C, NAME="fds_pressure_iteration_converged")
    INTEGER(C_INT) :: FLAG
    REAL(EB), SAVE :: VELOCITY_ERROR_MAX_OLD = 0._EB
    REAL(EB), SAVE :: PRESSURE_ERROR_MAX_OLD = 0._EB

    FLAG = 0

    ! Max iterations check
    IF (PREDICTOR .AND. &
        PRESSURE_ITERATIONS>=MAX_PREDICTOR_PRESSURE_ITERATIONS) THEN
        FLAG = 1; RETURN
    ENDIF
    IF (CORRECTOR .AND. &
        PRESSURE_ITERATIONS>=MAX_PRESSURE_ITERATIONS) THEN
        FLAG = 1; RETURN
    ENDIF

    ! Tolerance check
    IF (MAXVAL(PRESSURE_ERROR_MAX)<PRESSURE_TOLERANCE .AND. &
        MAXVAL(VELOCITY_ERROR_MAX)<VELOCITY_TOLERANCE) THEN
        FLAG = 1; RETURN
    ENDIF

    ! Suspend check (stagnating convergence)
    IF (SUSPEND_PRESSURE_ITERATIONS .AND. ICYC>10) THEN
        IF (PRESSURE_ITERATIONS>3 .AND. &
            MAXVAL(VELOCITY_ERROR_MAX) > &
                ITERATION_SUSPEND_FACTOR*VELOCITY_ERROR_MAX_OLD .AND. &
            MAXVAL(PRESSURE_ERROR_MAX) > &
                ITERATION_SUSPEND_FACTOR*PRESSURE_ERROR_MAX_OLD) THEN
            FLAG = 1; RETURN
        ENDIF
        VELOCITY_ERROR_MAX_OLD = MAXVAL(VELOCITY_ERROR_MAX)
        PRESSURE_ERROR_MAX_OLD = MAXVAL(PRESSURE_ERROR_MAX)
    ENDIF
END FUNCTION C_FDS_PRESSURE_ITERATION_CONVERGED

!> Return whether ITERATE_BAROCLINIC_TERM is true (Phase 1 should run).
FUNCTION C_FDS_PRESSURE_ITERATION_NEEDS_BAROCLINIC() RESULT(FLAG) &
    BIND(C, NAME="fds_pressure_iteration_needs_baroclinic")
    INTEGER(C_INT) :: FLAG
    IF (ITERATE_BAROCLINIC_TERM) THEN
        FLAG = 1
    ELSE
        FLAG = 0
    ENDIF
END FUNCTION C_FDS_PRESSURE_ITERATION_NEEDS_BAROCLINIC

END MODULE FDS_C_INTERFACE
