!> \brief Pure computation kernels extracted from DIVG module.
!> These routines take TYPE(MESH_TYPE) as an argument instead of relying on
!> MESH_POINTERS / POINT_TO_MESH, decoupling computation from global state.

MODULE DIVG_KERNELS

USE PRECISION_PARAMETERS
USE GLOBAL_CONSTANTS
USE MESH_VARIABLES, ONLY: MESH_TYPE
USE TYPES, ONLY: WALL_TYPE,BOUNDARY_COORD_TYPE,BOUNDARY_PROP1_TYPE,EXTERNAL_WALL_TYPE,CFACE_TYPE, &
                 VENTS_TYPE,SURFACE_TYPE,SURFACE,SPECIES_MIXTURE_TYPE,SPECIES_MIXTURE, &
                 P_ZONE_TYPE,P_ZONE,RAMPS_TYPE,RAMPS

IMPLICIT NONE (TYPE,EXTERNAL)
PRIVATE

PUBLIC DIVERGENCE_PART_1_KERNEL,DIVERGENCE_PART_1_ADD_QR_KERNEL,DIVERGENCE_PART_2_KERNEL,CHECK_DIVERGENCE_KERNEL
PUBLIC DIVERGENCE_PART_2_PREPROCESSING,DIVERGENCE_PART_2_BLOCK_KERNEL

CONTAINS

!> \brief Compute contributions to the divergence term
!> \param M Mesh data structure
!> \param T Time (s)
!> \param DT Time step (s)
!> \param NM Mesh number

SUBROUTINE DIVERGENCE_PART_1_KERNEL(M,T,DT,NM,SKIP_QR)

USE MATH_FUNCTIONS, ONLY: INTERPOLATE1D_UNIFORM
USE PHYSICAL_FUNCTIONS, ONLY: GET_CONDUCTIVITY,GET_SPECIFIC_HEAT,GET_SENSIBLE_ENTHALPY_Z,GET_SENSIBLE_ENTHALPY,&
                              GET_VISCOSITY,GET_MOLECULAR_WEIGHT
USE TURB_KERNELS, ONLY: TENSOR_DIFFUSIVITY_MODEL_KERNEL
USE MANUFACTURED_SOLUTIONS, ONLY: DIFF_MMS,UF_MMS,WF_MMS,VD2D_MMS_Z_SRC
USE COMPLEX_GEOMETRY, ONLY : CC_CGSC, CC_UNKZ, CC_SOLID, CC_CUTCFE
USE CC_PRESSURE_KERNELS, ONLY : ADD_CUTCELL_PSUM, &
   ADD_LINKEDCELL_PSUM
USE CC_VELOCITY_KERNELS, ONLY : CC_VELOCITY_FLUX
USE CC_VELOCITY, ONLY : CFACE_PREDICT_NORMAL_VELOCITY
USE CC_DIVERGENCE_KERNELS, ONLY : SET_EXIMDIFFLX_3D, &
                       SET_EXIMRHOHSLIM_3D,SET_EXIMRHOZZLIM_3D
USE CC_DIVERGENCE, ONLY : CC_DIVERGENCE_PART_1

TYPE(MESH_TYPE), INTENT(INOUT), TARGET :: M
INTEGER, INTENT(IN) :: NM
REAL(EB), INTENT(IN) :: T,DT
LOGICAL, INTENT(IN), OPTIONAL :: SKIP_QR
LOGICAL :: SKIP_QR_FLAG
REAL(EB), POINTER, DIMENSION(:,:,:) :: KDTDX,KDTDY,KDTDZ,DP,KP,CP, &
          RHO_D,H_RHO_D_DZDX,H_RHO_D_DZDY,H_RHO_D_DZDZ,RTRM, &
          U_DOT_DEL_RHO_H_S,U_DOT_DEL_RHO_Z,RHO_D_TURB,R_H_G
REAL(EB), POINTER, DIMENSION(:,:,:,:) :: RHO_D_DZDX,RHO_D_DZDY,RHO_D_DZDZ
REAL(EB), POINTER, DIMENSION(:,:) :: PBAR_P
REAL(EB), POINTER, DIMENSION(:,:,:) :: UU,VV,WW,RHOP
REAL(EB), POINTER, DIMENSION(:,:,:,:) :: ZZP
REAL(EB) :: DELKDELT,VC,VC1,DTDX,DTDY,DTDZ,DZDX,DZDY,DZDZ,TMP_G,DIV_DIFF_HEAT_FLUX,H_S,XHAT,ZHAT,TT,Q_Z,&
            D_Z_TEMP,D_Z_N(0:MAX_I_MAX_TEMP),RHO_D_DZDN_GET(1:MAX_SPECIES),UN_P,TMP_F_GAS,R_PFCT,RHO_D_DZDN
INTEGER :: IW,N,I,J,K,IPZ,N_ZZ_MAX,ICF
REAL(EB), ALLOCATABLE, DIMENSION(:) :: ZZ_GET
TYPE(SPECIES_MIXTURE_TYPE), POINTER :: SM
TYPE(WALL_TYPE), POINTER :: WC
TYPE(EXTERNAL_WALL_TYPE), POINTER :: EWC
TYPE(BOUNDARY_COORD_TYPE), POINTER :: BC
TYPE(BOUNDARY_PROP1_TYPE), POINTER :: B1
TYPE(CFACE_TYPE), POINTER :: CFA

IF (SOLID_PHASE_ONLY) RETURN

SKIP_QR_FLAG = .FALSE.
IF (PRESENT(SKIP_QR)) SKIP_QR_FLAG = SKIP_QR

SELECT CASE(PREDICTOR)
   CASE(.TRUE.)
      DP => M%DS
      PBAR_P => M%PBAR_S
      RHOP => M%RHOS
      UU=>M%U
      VV=>M%V
      WW=>M%W
      ZZP=>M%ZZS
   CASE(.FALSE.)
      DP => M%D
      PBAR_P => M%PBAR
      RHOP => M%RHO
      UU=>M%US
      VV=>M%VS
      WW=>M%WS
      ZZP=>M%ZZ
END SELECT

M%R_PBAR = 1._EB/PBAR_P

RTRM => M%WORK1

! Zero out divergence to start

DP = 0._EB

! Determine if pressure ZONEs have merged

IF (N_ZONE>0 .AND. OBST_CREATED_OR_REMOVED) CALL MERGE_PRESSURE_ZONES

! Compute normal component of velocity at boundaries

WALL_LOOP3: DO IW=1,M%N_EXTERNAL_WALL_CELLS+M%N_INTERNAL_WALL_CELLS
   CALL PREDICT_NORMAL_VELOCITY(IW,T,DT)
ENDDO WALL_LOOP3

IF (CC_IBM) THEN
   CALL CC_VELOCITY_FLUX(M,DT,PREDICTOR,RHOP,CORRECT_GRAV=.FALSE.)
   CALL CFACE_PREDICT_NORMAL_VELOCITY(T,DT)
ENDIF

! --- Species diffusion and heat flux ---

RHO_D_DZDX => M%SWORK1
RHO_D_DZDY => M%SWORK2
RHO_D_DZDZ => M%SWORK3

IF (CHECK_VN) M%D_Z_MAX = 0._EB

SPECIES_GT_1_IF: IF (N_TOTAL_SCALARS>1) THEN

   RHO_D => M%WORK4
   IF (SIM_MODE/=DNS_MODE) THEN
      IF (SIM_MODE==LES_MODE) THEN
         RHO_D_TURB => M%WORK9
         RHO_D_TURB = MAX(0._EB,M%MU-M%MU_DNS)*RSC_T
      ELSE
         RHO_D = MAX(0._EB,M%MU)*RSC_T
      ENDIF
   ENDIF

   CALL COMPUTE_SPECIES_DIFFUSION_FLUXES

   H_RHO_D_DZDX => M%WORK5
   H_RHO_D_DZDY => M%WORK6
   H_RHO_D_DZDZ => M%WORK7

   CALL COMPUTE_DIFFUSIVE_HEAT_FLUX

ENDIF SPECIES_GT_1_IF

! --- Thermodynamic properties (CP, R_H_G) ---

IF (.NOT.CONSTANT_SPECIFIC_HEAT_RATIO) THEN
   CP    => M%WORK5   ! Reuses H_RHO_D_DZDX (no longer needed)
   R_H_G => M%WORK9   ! Reuses RHO_D_TURB (no longer needed)
   CALL COMPUTE_SPECIFIC_HEAT
ENDIF

! --- Thermal conductivity and gradients ---

KDTDX => M%WORK1     ! Reuses RTRM (will be rewritten later)
KDTDY => M%WORK2
KDTDZ => M%WORK3
KP    => M%WORK4     ! Reuses RHO_D (no longer needed)

CALL COMPUTE_THERMAL_CONDUCTIVITY
CALL COMPUTE_THERMAL_DIVERGENCE

! --- Divergence source terms (enthalpy/species advection, RTRM, reactions, etc.) ---

CALL COMPUTE_DIVERGENCE_SOURCES

IF (CC_IBM) CALL CC_DIVERGENCE_PART_1(T,DT,NM)

! --- Pressure zone sums ---

IF (N_ZONE>0) CALL COMPUTE_PRESSURE_ZONE_SUMS


CONTAINS


!> Compute rho*D*grad(Z) for all species, apply wall BCs, flux correction, and store fluxes.
SUBROUTINE COMPUTE_SPECIES_DIFFUSION_FLUXES

M%DEL_RHO_D_DEL_Z = 0._EB

DIFFUSIVE_FLUX_LOOP: DO N=1,N_TOTAL_SCALARS

   IF (SIM_MODE==DNS_MODE .OR. SIM_MODE==LES_MODE) THEN
      RHO_D = 0._EB
      D_Z_N = D_Z(:,N)
      DO K=0,M%KBP1
         DO J=0,M%JBP1
            DO I=0,M%IBP1
               CALL INTERPOLATE1D_UNIFORM(LBOUND(D_Z_N,1),D_Z_N,M%TMP(I,J,K),D_Z_TEMP)
               RHO_D(I,J,K) = RHOP(I,J,K)*D_Z_TEMP
            ENDDO
         ENDDO
      ENDDO
   ENDIF

   IF (SIM_MODE==LES_MODE .AND. .NOT.TENSOR_DIFFUSIVITY) THEN
      SM=>SPECIES_MIXTURE(N)
      IF (SM%SC_T_USER>TWENTY_EPSILON_EB) THEN
         RHO_D = RHO_D + RHO_D_TURB*SC_T/SM%SC_T_USER
      ELSE
         RHO_D = RHO_D + RHO_D_TURB
      ENDIF
   ENDIF

   IF (PERIODIC_TEST==7) RHO_D = DIFF_MMS

   IF (CHECK_VN) THEN
      DO K=0,M%KBP1
         DO J=0,M%JBP1
            DO I=0,M%IBP1
               M%D_Z_MAX(I,J,K) = MAX(M%D_Z_MAX(I,J,K),RHO_D(I,J,K)/(RHOP(I,J,K)+TWENTY_EPSILON_EB))
            ENDDO
         ENDDO
      ENDDO
   ENDIF

   ! Compute rho*D del Z (face gradients)

   DO K=0,M%KBAR
      DO J=0,M%JBAR
         DO I=0,M%IBAR
            DZDX = (ZZP(I+1,J,K,N)-ZZP(I,J,K,N))*M%RDXN(I)
            RHO_D_DZDX(I,J,K,N) = .5_EB*(RHO_D(I+1,J,K)+RHO_D(I,J,K))*DZDX
            DZDY = (ZZP(I,J+1,K,N)-ZZP(I,J,K,N))*M%RDYN(J)
            RHO_D_DZDY(I,J,K,N) = .5_EB*(RHO_D(I,J+1,K)+RHO_D(I,J,K))*DZDY
            DZDZ = (ZZP(I,J,K+1,N)-ZZP(I,J,K,N))*M%RDZN(K)
            RHO_D_DZDZ(I,J,K,N) = .5_EB*(RHO_D(I,J,K+1)+RHO_D(I,J,K))*DZDZ
         ENDDO
      ENDDO
   ENDDO

   IF (TENSOR_DIFFUSIVITY) CALL TENSOR_DIFFUSIVITY_MODEL_KERNEL(M,N)

   ! Apply wall boundary conditions to species diffusion fluxes

   WALL_LOOP: DO IW=1,M%N_EXTERNAL_WALL_CELLS+M%N_INTERNAL_WALL_CELLS
      WC => M%WALL(IW)
      IF (WC%BOUNDARY_TYPE==NULL_BOUNDARY) CYCLE WALL_LOOP
      BC => M%BOUNDARY_COORD(WC%BC_INDEX)
      IF (WC%THIN .AND. BC%IOR<0) CYCLE WALL_LOOP
      BOUNDARY_TYPE_SELECT: SELECT CASE(WC%BOUNDARY_TYPE)
         CASE DEFAULT
            SELECT CASE(BC%IOR)
               CASE( 1); RHO_D_DZDX(BC%IIG-1,BC%JJG  ,BC%KKG  ,N) = 0._EB
               CASE(-1); RHO_D_DZDX(BC%IIG  ,BC%JJG  ,BC%KKG  ,N) = 0._EB
               CASE( 2); RHO_D_DZDY(BC%IIG  ,BC%JJG-1,BC%KKG  ,N) = 0._EB
               CASE(-2); RHO_D_DZDY(BC%IIG  ,BC%JJG  ,BC%KKG  ,N) = 0._EB
               CASE( 3); RHO_D_DZDZ(BC%IIG  ,BC%JJG  ,BC%KKG-1,N) = 0._EB
               CASE(-3); RHO_D_DZDZ(BC%IIG  ,BC%JJG  ,BC%KKG  ,N) = 0._EB
            END SELECT
         CASE(OPEN_BOUNDARY,INTERPOLATED_BOUNDARY)
            B1 => M%BOUNDARY_PROP1(WC%B1_INDEX)
            EWC => M%EXTERNAL_WALL(IW)
            IF (EWC%NIC>1) THEN
               SELECT CASE(BC%IOR)
                  CASE( 1); RHO_D_DZDX(BC%IIG-1,BC%JJG  ,BC%KKG  ,N) =  B1%RHO_D_DZDN_F(N)
                  CASE(-1); RHO_D_DZDX(BC%IIG  ,BC%JJG  ,BC%KKG  ,N) = -B1%RHO_D_DZDN_F(N)
                  CASE( 2); RHO_D_DZDY(BC%IIG  ,BC%JJG-1,BC%KKG  ,N) =  B1%RHO_D_DZDN_F(N)
                  CASE(-2); RHO_D_DZDY(BC%IIG  ,BC%JJG  ,BC%KKG  ,N) = -B1%RHO_D_DZDN_F(N)
                  CASE( 3); RHO_D_DZDZ(BC%IIG  ,BC%JJG  ,BC%KKG-1,N) =  B1%RHO_D_DZDN_F(N)
                  CASE(-3); RHO_D_DZDZ(BC%IIG  ,BC%JJG  ,BC%KKG  ,N) = -B1%RHO_D_DZDN_F(N)
               END SELECT
            ELSE
               SELECT CASE(BC%IOR)
                  CASE( 1); B1%RHO_D_DZDN_F(N) =  RHO_D_DZDX(BC%IIG-1,BC%JJG  ,BC%KKG  ,N)
                  CASE(-1); B1%RHO_D_DZDN_F(N) = -RHO_D_DZDX(BC%IIG  ,BC%JJG  ,BC%KKG  ,N)
                  CASE( 2); B1%RHO_D_DZDN_F(N) =  RHO_D_DZDY(BC%IIG  ,BC%JJG-1,BC%KKG  ,N)
                  CASE(-2); B1%RHO_D_DZDN_F(N) = -RHO_D_DZDY(BC%IIG  ,BC%JJG  ,BC%KKG  ,N)
                  CASE( 3); B1%RHO_D_DZDN_F(N) =  RHO_D_DZDZ(BC%IIG  ,BC%JJG  ,BC%KKG-1,N)
                  CASE(-3); B1%RHO_D_DZDN_F(N) = -RHO_D_DZDZ(BC%IIG  ,BC%JJG  ,BC%KKG  ,N)
               END SELECT
            ENDIF
      END SELECT BOUNDARY_TYPE_SELECT
   ENDDO WALL_LOOP

ENDDO DIFFUSIVE_FLUX_LOOP

! Ensure RHO_D terms sum to zero over all species

IF (SIM_MODE==DNS_MODE .OR. SIM_MODE==LES_MODE .OR. TENSOR_DIFFUSIVITY) THEN
   DO K=0,M%KBAR
      DO J=0,M%JBAR
         DO I=0,M%IBAR
            N=MAXLOC(ZZP(I,J,K,1:N_TRACKED_SPECIES)+ZZP(I+1,J,K,1:N_TRACKED_SPECIES),1)
            RHO_D_DZDX(I,J,K,N) = -(SUM(RHO_D_DZDX(I,J,K,1:N_TRACKED_SPECIES))-RHO_D_DZDX(I,J,K,N))
            N=MAXLOC(ZZP(I,J,K,1:N_TRACKED_SPECIES)+ZZP(I,J+1,K,1:N_TRACKED_SPECIES),1)
            RHO_D_DZDY(I,J,K,N) = -(SUM(RHO_D_DZDY(I,J,K,1:N_TRACKED_SPECIES))-RHO_D_DZDY(I,J,K,N))
            N=MAXLOC(ZZP(I,J,K,1:N_TRACKED_SPECIES)+ZZP(I,J,K+1,1:N_TRACKED_SPECIES),1)
            RHO_D_DZDZ(I,J,K,N) = -(SUM(RHO_D_DZDZ(I,J,K,1:N_TRACKED_SPECIES))-RHO_D_DZDZ(I,J,K,N))
         ENDDO
      ENDDO
   ENDDO
ENDIF

IF (CC_IBM) CALL SET_EXIMDIFFLX_3D(M,RHO_D_DZDX,RHO_D_DZDY,RHO_D_DZDZ)

! Store diffusive flux for output

IF (STORE_SPECIES_FLUX) THEN
   IF (PREDICTOR) THEN
      DO N=1,N_TOTAL_SCALARS
         M%DIF_FX(:,:,:,N) = 0.5_EB*( M%DIF_FXS(:,:,:,N) - RHO_D_DZDX(:,:,:,N) )
         M%DIF_FY(:,:,:,N) = 0.5_EB*( M%DIF_FYS(:,:,:,N) - RHO_D_DZDY(:,:,:,N) )
         M%DIF_FZ(:,:,:,N) = 0.5_EB*( M%DIF_FZS(:,:,:,N) - RHO_D_DZDZ(:,:,:,N) )
      ENDDO
   ELSE
      DO N=1,N_TOTAL_SCALARS
         M%DIF_FXS(:,:,:,N) = -RHO_D_DZDX(:,:,:,N)
         M%DIF_FYS(:,:,:,N) = -RHO_D_DZDY(:,:,:,N)
         M%DIF_FZS(:,:,:,N) = -RHO_D_DZDZ(:,:,:,N)
      ENDDO
   ENDIF
ENDIF

END SUBROUTINE COMPUTE_SPECIES_DIFFUSION_FLUXES


!> Compute h*rho*D*grad(Z), apply wall BCs, add div(h*rho*D*grad(Z)) and DEL_RHO_D_DEL_Z to DP.
SUBROUTINE COMPUTE_DIFFUSIVE_HEAT_FLUX

SPECIES_LOOP: DO N=1,N_TOTAL_SCALARS

   ! Compute enthalpy-weighted diffusion flux on faces

   DO K=0,M%KBAR
      DO J=0,M%JBAR
         DO I=0,M%IBAR
            TMP_G = 0.5_EB*(M%TMP(I+1,J,K)+M%TMP(I,J,K))
            CALL GET_SENSIBLE_ENTHALPY_Z(N,TMP_G,H_S)
            H_RHO_D_DZDX(I,J,K) = H_S*RHO_D_DZDX(I,J,K,N)
            TMP_G = 0.5_EB*(M%TMP(I,J+1,K)+M%TMP(I,J,K))
            CALL GET_SENSIBLE_ENTHALPY_Z(N,TMP_G,H_S)
            H_RHO_D_DZDY(I,J,K) = H_S*RHO_D_DZDY(I,J,K,N)
            TMP_G = 0.5_EB*(M%TMP(I,J,K+1)+M%TMP(I,J,K))
            CALL GET_SENSIBLE_ENTHALPY_Z(N,TMP_G,H_S)
            H_RHO_D_DZDZ(I,J,K) = H_S*RHO_D_DZDZ(I,J,K,N)
         ENDDO
      ENDDO
   ENDDO

   ! Correct rho*D_n grad Z_n and h_n*rho*D_n grad Z_n at boundaries

   WALL_LOOP_2: DO IW=1,M%N_EXTERNAL_WALL_CELLS+M%N_INTERNAL_WALL_CELLS
      WC => M%WALL(IW)
      IF (WC%BOUNDARY_TYPE==NULL_BOUNDARY .OR. &
          WC%BOUNDARY_TYPE==OPEN_BOUNDARY .OR. &
          WC%BOUNDARY_TYPE==INTERPOLATED_BOUNDARY) CYCLE WALL_LOOP_2
      BC => M%BOUNDARY_COORD(WC%BC_INDEX)
      B1 => M%BOUNDARY_PROP1(WC%B1_INDEX)

      N_ZZ_MAX = MAXLOC(B1%ZZ_F(1:N_TRACKED_SPECIES),1)
      RHO_D_DZDN = 2._EB*B1%RHO_D_F(N)*(ZZP(BC%IIG,BC%JJG,BC%KKG,N)-B1%ZZ_F(N))*B1%RDN
      IF (N==N_ZZ_MAX) THEN
         RHO_D_DZDN_GET(1:N_TRACKED_SPECIES) = &
            2._EB*B1%RHO_D_F(:)*(ZZP(BC%IIG,BC%JJG,BC%KKG,:)-B1%ZZ_F(:))*B1%RDN
         RHO_D_DZDN = -(SUM(RHO_D_DZDN_GET(1:N_TRACKED_SPECIES))-RHO_D_DZDN)
      ENDIF
      B1%RHO_D_DZDN_F(N) = RHO_D_DZDN

      IF (WC%THIN .AND. BC%IOR<0) CYCLE WALL_LOOP_2

      IF (STORE_SPECIES_FLUX) THEN
         IF (CORRECTOR) THEN
            SELECT CASE(BC%IOR)
               CASE(-1) ; M%DIF_FXS(BC%IIG  ,BC%JJG  ,BC%KKG  ,N) =  RHO_D_DZDN
               CASE( 1) ; M%DIF_FXS(BC%IIG-1,BC%JJG  ,BC%KKG  ,N) = -RHO_D_DZDN
               CASE(-2) ; M%DIF_FYS(BC%IIG  ,BC%JJG  ,BC%KKG  ,N) =  RHO_D_DZDN
               CASE( 2) ; M%DIF_FYS(BC%IIG  ,BC%JJG-1,BC%KKG  ,N) = -RHO_D_DZDN
               CASE(-3) ; M%DIF_FZS(BC%IIG  ,BC%JJG  ,BC%KKG  ,N) =  RHO_D_DZDN
               CASE( 3) ; M%DIF_FZS(BC%IIG  ,BC%JJG  ,BC%KKG-1,N) = -RHO_D_DZDN
            END SELECT
         ELSE
            SELECT CASE(BC%IOR)
               CASE(-1) ; M%DIF_FX(BC%IIG  ,BC%JJG  ,BC%KKG  ,N) = &
                           0.5_EB*(M%DIF_FXS(BC%IIG  ,BC%JJG  ,BC%KKG  ,N)+RHO_D_DZDN)
               CASE( 1) ; M%DIF_FX(BC%IIG-1,BC%JJG  ,BC%KKG  ,N) = &
                           0.5_EB*(M%DIF_FXS(BC%IIG-1,BC%JJG  ,BC%KKG  ,N)-RHO_D_DZDN)
               CASE(-2) ; M%DIF_FY(BC%IIG  ,BC%JJG  ,BC%KKG  ,N) = &
                           0.5_EB*(M%DIF_FYS(BC%IIG  ,BC%JJG  ,BC%KKG  ,N)+RHO_D_DZDN)
               CASE( 2) ; M%DIF_FY(BC%IIG  ,BC%JJG-1,BC%KKG  ,N) = &
                           0.5_EB*(M%DIF_FYS(BC%IIG  ,BC%JJG-1,BC%KKG  ,N)-RHO_D_DZDN)
               CASE(-3) ; M%DIF_FZ(BC%IIG  ,BC%JJG  ,BC%KKG  ,N) = &
                           0.5_EB*(M%DIF_FZS(BC%IIG  ,BC%JJG  ,BC%KKG  ,N)+RHO_D_DZDN)
               CASE( 3) ; M%DIF_FZ(BC%IIG  ,BC%JJG  ,BC%KKG-1,N) = &
                           0.5_EB*(M%DIF_FZS(BC%IIG  ,BC%JJG  ,BC%KKG-1,N)-RHO_D_DZDN)
            END SELECT
         ENDIF
      ENDIF

      IF (PREDICTOR) THEN
         UN_P = B1%U_NORMAL_S
      ELSE
         UN_P = B1%U_NORMAL
      ENDIF
      IF (WC%BOUNDARY_TYPE==SOLID_BOUNDARY .AND. UN_P>0._EB) THEN
         TMP_F_GAS = M%TMP(BC%IIG,BC%JJG,BC%KKG)
      ELSE
         TMP_F_GAS = B1%TMP_F
      ENDIF

      CALL GET_SENSIBLE_ENTHALPY_Z(N,TMP_F_GAS,H_S)

      SELECT CASE(BC%IOR)
         CASE( 1) ; RHO_D_DZDX(BC%IIG-1,BC%JJG  ,BC%KKG  ,N) =  RHO_D_DZDN
                  H_RHO_D_DZDX(BC%IIG-1,BC%JJG  ,BC%KKG    ) =  RHO_D_DZDN*H_S
         CASE(-1) ; RHO_D_DZDX(BC%IIG  ,BC%JJG  ,BC%KKG  ,N) = -RHO_D_DZDN
                  H_RHO_D_DZDX(BC%IIG  ,BC%JJG  ,BC%KKG    ) = -RHO_D_DZDN*H_S
         CASE( 2) ; RHO_D_DZDY(BC%IIG  ,BC%JJG-1,BC%KKG  ,N) =  RHO_D_DZDN
                  H_RHO_D_DZDY(BC%IIG  ,BC%JJG-1,BC%KKG    ) =  RHO_D_DZDN*H_S
         CASE(-2) ; RHO_D_DZDY(BC%IIG  ,BC%JJG  ,BC%KKG  ,N) = -RHO_D_DZDN
                  H_RHO_D_DZDY(BC%IIG  ,BC%JJG  ,BC%KKG    ) = -RHO_D_DZDN*H_S
         CASE( 3) ; RHO_D_DZDZ(BC%IIG  ,BC%JJG  ,BC%KKG-1,N) =  RHO_D_DZDN
                  H_RHO_D_DZDZ(BC%IIG  ,BC%JJG  ,BC%KKG-1  ) =  RHO_D_DZDN*H_S
         CASE(-3) ; RHO_D_DZDZ(BC%IIG  ,BC%JJG  ,BC%KKG  ,N) = -RHO_D_DZDN
                  H_RHO_D_DZDZ(BC%IIG  ,BC%JJG  ,BC%KKG    ) = -RHO_D_DZDN*H_S
      END SELECT

   ENDDO WALL_LOOP_2

   ! Add div(h*rho*D*grad(Z)) and div(rho*D*grad(Z)) to DP (fused, tiled)

   DO K=1,M%KBAR
      DO J=1,M%JBAR
         DO I=1,M%IBAR
            DIV_DIFF_HEAT_FLUX = &
               (M%R(I)*H_RHO_D_DZDX(I,J,K)-M%R(I-1)*H_RHO_D_DZDX(I-1,J,K))*M%RDX(I)*M%RRN(I) + &
               (       H_RHO_D_DZDY(I,J,K)-          H_RHO_D_DZDY(I,J-1,K))*M%RDY(J)           + &
               (       H_RHO_D_DZDZ(I,J,K)-          H_RHO_D_DZDZ(I,J,K-1))*M%RDZ(K)
            DP(I,J,K) = DP(I,J,K) + DIV_DIFF_HEAT_FLUX
            M%DEL_RHO_D_DEL_Z(I,J,K,N) = &
               (M%R(I)*RHO_D_DZDX(I,J,K,N)-M%R(I-1)*RHO_D_DZDX(I-1,J,K,N))*M%RDX(I)*M%RRN(I) + &
               (       RHO_D_DZDY(I,J,K,N)-          RHO_D_DZDY(I,J-1,K,N))*M%RDY(J)           + &
               (       RHO_D_DZDZ(I,J,K,N)-          RHO_D_DZDZ(I,J,K-1,N))*M%RDZ(K)
         ENDDO
      ENDDO
   ENDDO

ENDDO SPECIES_LOOP

END SUBROUTINE COMPUTE_DIFFUSIVE_HEAT_FLUX


!> Compute specific heat CP and reciprocal enthalpy R_H_G = 1/(CP*TMP).
SUBROUTINE COMPUTE_SPECIFIC_HEAT

REAL(EB), ALLOCATABLE, DIMENSION(:) :: ZZ_GET_LOC
ALLOCATE(ZZ_GET_LOC(1:N_TRACKED_SPECIES))
DO K=1,M%KBAR
   DO J=1,M%JBAR
      DO I=1,M%IBAR
         ZZ_GET_LOC(1:N_TRACKED_SPECIES) = ZZP(I,J,K,1:N_TRACKED_SPECIES)
         CALL GET_SPECIFIC_HEAT(ZZ_GET_LOC,CP(I,J,K),M%TMP(I,J,K))
         R_H_G(I,J,K) = 1._EB/(CP(I,J,K)*M%TMP(I,J,K))
      ENDDO
   ENDDO
ENDDO
DEALLOCATE(ZZ_GET_LOC)

END SUBROUTINE COMPUTE_SPECIFIC_HEAT


!> Compute thermal conductivity KP, apply LES turbulent correction and boundary ghost copy.
SUBROUTINE COMPUTE_THERMAL_CONDUCTIVITY

REAL(EB), ALLOCATABLE, DIMENSION(:) :: ZZ_GET_LOC
K_DNS_OR_LES: IF (SIM_MODE==DNS_MODE .OR. SIM_MODE==LES_MODE) THEN

   ALLOCATE(ZZ_GET_LOC(1:N_TRACKED_SPECIES))
   KP = 0._EB
   DO K=1,M%KBAR
      DO J=1,M%JBAR
         DO I=1,M%IBAR
            IF (M%CELL(M%CELL_INDEX(I,J,K))%SOLID) CYCLE
            ZZ_GET_LOC(1:N_TRACKED_SPECIES) = ZZP(I,J,K,1:N_TRACKED_SPECIES)
            CALL GET_CONDUCTIVITY(ZZ_GET_LOC,KP(I,J,K),M%TMP(I,J,K))
         ENDDO
      ENDDO
   ENDDO
   DEALLOCATE(ZZ_GET_LOC)

   IF (SIM_MODE==LES_MODE .AND. .NOT.TENSOR_DIFFUSIVITY) THEN
      IF(.NOT.CONSTANT_SPECIFIC_HEAT_RATIO) THEN
         KP = KP + MAX(0._EB,(M%MU-M%MU_DNS))*CP*RPR_T
      ELSE
         KP = KP + MAX(0._EB,(M%MU-M%MU_DNS))*CPOPR
      ENDIF
   ENDIF

   BOUNDARY_LOOP: DO IW=1,M%N_EXTERNAL_WALL_CELLS
      WC=>M%WALL(IW)
      BC => M%BOUNDARY_COORD(WC%BC_INDEX)
      KP(BC%II,BC%JJ,BC%KK) = KP(BC%IIG,BC%JJG,BC%KKG)
   ENDDO BOUNDARY_LOOP

ELSE K_DNS_OR_LES

   KP = M%MU*CPOPR

ENDIF K_DNS_OR_LES

! Store max thermal diffusivity for stability check

IF (CHECK_VN .AND. .NOT.CONSTANT_SPECIFIC_HEAT_RATIO) THEN
   DO K=1,M%KBAR
      DO J=1,M%JBAR
         DO I=1,M%IBAR
            M%D_Z_MAX(I,J,K) = MAX(M%D_Z_MAX(I,J,K),KP(I,J,K)/(CP(I,J,K)*RHOP(I,J,K)))
         ENDDO
      ENDDO
   ENDDO
ENDIF

END SUBROUTINE COMPUTE_THERMAL_CONDUCTIVITY


!> Compute k*grad(T), apply wall corrections, add div(k*grad(T)) + Q + QR to DP.
SUBROUTINE COMPUTE_THERMAL_DIVERGENCE

! Compute k*dT/dx, k*dT/dy, k*dT/dz on faces

DO K=0,M%KBAR
   DO J=0,M%JBAR
      DO I=0,M%IBAR
         DTDX = (M%TMP(I+1,J,K)-M%TMP(I,J,K))*M%RDXN(I)
         KDTDX(I,J,K) = .5_EB*(KP(I+1,J,K)+KP(I,J,K))*DTDX
         DTDY = (M%TMP(I,J+1,K)-M%TMP(I,J,K))*M%RDYN(J)
         KDTDY(I,J,K) = .5_EB*(KP(I,J+1,K)+KP(I,J,K))*DTDY
         DTDZ = (M%TMP(I,J,K+1)-M%TMP(I,J,K))*M%RDZN(K)
         KDTDZ(I,J,K) = .5_EB*(KP(I,J,K+1)+KP(I,J,K))*DTDZ
      ENDDO
   ENDDO
ENDDO

IF (TENSOR_DIFFUSIVITY) CALL TENSOR_DIFFUSIVITY_MODEL_KERNEL(M)

! Correct thermal gradient at boundaries

CORRECTION_LOOP: DO IW=1,M%N_EXTERNAL_WALL_CELLS+M%N_INTERNAL_WALL_CELLS
   WC => M%WALL(IW)
   IF (WC%BOUNDARY_TYPE==NULL_BOUNDARY .OR. WC%BOUNDARY_TYPE==INTERPOLATED_BOUNDARY) CYCLE CORRECTION_LOOP
   BC => M%BOUNDARY_COORD(WC%BC_INDEX)
   B1 => M%BOUNDARY_PROP1(WC%B1_INDEX)
   IF (WC%BOUNDARY_TYPE==OPEN_BOUNDARY) THEN
      B1%K_G = 0.5_EB*(KP(BC%IIG,BC%JJG,BC%KKG)+KP(BC%II,BC%JJ,BC%KK))
      CYCLE CORRECTION_LOOP
   ELSE
      B1%K_G = KP(BC%IIG,BC%JJG,BC%KKG)
   ENDIF
   DP(BC%IIG,BC%JJG,BC%KKG) = DP(BC%IIG,BC%JJG,BC%KKG) - ( B1%AREA_ADJUST*B1%Q_CON_F*B1%RDN - B1%Q_LEAK )
   IF (WC%THIN .AND. BC%IOR<0) CYCLE CORRECTION_LOOP
   SELECT CASE(BC%IOR)
      CASE( 1) ; KDTDX(BC%II  ,BC%JJ  ,BC%KK  ) = 0._EB
      CASE(-1) ; KDTDX(BC%II-1,BC%JJ  ,BC%KK  ) = 0._EB
      CASE( 2) ; KDTDY(BC%II  ,BC%JJ  ,BC%KK  ) = 0._EB
      CASE(-2) ; KDTDY(BC%II  ,BC%JJ-1,BC%KK  ) = 0._EB
      CASE( 3) ; KDTDZ(BC%II  ,BC%JJ  ,BC%KK  ) = 0._EB
      CASE(-3) ; KDTDZ(BC%II  ,BC%JJ  ,BC%KK-1) = 0._EB
   END SELECT
ENDDO CORRECTION_LOOP

! Compute div(k*grad(T)) + Q [+ QR] and add to divergence

CYLINDER3: SELECT CASE(CYLINDRICAL)
CASE(.FALSE.) CYLINDER3
   IF (SKIP_QR_FLAG) THEN
      DO K=1,M%KBAR
         DO J=1,M%JBAR
            DO I=1,M%IBAR
               DELKDELT = (KDTDX(I,J,K)-KDTDX(I-1,J,K))*M%RDX(I) + &
                          (KDTDY(I,J,K)-KDTDY(I,J-1,K))*M%RDY(J) + &
                          (KDTDZ(I,J,K)-KDTDZ(I,J,K-1))*M%RDZ(K)
               DP(I,J,K) = DP(I,J,K) + DELKDELT + M%Q(I,J,K)
            ENDDO
         ENDDO
      ENDDO
   ELSE
      DO K=1,M%KBAR
         DO J=1,M%JBAR
            DO I=1,M%IBAR
               DELKDELT = (KDTDX(I,J,K)-KDTDX(I-1,J,K))*M%RDX(I) + &
                          (KDTDY(I,J,K)-KDTDY(I,J-1,K))*M%RDY(J) + &
                          (KDTDZ(I,J,K)-KDTDZ(I,J,K-1))*M%RDZ(K)
               DP(I,J,K) = DP(I,J,K) + DELKDELT + M%Q(I,J,K) + M%QR(I,J,K)
            ENDDO
         ENDDO
      ENDDO
   ENDIF
CASE(.TRUE.) CYLINDER3
   IF (SKIP_QR_FLAG) THEN
      DO K=1,M%KBAR
         DO J=1,M%JBAR
            DO I=1,M%IBAR
               DELKDELT = &
                    (M%R(I)*KDTDX(I,J,K)-M%R(I-1)*KDTDX(I-1,J,K))*M%RDX(I)*M%RRN(I) + &
                    (KDTDZ(I,J,K)-KDTDZ(I,J,K-1))*M%RDZ(K)
               DP(I,J,K) = DP(I,J,K) + DELKDELT + M%Q(I,J,K)
            ENDDO
         ENDDO
      ENDDO
   ELSE
      DO K=1,M%KBAR
         DO J=1,M%JBAR
            DO I=1,M%IBAR
               DELKDELT = &
                    (M%R(I)*KDTDX(I,J,K)-M%R(I-1)*KDTDX(I-1,J,K))*M%RDX(I)*M%RRN(I) + &
                    (KDTDZ(I,J,K)-KDTDZ(I,J,K-1))*M%RDZ(K)
               DP(I,J,K) = DP(I,J,K) + DELKDELT + M%Q(I,J,K) + M%QR(I,J,K)
            ENDDO
         ENDDO
      ENDDO
   ENDIF
END SELECT CYLINDER3

END SUBROUTINE COMPUTE_THERMAL_DIVERGENCE


!> Compute enthalpy/species advection, RTRM, reactions, stratification, MMS sources into DP.
SUBROUTINE COMPUTE_DIVERGENCE_SOURCES

! Enthalpy advection

CONST_GAMMA_IF_1: IF (.NOT.CONSTANT_SPECIFIC_HEAT_RATIO) THEN

   CALL ENTHALPY_ADVECTION_NEW(U_DOT_DEL_RHO_H_S)

   DO K=1,M%KBAR
      DO J=1,M%JBAR
         DO I=1,M%IBAR
            DP(I,J,K) = DP(I,J,K) - U_DOT_DEL_RHO_H_S(I,J,K)
         ENDDO
      ENDDO
   ENDDO

   IF (CC_IBM) CALL SET_EXIMRHOHSLIM_3D(M)

ENDIF CONST_GAMMA_IF_1

! Compute RTRM = 1/(rho*c_p*T) and multiply divergence

IF (CONSTANT_SPECIFIC_HEAT_RATIO) THEN

   DO K=1,M%KBAR
      DO J=1,M%JBAR
         DO I=1,M%IBAR
            IPZ = M%PRESSURE_ZONE(I,J,K)
            RTRM(I,J,K) = GM1OG*M%R_PBAR(K,IPZ)
            DP(I,J,K)   = RTRM(I,J,K)*DP(I,J,K)
         ENDDO
      ENDDO
   ENDDO

ELSE

   DO K=1,M%KBAR
      DO J=1,M%JBAR
         DO I=1,M%IBAR
            RTRM(I,J,K) = R_H_G(I,J,K)/RHOP(I,J,K)
            DP(I,J,K) = RTRM(I,J,K)*DP(I,J,K)
         ENDDO
      ENDDO
   ENDDO

ENDIF

! Species advection source terms

CONST_GAMMA_IF_2: IF (.NOT.CONSTANT_SPECIFIC_HEAT_RATIO) THEN

   CALL SPECIES_ADVECTION_PART_1_NEW

   DO N=1,N_TRACKED_SPECIES

      CALL SPECIES_ADVECTION_PART_2(N,U_DOT_DEL_RHO_Z)

      SM  => SPECIES_MIXTURE(N)
      DO K=1,M%KBAR
         DO J=1,M%JBAR
            DO I=1,M%IBAR
               IF (M%CELL(M%CELL_INDEX(I,J,K))%SOLID) CYCLE
               CALL GET_SENSIBLE_ENTHALPY_Z(N,M%TMP(I,J,K),H_S)
               DP(I,J,K) = DP(I,J,K) + (SM%RCON/M%RSUM(I,J,K) - H_S*R_H_G(I,J,K))* &
                    ( M%DEL_RHO_D_DEL_Z(I,J,K,N) - U_DOT_DEL_RHO_Z(I,J,K) )/RHOP(I,J,K)
            ENDDO
         ENDDO
      ENDDO

      IF (CC_IBM) CALL SET_EXIMRHOZZLIM_3D(M,N)

   ENDDO

ENDIF CONST_GAMMA_IF_2

! Reactions

IF (N_REACTIONS > 0 .OR. N_LP_ARRAY_INDICES>0 .OR. ANY(SPECIES_MIXTURE%DEPOSITING) .OR. &
    ANY(SPECIES_MIXTURE%CONDENSATION_SMIX_INDEX>0)) THEN
   DO K=1,M%KBAR
      DO J=1,M%JBAR
         DO I=1,M%IBAR
            DP(I,J,K) = DP(I,J,K) + M%D_SOURCE(I,J,K)
         ENDDO
      ENDDO
   ENDDO
ENDIF

! Atmospheric stratification

IF (STRATIFICATION) THEN
   DO K=1,M%KBAR
      DO J=1,M%JBAR
         DO I=1,M%IBAR
            DP(I,J,K) = DP(I,J,K) + RTRM(I,J,K)*0.5_EB*(WW(I,J,K)+WW(I,J,K-1))*M%RHO_0(K)*GVEC(3)
         ENDDO
      ENDDO
   ENDDO
ENDIF

! Manufactured solution

MMS_IF: IF (PERIODIC_TEST==7) THEN
   IF (PREDICTOR) TT=T+DT
   IF (CORRECTOR) TT=T
   DO K=1,M%KBAR
      DO J=1,M%JBAR
         DO I=1,M%IBAR
            XHAT = M%XC(I) - UF_MMS*TT
            ZHAT = M%ZC(K) - WF_MMS*TT
            DO N=1,N_TRACKED_SPECIES
               SM => SPECIES_MIXTURE(N)
               SELECT CASE(N)
                  CASE(1); Q_Z = -VD2D_MMS_Z_SRC(XHAT,ZHAT,TT)
                  CASE(2); Q_Z =  VD2D_MMS_Z_SRC(XHAT,ZHAT,TT)
               END SELECT
               CALL GET_SENSIBLE_ENTHALPY_Z(N,M%TMP(I,J,K),H_S)
               DP(I,J,K) = DP(I,J,K) + ( SM%RCON/M%RSUM(I,J,K) - H_S*R_H_G(I,J,K) )*Q_Z/RHOP(I,J,K)
            ENDDO
         ENDDO
      ENDDO
   ENDDO
ENDIF MMS_IF

END SUBROUTINE COMPUTE_DIVERGENCE_SOURCES


!> Compute DSUM, PSUM, USUM for pressure zone accumulation.
SUBROUTINE COMPUTE_PRESSURE_ZONE_SUMS

R_PFCT = 1._EB
DO K=1,M%KBAR
   DO J=1,M%JBAR
      VC1 = M%DY(J)*M%DZ(K)
      DO I=1,M%IBAR
         IF (M%INTERPOLATED_MESH(I,J,K)>0) CYCLE
         IPZ = M%PRESSURE_ZONE(I,J,K)
         IF (IPZ<1) CYCLE
         IF (M%CELL(M%CELL_INDEX(I,J,K))%SOLID) CYCLE
         VC = M%DX(I)*M%RC(I)*VC1
         DSUM(IPZ) = DSUM(IPZ) + VC*DP(I,J,K)
         IF (CC_IBM) THEN
            R_PFCT = 1._EB
            IF (M%CCVAR(I,J,K,CC_CGSC) == CC_SOLID) THEN
               CYCLE
            ELSEIF(M%CCVAR(I,J,K,CC_CGSC) == CC_CUTCFE) THEN
               CALL ADD_CUTCELL_PSUM(M,I,J,K, &
                  PBAR_P(K,IPZ),PSUM(IPZ)); CYCLE
            ELSEIF(M%CCVAR(I,J,K,CC_UNKZ) > 0) THEN
               CALL ADD_LINKEDCELL_PSUM(M,I,J,K, &
                  VC,PBAR_P(K,IPZ),RTRM(I,J,K), &
                  PSUM(IPZ)); CYCLE
            ENDIF
         ENDIF
         PSUM(IPZ) = PSUM(IPZ) + VC*(M%R_PBAR(K,IPZ)*R_PFCT-RTRM(I,J,K))
      ENDDO
   ENDDO
ENDDO

! Volume flux to boundary of pressure zone

WALL_LOOP4: DO IW=1,M%N_EXTERNAL_WALL_CELLS+M%N_INTERNAL_WALL_CELLS
   WC => M%WALL(IW)
   BC => M%BOUNDARY_COORD(WC%BC_INDEX)
   IF (M%INTERPOLATED_MESH(BC%IIG,BC%JJG,BC%KKG)>0) CYCLE
   B1 => M%BOUNDARY_PROP1(WC%B1_INDEX)
   IPZ = B1%PRESSURE_ZONE
   IF (IPZ<1) CYCLE WALL_LOOP4
   IF (WC%BOUNDARY_TYPE/=SOLID_BOUNDARY) CYCLE WALL_LOOP4
   IF (PREDICTOR) USUM(IPZ) = USUM(IPZ) + B1%U_NORMAL_S*B1%AREA
   IF (CORRECTOR) USUM(IPZ) = USUM(IPZ) + B1%U_NORMAL  *B1%AREA
ENDDO WALL_LOOP4

CFACE_LOOP: DO ICF=M%INTERNAL_CFACE_CELLS_LB+1,M%INTERNAL_CFACE_CELLS_LB+M%N_INTERNAL_CFACE_CELLS
   CFA => M%CFACE(ICF)
   BC => M%BOUNDARY_COORD(CFA%BC_INDEX)
   B1 => M%BOUNDARY_PROP1(CFA%B1_INDEX)
   IPZ = B1%PRESSURE_ZONE
   IF (IPZ<1) CYCLE CFACE_LOOP
   IF (PREDICTOR) USUM(IPZ) = USUM(IPZ) + B1%U_NORMAL_S*B1%AREA
   IF (CORRECTOR) USUM(IPZ) = USUM(IPZ) + B1%U_NORMAL  *B1%AREA
ENDDO CFACE_LOOP

END SUBROUTINE COMPUTE_PRESSURE_ZONE_SUMS


SUBROUTINE ENTHALPY_ADVECTION_NEW(U_DOT_DEL_RHO_H_S)

USE PHYSICAL_FUNCTIONS, ONLY: GET_SENSIBLE_ENTHALPY
USE MATH_FUNCTIONS, ONLY: GET_SCALAR_FACE_VALUE
REAL(EB), POINTER, DIMENSION(:,:,:) :: FX_H_S,FY_H_S,FZ_H_S,RHO_H_S_P,U_DOT_DEL_RHO_H_S
REAL(EB) :: UN,UN_P,TMP_F_GAS,DU_P,DU_M,DV_P,DV_M,DW_P,DW_M,DU,H_S
REAL(EB), ALLOCATABLE, DIMENSION(:) :: ZZ_GET
REAL(EB), TARGET, DIMENSION(0:3,0:3,0:3) :: F_WORK
REAL(EB), TARGET, DIMENSION(-1:3,-1:3,-1:3) :: U_WORK,Z_WORK
REAL(EB), POINTER, DIMENSION(:,:,:) :: F_TEMP,U_TEMP,Z_TEMP
INTEGER :: IC,I,J,K,IW
TYPE(WALL_TYPE), POINTER :: WC
TYPE(BOUNDARY_COORD_TYPE), POINTER :: BC
TYPE(BOUNDARY_PROP1_TYPE), POINTER :: B1

RHO_H_S_P=>M%WORK_PAD ; RHO_H_S_P = 0._EB
FX_H_S=>M%WORK2    ; FX_H_S = 0._EB
FY_H_S=>M%WORK3    ; FY_H_S = 0._EB
FZ_H_S=>M%WORK4    ; FZ_H_S = 0._EB
U_DOT_DEL_RHO_H_S=>M%WORK6 ; U_DOT_DEL_RHO_H_S=0._EB

! Compute and store rho*h_s

ALLOCATE(ZZ_GET(1:N_TRACKED_SPECIES))
DO K=-1,M%KBP1+1
   DO J=-1,M%JBP1+1
      DO I=-1,M%IBP1+1
ZZ_GET(1:N_TRACKED_SPECIES) = ZZP(I,J,K,1:N_TRACKED_SPECIES)
CALL GET_SENSIBLE_ENTHALPY(ZZ_GET,H_S,M%TMP(I,J,K))
RHO_H_S_P(I,J,K) = RHOP(I,J,K)*H_S
      ENDDO
   ENDDO
ENDDO
DEALLOCATE(ZZ_GET)

! Compute scalar face values

CALL GET_SCALAR_FACE_VALUE(UU,RHO_H_S_P,FX_H_S,0,M%IBAR,1,M%JBAR,1,M%KBAR,1,I_FLUX_LIMITER)
CALL GET_SCALAR_FACE_VALUE(VV,RHO_H_S_P,FY_H_S,1,M%IBAR,0,M%JBAR,1,M%KBAR,2,I_FLUX_LIMITER)
CALL GET_SCALAR_FACE_VALUE(WW,RHO_H_S_P,FZ_H_S,1,M%IBAR,1,M%JBAR,0,M%KBAR,3,I_FLUX_LIMITER)

ALLOCATE(ZZ_GET(1:N_TRACKED_SPECIES))

WALL_LOOP: DO IW=1,M%N_EXTERNAL_WALL_CELLS+M%N_INTERNAL_WALL_CELLS

   WC=>M%WALL(IW)
   IF (WC%BOUNDARY_TYPE==NULL_BOUNDARY) CYCLE WALL_LOOP
   BC => M%BOUNDARY_COORD(WC%BC_INDEX)
   B1 => M%BOUNDARY_PROP1(WC%B1_INDEX)

   ! Calculate the sensible enthalpy at the boundary. If the boundary is solid
   ! and the gas is flowing out, use the gas temperature for the calculation.

   IF (PREDICTOR) THEN
      UN_P = B1%U_NORMAL_S
   ELSE
      UN_P = B1%U_NORMAL
   ENDIF
   IF (WC%BOUNDARY_TYPE==SOLID_BOUNDARY .AND. UN_P>0._EB) THEN
      TMP_F_GAS = M%TMP(BC%IIG,BC%JJG,BC%KKG)
   ELSE
      TMP_F_GAS = B1%TMP_F
   ENDIF

   ZZ_GET(1:N_TRACKED_SPECIES) = B1%ZZ_F(1:N_TRACKED_SPECIES)
   CALL GET_SENSIBLE_ENTHALPY(ZZ_GET,H_S,TMP_F_GAS)

   ! overwrite first off-wall advective flux if flow is away from the wall and if the face is not also a wall cell

   IF (WC%BOUNDARY_TYPE/=INTERPOLATED_BOUNDARY .AND. WC%BOUNDARY_TYPE/=OPEN_BOUNDARY) THEN

      U_TEMP => U_WORK
      F_TEMP => F_WORK
      Z_TEMP => Z_WORK
      OFF_WALL_SELECT_1: SELECT CASE(BC%IOR)
         CASE( 1) OFF_WALL_SELECT_1
            !      ghost          FX/UU(II+1)
            ! ///   II   ///  II+1  |  II+2  | ...
            !                       ^ WALL_INDEX(II+1,+1)
            IF ((UU(BC%II+1,BC%JJ,BC%KK)>0._EB) .AND. .NOT.(M%CELL(M%CELL_INDEX(BC%II+1,BC%JJ,BC%KK))%WALL_INDEX(+1)>0)) THEN
               Z_TEMP(0:2,1,1) = (/RHO_H_S_P(BC%II+1,BC%JJ,BC%KK),RHO_H_S_P(BC%II+1:BC%II+2,BC%JJ,BC%KK)/)
               U_TEMP(1,1,1) = UU(BC%II+1,BC%JJ,BC%KK)
               CALL GET_SCALAR_FACE_VALUE(U_TEMP,Z_TEMP,F_TEMP,1,1,1,1,1,1,1,I_FLUX_LIMITER)
               FX_H_S(BC%II+1,BC%JJ,BC%KK) = F_TEMP(1,1,1)
            ENDIF
         CASE(-1) OFF_WALL_SELECT_1
            !            FX/UU(II-2)     ghost
            ! ... |  II-2  |  II-1  ///   II   ///
            !              ^ WALL_INDEX(II-1,-1)
            IF ((UU(BC%II-2,BC%JJ,BC%KK)<0._EB) .AND. .NOT.(M%CELL(M%CELL_INDEX(BC%II-1,BC%JJ,BC%KK))%WALL_INDEX(-1)>0)) THEN
               Z_TEMP(1:3,1,1) = (/RHO_H_S_P(BC%II-2:BC%II-1,BC%JJ,BC%KK),RHO_H_S_P(BC%II-1,BC%JJ,BC%KK)/)
               U_TEMP(1,1,1) = UU(BC%II-2,BC%JJ,BC%KK)
               CALL GET_SCALAR_FACE_VALUE(U_TEMP,Z_TEMP,F_TEMP,1,1,1,1,1,1,1,I_FLUX_LIMITER)
               FX_H_S(BC%II-2,BC%JJ,BC%KK) = F_TEMP(1,1,1)
            ENDIF
         CASE( 2) OFF_WALL_SELECT_1
            IF ((VV(BC%II,BC%JJ+1,BC%KK)>0._EB) .AND. .NOT.(M%CELL(M%CELL_INDEX(BC%II,BC%JJ+1,BC%KK))%WALL_INDEX(+2)>0)) THEN
               Z_TEMP(1,0:2,1) = (/RHO_H_S_P(BC%II,BC%JJ+1,BC%KK),RHO_H_S_P(BC%II,BC%JJ+1:BC%JJ+2,BC%KK)/)
               U_TEMP(1,1,1) = VV(BC%II,BC%JJ+1,BC%KK)
               CALL GET_SCALAR_FACE_VALUE(U_TEMP,Z_TEMP,F_TEMP,1,1,1,1,1,1,2,I_FLUX_LIMITER)
               FY_H_S(BC%II,BC%JJ+1,BC%KK) = F_TEMP(1,1,1)
            ENDIF
         CASE(-2) OFF_WALL_SELECT_1
            IF ((VV(BC%II,BC%JJ-2,BC%KK)<0._EB) .AND. .NOT.(M%CELL(M%CELL_INDEX(BC%II,BC%JJ-1,BC%KK))%WALL_INDEX(-2)>0)) THEN
               Z_TEMP(1,1:3,1) = (/RHO_H_S_P(BC%II,BC%JJ-2:BC%JJ-1,BC%KK),RHO_H_S_P(BC%II,BC%JJ-1,BC%KK)/)
               U_TEMP(1,1,1) = VV(BC%II,BC%JJ-2,BC%KK)
               CALL GET_SCALAR_FACE_VALUE(U_TEMP,Z_TEMP,F_TEMP,1,1,1,1,1,1,2,I_FLUX_LIMITER)
               FY_H_S(BC%II,BC%JJ-2,BC%KK) = F_TEMP(1,1,1)
            ENDIF
         CASE( 3) OFF_WALL_SELECT_1
            IF ((WW(BC%II,BC%JJ,BC%KK+1)>0._EB) .AND. .NOT.(M%CELL(M%CELL_INDEX(BC%II,BC%JJ,BC%KK+1))%WALL_INDEX(+3)>0)) THEN
               Z_TEMP(1,1,0:2) = (/RHO_H_S_P(BC%II,BC%JJ,BC%KK+1),RHO_H_S_P(BC%II,BC%JJ,BC%KK+1:BC%KK+2)/)
               U_TEMP(1,1,1) = WW(BC%II,BC%JJ,BC%KK+1)
               CALL GET_SCALAR_FACE_VALUE(U_TEMP,Z_TEMP,F_TEMP,1,1,1,1,1,1,3,I_FLUX_LIMITER)
               FZ_H_S(BC%II,BC%JJ,BC%KK+1) = F_TEMP(1,1,1)
            ENDIF
         CASE(-3) OFF_WALL_SELECT_1
            IF ((WW(BC%II,BC%JJ,BC%KK-2)<0._EB) .AND. .NOT.(M%CELL(M%CELL_INDEX(BC%II,BC%JJ,BC%KK-1))%WALL_INDEX(-3)>0)) THEN
               Z_TEMP(1,1,1:3) = (/RHO_H_S_P(BC%II,BC%JJ,BC%KK-2:BC%KK-1),RHO_H_S_P(BC%II,BC%JJ,BC%KK-1)/)
               U_TEMP(1,1,1) = WW(BC%II,BC%JJ,BC%KK-2)
               CALL GET_SCALAR_FACE_VALUE(U_TEMP,Z_TEMP,F_TEMP,1,1,1,1,1,1,3,I_FLUX_LIMITER)
               FZ_H_S(BC%II,BC%JJ,BC%KK-2) = F_TEMP(1,1,1)
            ENDIF
      END SELECT OFF_WALL_SELECT_1

   ENDIF

   SELECT CASE(WC%BOUNDARY_TYPE)
      CASE DEFAULT
         IOR_SELECT: SELECT CASE(BC%IOR)
            CASE( 1); UN = UU(BC%II  ,BC%JJ  ,BC%KK  )
            CASE(-1); UN = UU(BC%II-1,BC%JJ  ,BC%KK  )
            CASE( 2); UN = VV(BC%II  ,BC%JJ  ,BC%KK  )
            CASE(-2); UN = VV(BC%II  ,BC%JJ-1,BC%KK  )
            CASE( 3); UN = WW(BC%II  ,BC%JJ  ,BC%KK  )
            CASE(-3); UN = WW(BC%II  ,BC%JJ  ,BC%KK-1)
         END SELECT IOR_SELECT
      CASE(SOLID_BOUNDARY)
         IF (PREDICTOR) UN = -SIGN(1._EB,REAL(BC%IOR,EB))*B1%U_NORMAL_S
         IF (CORRECTOR) UN = -SIGN(1._EB,REAL(BC%IOR,EB))*B1%U_NORMAL
      CASE(INTERPOLATED_BOUNDARY)
         UN = M%UVW_SAVE(IW)
   END SELECT

   DU = (B1%RHO_F*H_S - RHO_H_S_P(BC%IIG,BC%JJG,BC%KKG))*UN
   U_DOT_DEL_RHO_H_S(BC%IIG,BC%JJG,BC%KKG) = U_DOT_DEL_RHO_H_S(BC%IIG,BC%JJG,BC%KKG) - SIGN(1._EB,REAL(BC%IOR,EB))*DU*B1%RDN

ENDDO WALL_LOOP

DEALLOCATE(ZZ_GET)

! FDS Tech Guide (B.12-B.14)

DO K=1,M%KBAR
   DO J=1,M%JBAR
      DO I=1,M%IBAR
IC = M%CELL_INDEX(I,J,K)
IF (M%CELL(IC)%SOLID) CYCLE
DU_P = 0._EB
DU_M = 0._EB
DV_P = 0._EB
DV_M = 0._EB
DW_P = 0._EB
DW_M = 0._EB
IF (M%CELL(IC)%WALL_INDEX( 1)==0) DU_P = (FX_H_S(I,J,K)   - RHO_H_S_P(I,J,K))*UU(I,J,K)
IF (M%CELL(IC)%WALL_INDEX(-1)==0) DU_M = (FX_H_S(I-1,J,K) - RHO_H_S_P(I,J,K))*UU(I-1,J,K)
IF (M%CELL(IC)%WALL_INDEX( 2)==0) DV_P = (FY_H_S(I,J,K)   - RHO_H_S_P(I,J,K))*VV(I,J,K)
IF (M%CELL(IC)%WALL_INDEX(-2)==0) DV_M = (FY_H_S(I,J-1,K) - RHO_H_S_P(I,J,K))*VV(I,J-1,K)
IF (M%CELL(IC)%WALL_INDEX( 3)==0) DW_P = (FZ_H_S(I,J,K)   - RHO_H_S_P(I,J,K))*WW(I,J,K)
IF (M%CELL(IC)%WALL_INDEX(-3)==0) DW_M = (FZ_H_S(I,J,K-1) - RHO_H_S_P(I,J,K))*WW(I,J,K-1)
U_DOT_DEL_RHO_H_S(I,J,K) = U_DOT_DEL_RHO_H_S(I,J,K) &
   + (DU_P-DU_M)*M%RDX(I) + (DV_P-DV_M)*M%RDY(J) + (DW_P-DW_M)*M%RDZ(K)
      ENDDO
   ENDDO
ENDDO

END SUBROUTINE ENTHALPY_ADVECTION_NEW



SUBROUTINE SPECIES_ADVECTION_PART_1_NEW

USE MATH_FUNCTIONS, ONLY: GET_SCALAR_FACE_VALUE
USE PHYSICAL_FUNCTIONS, ONLY: GET_MOLECULAR_WEIGHT
! INTEGER, INTENT(IN) :: N
REAL(EB), POINTER, DIMENSION(:,:,:) :: RHO_Z_P,RHO_RMW,FX_P,FY_P,FZ_P
REAL(EB), POINTER, DIMENSION(:,:,:,:) :: FX_ZZ,FY_ZZ,FZ_ZZ
REAL(EB) :: ZZ_GET(1:N_TRACKED_SPECIES),MW_G
REAL(EB), TARGET, DIMENSION(0:3,0:3,0:3) :: F_WORK
REAL(EB), TARGET, DIMENSION(-1:3,-1:3,-1:3) :: U_WORK,Z_WORK
REAL(EB), POINTER, DIMENSION(:,:,:) :: F_TEMP,U_TEMP,Z_TEMP
INTEGER :: I,J,K,IW,N
TYPE(WALL_TYPE), POINTER :: WC
TYPE(BOUNDARY_COORD_TYPE), POINTER :: BC
TYPE(BOUNDARY_PROP1_TYPE), POINTER :: B1

FX_ZZ=>M%SWORK1
FY_ZZ=>M%SWORK2
FZ_ZZ=>M%SWORK3
RHO_Z_P=>M%WORK_PAD

! Species face values

SPECIES_LOOP: DO N=1,N_TOTAL_SCALARS

   DO K=-1,M%KBP1+1
      DO J=-1,M%JBP1+1
         DO I=-1,M%IBP1+1
   RHO_Z_P(I,J,K) = RHOP(I,J,K)*ZZP(I,J,K,N)
         ENDDO
      ENDDO
   ENDDO

   ! Compute scalar face values

   FX_P(LBOUND(FX_ZZ,1):,LBOUND(FX_ZZ,2):,LBOUND(FX_ZZ,3):) => FX_ZZ(:,:,:,N)
   FY_P(LBOUND(FY_ZZ,1):,LBOUND(FY_ZZ,2):,LBOUND(FY_ZZ,3):) => FY_ZZ(:,:,:,N)
   FZ_P(LBOUND(FZ_ZZ,1):,LBOUND(FZ_ZZ,2):,LBOUND(FZ_ZZ,3):) => FZ_ZZ(:,:,:,N)
   CALL GET_SCALAR_FACE_VALUE(UU,RHO_Z_P,FX_P,0,M%IBAR,1,M%JBAR,1,M%KBAR,1,I_FLUX_LIMITER)
   CALL GET_SCALAR_FACE_VALUE(VV,RHO_Z_P,FY_P,1,M%IBAR,0,M%JBAR,1,M%KBAR,2,I_FLUX_LIMITER)
   CALL GET_SCALAR_FACE_VALUE(WW,RHO_Z_P,FZ_P,1,M%IBAR,1,M%JBAR,0,M%KBAR,3,I_FLUX_LIMITER)

   U_TEMP => U_WORK
   F_TEMP => F_WORK
   Z_TEMP => Z_WORK
   WALL_LOOP_2: DO IW=1,M%N_EXTERNAL_WALL_CELLS+M%N_INTERNAL_WALL_CELLS
      WC=>M%WALL(IW)
      IF (WC%BOUNDARY_TYPE==NULL_BOUNDARY) CYCLE WALL_LOOP_2
      BC=>M%BOUNDARY_COORD(WC%BC_INDEX)
      B1=>M%BOUNDARY_PROP1(WC%B1_INDEX)

      ! Overwrite first off-wall advective flux if flow is away from the wall and if the face is not also a wall cell

      OFF_WALL_IF_2: IF (WC%BOUNDARY_TYPE/=INTERPOLATED_BOUNDARY .AND. WC%BOUNDARY_TYPE/=OPEN_BOUNDARY) THEN

         OFF_WALL_SELECT_2: SELECT CASE(BC%IOR)
            CASE( 1) OFF_WALL_SELECT_2
               !      ghost          FX/UU(II+1)
               ! ///   II   ///  II+1  |  II+2  | ...
               !                       ^ WALL_INDEX(II+1,+1)
               IF ((UU(BC%II+1,BC%JJ,BC%KK)>0._EB) .AND. .NOT.(M%CELL(M%CELL_INDEX(BC%II+1,BC%JJ,BC%KK))%WALL_INDEX(+1)>0)) THEN
                  Z_TEMP(0:2,1,1) = (/RHO_Z_P(BC%II+1,BC%JJ,BC%KK),RHO_Z_P(BC%II+1:BC%II+2,BC%JJ,BC%KK)/)
                  U_TEMP(1,1,1) = UU(BC%II+1,BC%JJ,BC%KK)
                  CALL GET_SCALAR_FACE_VALUE(U_TEMP,Z_TEMP,F_TEMP,1,1,1,1,1,1,1,I_FLUX_LIMITER)
                  FX_ZZ(BC%II+1,BC%JJ,BC%KK,N) = F_TEMP(1,1,1)
               ENDIF
            CASE(-1) OFF_WALL_SELECT_2
               !            FX/UU(II-2)     ghost
               ! ... |  II-2  |  II-1  ///   II   ///
               !              ^ WALL_INDEX(II-1,-1)
               IF ((UU(BC%II-2,BC%JJ,BC%KK)<0._EB) .AND. .NOT.(M%CELL(M%CELL_INDEX(BC%II-1,BC%JJ,BC%KK))%WALL_INDEX(-1)>0)) THEN
                  Z_TEMP(1:3,1,1) = (/RHO_Z_P(BC%II-2:BC%II-1,BC%JJ,BC%KK),RHO_Z_P(BC%II-1,BC%JJ,BC%KK)/)
                  U_TEMP(1,1,1) = UU(BC%II-2,BC%JJ,BC%KK)
                  CALL GET_SCALAR_FACE_VALUE(U_TEMP,Z_TEMP,F_TEMP,1,1,1,1,1,1,1,I_FLUX_LIMITER)
                  FX_ZZ(BC%II-2,BC%JJ,BC%KK,N) = F_TEMP(1,1,1)
               ENDIF
            CASE( 2) OFF_WALL_SELECT_2
               IF ((VV(BC%II,BC%JJ+1,BC%KK)>0._EB) .AND. .NOT.(M%CELL(M%CELL_INDEX(BC%II,BC%JJ+1,BC%KK))%WALL_INDEX(+2)>0)) THEN
                  Z_TEMP(1,0:2,1) = (/RHO_Z_P(BC%II,BC%JJ+1,BC%KK),RHO_Z_P(BC%II,BC%JJ+1:BC%JJ+2,BC%KK)/)
                  U_TEMP(1,1,1) = VV(BC%II,BC%JJ+1,BC%KK)
                  CALL GET_SCALAR_FACE_VALUE(U_TEMP,Z_TEMP,F_TEMP,1,1,1,1,1,1,2,I_FLUX_LIMITER)
                  FY_ZZ(BC%II,BC%JJ+1,BC%KK,N) = F_TEMP(1,1,1)
               ENDIF
            CASE(-2) OFF_WALL_SELECT_2
               IF ((VV(BC%II,BC%JJ-2,BC%KK)<0._EB) .AND. .NOT.(M%CELL(M%CELL_INDEX(BC%II,BC%JJ-1,BC%KK))%WALL_INDEX(-2)>0)) THEN
                  Z_TEMP(1,1:3,1) = (/RHO_Z_P(BC%II,BC%JJ-2:BC%JJ-1,BC%KK),RHO_Z_P(BC%II,BC%JJ-1,BC%KK)/)
                  U_TEMP(1,1,1) = VV(BC%II,BC%JJ-2,BC%KK)
                  CALL GET_SCALAR_FACE_VALUE(U_TEMP,Z_TEMP,F_TEMP,1,1,1,1,1,1,2,I_FLUX_LIMITER)
                  FY_ZZ(BC%II,BC%JJ-2,BC%KK,N) = F_TEMP(1,1,1)
               ENDIF
            CASE( 3) OFF_WALL_SELECT_2
               IF ((WW(BC%II,BC%JJ,BC%KK+1)>0._EB) .AND. .NOT.(M%CELL(M%CELL_INDEX(BC%II,BC%JJ,BC%KK+1))%WALL_INDEX(+3)>0)) THEN
                  Z_TEMP(1,1,0:2) = (/RHO_Z_P(BC%II,BC%JJ,BC%KK+1),RHO_Z_P(BC%II,BC%JJ,BC%KK+1:BC%KK+2)/)
                  U_TEMP(1,1,1) = WW(BC%II,BC%JJ,BC%KK+1)
                  CALL GET_SCALAR_FACE_VALUE(U_TEMP,Z_TEMP,F_TEMP,1,1,1,1,1,1,3,I_FLUX_LIMITER)
                  FZ_ZZ(BC%II,BC%JJ,BC%KK+1,N) = F_TEMP(1,1,1)
               ENDIF
            CASE(-3) OFF_WALL_SELECT_2
               IF ((WW(BC%II,BC%JJ,BC%KK-2)<0._EB) .AND. .NOT.(M%CELL(M%CELL_INDEX(BC%II,BC%JJ,BC%KK-1))%WALL_INDEX(-3)>0)) THEN
                  Z_TEMP(1,1,1:3) = (/RHO_Z_P(BC%II,BC%JJ,BC%KK-2:BC%KK-1),RHO_Z_P(BC%II,BC%JJ,BC%KK-1)/)
                  U_TEMP(1,1,1) = WW(BC%II,BC%JJ,BC%KK-2)
                  CALL GET_SCALAR_FACE_VALUE(U_TEMP,Z_TEMP,F_TEMP,1,1,1,1,1,1,3,I_FLUX_LIMITER)
                  FZ_ZZ(BC%II,BC%JJ,BC%KK-2,N) = F_TEMP(1,1,1)
               ENDIF
         END SELECT OFF_WALL_SELECT_2

      ENDIF OFF_WALL_IF_2

   ENDDO WALL_LOOP_2

ENDDO SPECIES_LOOP

FACE_CORRECTION_IF: IF (FLUX_LIMITER_MW_CORRECTION) THEN

   ! Repeat the above for DENSITY

   RHO_RMW=>M%WORK_PAD

   DO K=-1,M%KBP1+1
      DO J=-1,M%JBP1+1
         DO I=-1,M%IBP1+1
            ZZ_GET(1:N_TRACKED_SPECIES) = ZZP(I,J,K,1:N_TRACKED_SPECIES)
            CALL GET_MOLECULAR_WEIGHT(ZZ_GET,MW_G)
            RHO_RMW(I,J,K) = RHOP(I,J,K)/MW_G
         ENDDO
      ENDDO
   ENDDO

   FX_P(LBOUND(FX_ZZ,1):,LBOUND(FX_ZZ,2):,LBOUND(FX_ZZ,3):) => FX_ZZ(:,:,:,0)
   FY_P(LBOUND(FY_ZZ,1):,LBOUND(FY_ZZ,2):,LBOUND(FY_ZZ,3):) => FY_ZZ(:,:,:,0)
   FZ_P(LBOUND(FZ_ZZ,1):,LBOUND(FZ_ZZ,2):,LBOUND(FZ_ZZ,3):) => FZ_ZZ(:,:,:,0)
   CALL GET_SCALAR_FACE_VALUE(UU,RHO_RMW,FX_P,0,M%IBAR,1,M%JBAR,1,M%KBAR,1,I_FLUX_LIMITER)
   CALL GET_SCALAR_FACE_VALUE(VV,RHO_RMW,FY_P,1,M%IBAR,0,M%JBAR,1,M%KBAR,2,I_FLUX_LIMITER)
   CALL GET_SCALAR_FACE_VALUE(WW,RHO_RMW,FZ_P,1,M%IBAR,1,M%JBAR,0,M%KBAR,3,I_FLUX_LIMITER)

   U_TEMP => U_WORK
   F_TEMP => F_WORK
   Z_TEMP => Z_WORK
   WALL_LOOP_3: DO IW=1,M%N_EXTERNAL_WALL_CELLS+M%N_INTERNAL_WALL_CELLS
      WC=>M%WALL(IW)
      IF (WC%BOUNDARY_TYPE==NULL_BOUNDARY) CYCLE WALL_LOOP_3
      BC=>M%BOUNDARY_COORD(WC%BC_INDEX)
      B1=>M%BOUNDARY_PROP1(WC%B1_INDEX)

      ! Overwrite first off-wall advective flux if flow is away from the wall and if the face is not also a wall cell

      OFF_WALL_IF_3: IF (WC%BOUNDARY_TYPE/=INTERPOLATED_BOUNDARY .AND. WC%BOUNDARY_TYPE/=OPEN_BOUNDARY) THEN

         OFF_WALL_SELECT_3: SELECT CASE(BC%IOR)
            CASE( 1) OFF_WALL_SELECT_3
               !      ghost          FX/UU(II+1)
               ! ///   II   ///  II+1  |  II+2  | ...
               !                       ^ WALL_INDEX(II+1,+1)
               IF ((UU(BC%II+1,BC%JJ,BC%KK)>0._EB) .AND. .NOT.(M%CELL(M%CELL_INDEX(BC%II+1,BC%JJ,BC%KK))%WALL_INDEX(+1)>0)) THEN
                  Z_TEMP(0:2,1,1) = (/RHO_Z_P(BC%II+1,BC%JJ,BC%KK),RHO_Z_P(BC%II+1:BC%II+2,BC%JJ,BC%KK)/)
                  U_TEMP(1,1,1) = UU(BC%II+1,BC%JJ,BC%KK)
                  CALL GET_SCALAR_FACE_VALUE(U_TEMP,Z_TEMP,F_TEMP,1,1,1,1,1,1,1,I_FLUX_LIMITER)
                  FX_ZZ(BC%II+1,BC%JJ,BC%KK,0) = F_TEMP(1,1,1)
               ENDIF
            CASE(-1) OFF_WALL_SELECT_3
               !            FX/UU(II-2)     ghost
               ! ... |  II-2  |  II-1  ///   II   ///
               !              ^ WALL_INDEX(II-1,-1)
               IF ((UU(BC%II-2,BC%JJ,BC%KK)<0._EB) .AND. .NOT.(M%CELL(M%CELL_INDEX(BC%II-1,BC%JJ,BC%KK))%WALL_INDEX(-1)>0)) THEN
                  Z_TEMP(1:3,1,1) = (/RHO_Z_P(BC%II-2:BC%II-1,BC%JJ,BC%KK),RHO_Z_P(BC%II-1,BC%JJ,BC%KK)/)
                  U_TEMP(1,1,1) = UU(BC%II-2,BC%JJ,BC%KK)
                  CALL GET_SCALAR_FACE_VALUE(U_TEMP,Z_TEMP,F_TEMP,1,1,1,1,1,1,1,I_FLUX_LIMITER)
                  FX_ZZ(BC%II-2,BC%JJ,BC%KK,0) = F_TEMP(1,1,1)
               ENDIF
            CASE( 2) OFF_WALL_SELECT_3
               IF ((VV(BC%II,BC%JJ+1,BC%KK)>0._EB) .AND. .NOT.(M%CELL(M%CELL_INDEX(BC%II,BC%JJ+1,BC%KK))%WALL_INDEX(+2)>0)) THEN
                  Z_TEMP(1,0:2,1) = (/RHO_Z_P(BC%II,BC%JJ+1,BC%KK),RHO_Z_P(BC%II,BC%JJ+1:BC%JJ+2,BC%KK)/)
                  U_TEMP(1,1,1) = VV(BC%II,BC%JJ+1,BC%KK)
                  CALL GET_SCALAR_FACE_VALUE(U_TEMP,Z_TEMP,F_TEMP,1,1,1,1,1,1,2,I_FLUX_LIMITER)
                  FY_ZZ(BC%II,BC%JJ+1,BC%KK,0) = F_TEMP(1,1,1)
               ENDIF
            CASE(-2) OFF_WALL_SELECT_3
               IF ((VV(BC%II,BC%JJ-2,BC%KK)<0._EB) .AND. .NOT.(M%CELL(M%CELL_INDEX(BC%II,BC%JJ-1,BC%KK))%WALL_INDEX(-2)>0)) THEN
                  Z_TEMP(1,1:3,1) = (/RHO_Z_P(BC%II,BC%JJ-2:BC%JJ-1,BC%KK),RHO_Z_P(BC%II,BC%JJ-1,BC%KK)/)
                  U_TEMP(1,1,1) = VV(BC%II,BC%JJ-2,BC%KK)
                  CALL GET_SCALAR_FACE_VALUE(U_TEMP,Z_TEMP,F_TEMP,1,1,1,1,1,1,2,I_FLUX_LIMITER)
                  FY_ZZ(BC%II,BC%JJ-2,BC%KK,0) = F_TEMP(1,1,1)
               ENDIF
            CASE( 3) OFF_WALL_SELECT_3
               IF ((WW(BC%II,BC%JJ,BC%KK+1)>0._EB) .AND. .NOT.(M%CELL(M%CELL_INDEX(BC%II,BC%JJ,BC%KK+1))%WALL_INDEX(+3)>0)) THEN
                  Z_TEMP(1,1,0:2) = (/RHO_Z_P(BC%II,BC%JJ,BC%KK+1),RHO_Z_P(BC%II,BC%JJ,BC%KK+1:BC%KK+2)/)
                  U_TEMP(1,1,1) = WW(BC%II,BC%JJ,BC%KK+1)
                  CALL GET_SCALAR_FACE_VALUE(U_TEMP,Z_TEMP,F_TEMP,1,1,1,1,1,1,3,I_FLUX_LIMITER)
                  FZ_ZZ(BC%II,BC%JJ,BC%KK+1,0) = F_TEMP(1,1,1)
               ENDIF
            CASE(-3) OFF_WALL_SELECT_3
               IF ((WW(BC%II,BC%JJ,BC%KK-2)<0._EB) .AND. .NOT.(M%CELL(M%CELL_INDEX(BC%II,BC%JJ,BC%KK-1))%WALL_INDEX(-3)>0)) THEN
                  Z_TEMP(1,1,1:3) = (/RHO_Z_P(BC%II,BC%JJ,BC%KK-2:BC%KK-1),RHO_Z_P(BC%II,BC%JJ,BC%KK-1)/)
                  U_TEMP(1,1,1) = WW(BC%II,BC%JJ,BC%KK-2)
                  CALL GET_SCALAR_FACE_VALUE(U_TEMP,Z_TEMP,F_TEMP,1,1,1,1,1,1,3,I_FLUX_LIMITER)
                  FZ_ZZ(BC%II,BC%JJ,BC%KK-2,0) = F_TEMP(1,1,1)
               ENDIF
         END SELECT OFF_WALL_SELECT_3

      ENDIF OFF_WALL_IF_3

   ENDDO WALL_LOOP_3

   ! Now correct the max face value of (RHO*ZZ) such that SUM(RHO*ZZ/MW)_FACE = RHO_FACE/MW_FACE
   ! (necessary condition to preserve isothermal flow)

   DO K=0,M%KBAR
      DO J=0,M%JBAR
         DO I=0,M%IBAR
   N=MAXLOC(FX_ZZ(I,J,K,1:N_TRACKED_SPECIES),1)
   MW_G = SPECIES_MIXTURE(N)%MW
   FX_ZZ(I,J,K,N) = MW_G*MAX( 0._EB, FX_ZZ(I,J,K,0) &
         - SUM(FX_ZZ(I,J,K,1:(N-1))/SPECIES_MIXTURE(1:(N-1))%MW) &
         - SUM(FX_ZZ(I,J,K,(N+1):N_TRACKED_SPECIES)/SPECIES_MIXTURE((N+1):N_TRACKED_SPECIES)%MW) )
   N=MAXLOC(FY_ZZ(I,J,K,1:N_TRACKED_SPECIES),1)
   MW_G = SPECIES_MIXTURE(N)%MW
   FY_ZZ(I,J,K,N) = MW_G*MAX( 0._EB, FY_ZZ(I,J,K,0) &
         - SUM(FY_ZZ(I,J,K,1:(N-1))/SPECIES_MIXTURE(1:(N-1))%MW) &
         - SUM(FY_ZZ(I,J,K,(N+1):N_TRACKED_SPECIES)/SPECIES_MIXTURE((N+1):N_TRACKED_SPECIES)%MW) )
   N=MAXLOC(FZ_ZZ(I,J,K,1:N_TRACKED_SPECIES),1)
   MW_G = SPECIES_MIXTURE(N)%MW
   FZ_ZZ(I,J,K,N) = MW_G*MAX( 0._EB, FZ_ZZ(I,J,K,0) &
         - SUM(FZ_ZZ(I,J,K,1:(N-1))/SPECIES_MIXTURE(1:(N-1))%MW) &
         - SUM(FZ_ZZ(I,J,K,(N+1):N_TRACKED_SPECIES)/SPECIES_MIXTURE((N+1):N_TRACKED_SPECIES)%MW) )
         ENDDO
      ENDDO
   ENDDO

ENDIF FACE_CORRECTION_IF

END SUBROUTINE SPECIES_ADVECTION_PART_1_NEW



SUBROUTINE SPECIES_ADVECTION_PART_2(N,U_DOT_DEL_RHO_Z)

INTEGER, INTENT(IN) :: N
REAL(EB), POINTER, DIMENSION(:,:,:) :: U_DOT_DEL_RHO_Z
REAL(EB), POINTER, DIMENSION(:,:,:,:) :: FX_ZZ,FY_ZZ,FZ_ZZ
REAL(EB) :: UN,DU_P,DU_M,DV_P,DV_M,DW_P,DW_M,DU
INTEGER :: IC,I,J,K,IW
TYPE(WALL_TYPE), POINTER :: WC
TYPE(BOUNDARY_COORD_TYPE), POINTER :: BC
TYPE(BOUNDARY_PROP1_TYPE), POINTER :: B1

FX_ZZ=>M%SWORK1
FY_ZZ=>M%SWORK2
FZ_ZZ=>M%SWORK3
U_DOT_DEL_RHO_Z=>M%WORK7 ; U_DOT_DEL_RHO_Z = 0._EB

WALL_LOOP: DO IW=1,M%N_EXTERNAL_WALL_CELLS+M%N_INTERNAL_WALL_CELLS

   WC=>M%WALL(IW)
   IF (WC%BOUNDARY_TYPE==NULL_BOUNDARY) CYCLE WALL_LOOP
   B1 => M%BOUNDARY_PROP1(WC%B1_INDEX)
   BC => M%BOUNDARY_COORD(WC%BC_INDEX)

   ! Correct flux terms at the boundary

   SELECT CASE(WC%BOUNDARY_TYPE)
      CASE DEFAULT
         IOR_SELECT: SELECT CASE(BC%IOR)
            CASE( 1); UN = UU(BC%II  ,BC%JJ  ,BC%KK  )
            CASE(-1); UN = UU(BC%II-1,BC%JJ  ,BC%KK  )
            CASE( 2); UN = VV(BC%II  ,BC%JJ  ,BC%KK  )
            CASE(-2); UN = VV(BC%II  ,BC%JJ-1,BC%KK  )
            CASE( 3); UN = WW(BC%II  ,BC%JJ  ,BC%KK  )
            CASE(-3); UN = WW(BC%II  ,BC%JJ  ,BC%KK-1)
         END SELECT IOR_SELECT
      CASE(SOLID_BOUNDARY)
         IF (PREDICTOR) UN = -SIGN(1._EB,REAL(BC%IOR,EB))*B1%U_NORMAL_S
         IF (CORRECTOR) UN = -SIGN(1._EB,REAL(BC%IOR,EB))*B1%U_NORMAL
      CASE(INTERPOLATED_BOUNDARY)
         UN = M%UVW_SAVE(IW)
   END SELECT

   DU = (B1%RHO_F*B1%ZZ_F(N) - RHOP(BC%IIG,BC%JJG,BC%KKG)*ZZP(BC%IIG,BC%JJG,BC%KKG,N))*UN
   U_DOT_DEL_RHO_Z(BC%IIG,BC%JJG,BC%KKG) = U_DOT_DEL_RHO_Z(BC%IIG,BC%JJG,BC%KKG) - SIGN(1._EB,REAL(BC%IOR,EB))*DU*B1%RDN

ENDDO WALL_LOOP

DO K=1,M%KBAR
   DO J=1,M%JBAR
      DO I=1,M%IBAR
IC = M%CELL_INDEX(I,J,K)
IF (M%CELL(IC)%SOLID) CYCLE
DU_P = 0._EB
DU_M = 0._EB
DV_P = 0._EB
DV_M = 0._EB
DW_P = 0._EB
DW_M = 0._EB
IF (M%CELL(IC)%WALL_INDEX( 1)==0) DU_P = (FX_ZZ(I,J,K,N)   - RHOP(I,J,K)*ZZP(I,J,K,N))*UU(I,J,K)
IF (M%CELL(IC)%WALL_INDEX(-1)==0) DU_M = (FX_ZZ(I-1,J,K,N) - RHOP(I,J,K)*ZZP(I,J,K,N))*UU(I-1,J,K)
IF (M%CELL(IC)%WALL_INDEX( 2)==0) DV_P = (FY_ZZ(I,J,K,N)   - RHOP(I,J,K)*ZZP(I,J,K,N))*VV(I,J,K)
IF (M%CELL(IC)%WALL_INDEX(-2)==0) DV_M = (FY_ZZ(I,J-1,K,N) - RHOP(I,J,K)*ZZP(I,J,K,N))*VV(I,J-1,K)
IF (M%CELL(IC)%WALL_INDEX( 3)==0) DW_P = (FZ_ZZ(I,J,K,N)   - RHOP(I,J,K)*ZZP(I,J,K,N))*WW(I,J,K)
IF (M%CELL(IC)%WALL_INDEX(-3)==0) DW_M = (FZ_ZZ(I,J,K-1,N) - RHOP(I,J,K)*ZZP(I,J,K,N))*WW(I,J,K-1)
U_DOT_DEL_RHO_Z(I,J,K) = U_DOT_DEL_RHO_Z(I,J,K) &
   + (DU_P-DU_M)*M%RDX(I) + (DV_P-DV_M)*M%RDY(J) + (DW_P-DW_M)*M%RDZ(K)
      ENDDO
   ENDDO
ENDDO

END SUBROUTINE SPECIES_ADVECTION_PART_2


SUBROUTINE MERGE_PRESSURE_ZONES

INTEGER :: IW,IPZ,IOPZ
TYPE(WALL_TYPE), POINTER :: WC
TYPE(BOUNDARY_COORD_TYPE), POINTER :: BC

DO IW=1,M%N_EXTERNAL_WALL_CELLS+M%N_INTERNAL_WALL_CELLS
   WC=>M%WALL(IW)
   IF (WC%BOUNDARY_TYPE/=NULL_BOUNDARY .AND. WC%BOUNDARY_TYPE/=OPEN_BOUNDARY .AND. WC%BOUNDARY_TYPE/=INTERPOLATED_BOUNDARY) CYCLE
   BC => M%BOUNDARY_COORD(WC%BC_INDEX)
   IF (M%CELL(M%CELL_INDEX(BC%IIG,BC%JJG,BC%KKG))%SOLID) CYCLE
   IPZ  = M%PRESSURE_ZONE(BC%IIG,BC%JJG,BC%KKG)
   IOPZ = M%PRESSURE_ZONE(BC%II,BC%JJ,BC%KK)
   IF (IW>M%N_EXTERNAL_WALL_CELLS .AND. IPZ/=IOPZ) THEN
      CONNECTED_ZONES(IOPZ,IPZ) = 1
      CONNECTED_ZONES(IPZ,IOPZ) = 1
   ENDIF
   IF (WC%BOUNDARY_TYPE==OPEN_BOUNDARY) THEN
      CONNECTED_ZONES(0,IPZ) = 1
      CONNECTED_ZONES(IPZ,0) = 1
   ELSEIF (WC%BOUNDARY_TYPE==INTERPOLATED_BOUNDARY) THEN
      CONNECTED_ZONES(IOPZ,IPZ) = 1
      CONNECTED_ZONES(IPZ,IOPZ) = 1
   ENDIF
ENDDO

END SUBROUTINE MERGE_PRESSURE_ZONES


SUBROUTINE PREDICT_NORMAL_VELOCITY(IW,T,DT)

USE MATH_FUNCTIONS, ONLY: EVALUATE_RAMP
INTEGER, INTENT(IN) :: IW
REAL(EB), INTENT(IN) :: T,DT
REAL(EB) :: TSI,TIME_RAMP_FACTOR,PROFILE_FACTOR
TYPE(VENTS_TYPE), POINTER :: VT
TYPE(SURFACE_TYPE), POINTER :: SF
TYPE(WALL_TYPE), POINTER :: WC
TYPE(BOUNDARY_COORD_TYPE), POINTER :: BC
TYPE(BOUNDARY_PROP1_TYPE), POINTER :: B1

WC => M%WALL(IW)
BC => M%BOUNDARY_COORD(WC%BC_INDEX)
B1 => M%BOUNDARY_PROP1(WC%B1_INDEX)
SF => SURFACE(WC%SURF_INDEX)

PREDICT_NORMALS: IF (PREDICTOR) THEN

   WALL_CELL_TYPE: SELECT CASE (WC%BOUNDARY_TYPE)

      CASE (NULL_BOUNDARY)

         B1%U_NORMAL_S = 0._EB

      CASE (SOLID_BOUNDARY)

         IF (SF%SPECIES_BC_INDEX==SPECIFIED_MASS_FLUX .OR. SF%SPECIES_BC_INDEX==INTERPOLATED_BC .OR. &
             B1%NODE_INDEX > 0 .OR. ANY(SF%LEAK_PATH>0)) EXIT WALL_CELL_TYPE

         IF (ABS(B1%T_IGN-T_BEGIN) < SPACING(B1%T_IGN) .AND. SF%RAMP(TIME_VELO)%INDEX>=1) THEN
            TSI = T + DT
         ELSE
            TSI = T + DT - B1%T_IGN
            IF (TSI<0._EB) THEN
               B1%U_NORMAL_S = 0._EB
               EXIT WALL_CELL_TYPE
            ENDIF
         ENDIF
         TIME_RAMP_FACTOR = EVALUATE_RAMP(TSI,SF%RAMP(TIME_VELO)%INDEX,TAU=SF%RAMP(TIME_VELO)%TAU)
         B1%U_NORMAL_S = TIME_RAMP_FACTOR*B1%U_NORMAL_0

         ! Special Cases
         NEUMANN_IF: IF (SF%SPECIFIED_NORMAL_GRADIENT) THEN
            SELECT CASE(BC%IOR)
               CASE( 1); B1%U_NORMAL_S =-(M%U(BC%IIG,BC%JJG,BC%KKG)   + SF%VEL_GRAD*B1%RDN)
               CASE(-1); B1%U_NORMAL_S = (M%U(BC%IIG-1,BC%JJG,BC%KKG) + SF%VEL_GRAD*B1%RDN)
               CASE( 2); B1%U_NORMAL_S =-(M%V(BC%IIG,BC%JJG,BC%KKG)   + SF%VEL_GRAD*B1%RDN)
               CASE(-2); B1%U_NORMAL_S = (M%V(BC%IIG,BC%JJG-1,BC%KKG) + SF%VEL_GRAD*B1%RDN)
               CASE( 3); B1%U_NORMAL_S =-(M%W(BC%IIG,BC%JJG,BC%KKG)   + SF%VEL_GRAD*B1%RDN)
               CASE(-3); B1%U_NORMAL_S = (M%W(BC%IIG,BC%JJG,BC%KKG-1) + SF%VEL_GRAD*B1%RDN)
            END SELECT
         ENDIF NEUMANN_IF
         IF (ABS(SURFACE(WC%SURF_INDEX)%MASS_FLUX_TOTAL)>=TWENTY_EPSILON_EB) B1%U_NORMAL_S = &
                                                                          B1%U_NORMAL_S*RHOA/B1%RHO_F
         VENT_IF: IF (WC%VENT_INDEX>0) THEN
            VT=>M%VENTS(WC%VENT_INDEX)
            IF (VT%N_EDDY>0) THEN ! Synthetic Eddy Method
               IF (SF%PROFILE/=0 .AND. ABS(SF%VEL)>TWENTY_EPSILON_EB) THEN
                  PROFILE_FACTOR = ABS(B1%U_NORMAL_0/SF%VEL)
               ELSE
                  PROFILE_FACTOR = 1._EB
               ENDIF
               SELECT CASE(BC%IOR)
                  CASE( 1); B1%U_NORMAL_S = B1%U_NORMAL_S - TIME_RAMP_FACTOR*VT%U_EDDY(BC%JJ,BC%KK)*PROFILE_FACTOR
                  CASE(-1); B1%U_NORMAL_S = B1%U_NORMAL_S + TIME_RAMP_FACTOR*VT%U_EDDY(BC%JJ,BC%KK)*PROFILE_FACTOR
                  CASE( 2); B1%U_NORMAL_S = B1%U_NORMAL_S - TIME_RAMP_FACTOR*VT%V_EDDY(BC%II,BC%KK)*PROFILE_FACTOR
                  CASE(-2); B1%U_NORMAL_S = B1%U_NORMAL_S + TIME_RAMP_FACTOR*VT%V_EDDY(BC%II,BC%KK)*PROFILE_FACTOR
                  CASE( 3); B1%U_NORMAL_S = B1%U_NORMAL_S - TIME_RAMP_FACTOR*VT%W_EDDY(BC%II,BC%JJ)*PROFILE_FACTOR
                  CASE(-3); B1%U_NORMAL_S = B1%U_NORMAL_S + TIME_RAMP_FACTOR*VT%W_EDDY(BC%II,BC%JJ)*PROFILE_FACTOR
               END SELECT
            ENDIF
         ENDIF VENT_IF

      CASE(OPEN_BOUNDARY,INTERPOLATED_BOUNDARY)
         SELECT CASE(BC%IOR)
            CASE( 1); B1%U_NORMAL_S = -M%U(BC%II,BC%JJ,BC%KK)
            CASE(-1); B1%U_NORMAL_S =  M%U(BC%II-1,BC%JJ,BC%KK)
            CASE( 2); B1%U_NORMAL_S = -M%V(BC%II,BC%JJ,BC%KK)
            CASE(-2); B1%U_NORMAL_S =  M%V(BC%II,BC%JJ-1,BC%KK)
            CASE( 3); B1%U_NORMAL_S = -M%W(BC%II,BC%JJ,BC%KK)
            CASE(-3); B1%U_NORMAL_S =  M%W(BC%II,BC%JJ,BC%KK-1)
         END SELECT

   END SELECT WALL_CELL_TYPE

   ! Calculate du/dt, dv/dt, dw/dt at external boundaries. DUNDT is only used for Neumann BCs.

   IF (IW<=M%N_EXTERNAL_WALL_CELLS) M%EXTERNAL_WALL(IW)%DUNDT = (B1%U_NORMAL_S-B1%U_NORMAL)/DT

ELSE PREDICT_NORMALS

   ! In the CORRECTOR step, the normal component of velocity, U_NORMAL, is the same as the predicted value, U_NORMAL_S.
   ! However, for species mass fluxes and HVAC, U_NORMAL is computed elsewhere (wall.f90).

   IF (WC%BOUNDARY_TYPE/=SOLID_BOUNDARY .OR. (SF%SPECIES_BC_INDEX/=SPECIFIED_MASS_FLUX .AND. &
       SF%SPECIES_BC_INDEX/=INTERPOLATED_BC .AND. B1%NODE_INDEX<=0 .AND. ALL(SF%LEAK_PATH<=0))) B1%U_NORMAL = B1%U_NORMAL_S

   ! Calculate du/dt, dv/dt, dw/dt at external boundaries. DUNDT is only used for Neumann BCs. Note the second-order RK formula.

   IF (IW<=M%N_EXTERNAL_WALL_CELLS) M%EXTERNAL_WALL(IW)%DUNDT = M%EXTERNAL_WALL(IW)%DUNDT + 2._EB*(B1%U_NORMAL-B1%U_NORMAL_S)/DT

ENDIF PREDICT_NORMALS

END SUBROUTINE PREDICT_NORMAL_VELOCITY


END SUBROUTINE DIVERGENCE_PART_1_KERNEL


!> \brief Add QR (radiation source term) to the divergence DP.
!> Used after DIVERGENCE_PART_1_KERNEL(SKIP_QR=.TRUE.) and a QR exchange.
!> \param M Mesh data structure
!> \param NM Mesh number

RECURSIVE SUBROUTINE DIVERGENCE_PART_1_ADD_QR_KERNEL(M,NM)

TYPE(MESH_TYPE), INTENT(INOUT), TARGET :: M
INTEGER, INTENT(IN) :: NM
REAL(EB), POINTER, DIMENSION(:,:,:) :: DP
INTEGER :: I,J,K

IF (SOLID_PHASE_ONLY) RETURN

SELECT CASE(PREDICTOR)
   CASE(.TRUE.)
      DP => M%DS
   CASE(.FALSE.)
      DP => M%D
END SELECT

SELECT CASE(CYLINDRICAL)
CASE(.FALSE.)
   DO K=1,M%KBAR
      DO J=1,M%JBAR
         DO I=1,M%IBAR
            DP(I,J,K) = DP(I,J,K) + M%QR(I,J,K)
         ENDDO
      ENDDO
   ENDDO
CASE(.TRUE.)
   DO K=1,M%KBAR
      DO J=1,M%JBAR
         DO I=1,M%IBAR
            DP(I,J,K) = DP(I,J,K) + M%QR(I,J,K)
         ENDDO
      ENDDO
   ENDDO
END SELECT

END SUBROUTINE DIVERGENCE_PART_1_ADD_QR_KERNEL


!> \brief Finish computing the divergence of the flow, D, and then compute its time derivative, DDDT
!> \param M Mesh data structure
!> \param DT Time step (s)
!> \param NM Mesh number

SUBROUTINE DIVERGENCE_PART_2_KERNEL(M,DT,NM)

USE COMPLEX_GEOMETRY, ONLY : CC_CGSC, CC_UNKZ, CC_SOLID, CC_CUTCFE
USE CC_PRESSURE_KERNELS, ONLY : ADD_CUTCELL_D_PBAR_DT, &
   ADD_LINKEDCELL_D_PBAR_DT
USE CC_PRESSURE, ONLY : GET_CUTCELL_DDDT
USE CC_VELOCITY, ONLY : GET_LINKED_VELOCITIES

TYPE(MESH_TYPE), INTENT(INOUT), TARGET :: M
INTEGER, INTENT(IN) :: NM
REAL(EB), INTENT(IN) :: DT
REAL(EB), POINTER, DIMENSION(:,:,:) :: DP,RTRM,DIV
REAL(EB) :: USUM_ADD(N_ZONE),UN_P
REAL(EB) :: RDT,P_EQ,SUM_P_PSUM,SUM_USUM,SUM_DSUM,SUM_PSUM
LOGICAL :: OPEN_ZONE
REAL(EB), POINTER, DIMENSION(:) :: D_PBAR_DT_P
REAL(EB), POINTER, DIMENSION(:,:) :: PBAR_P
INTEGER :: IW,IC,I,J,K,IPZ,IOPZ
TYPE(WALL_TYPE), POINTER :: WC
TYPE(BOUNDARY_COORD_TYPE), POINTER :: BC
TYPE(BOUNDARY_PROP1_TYPE), POINTER :: B1

IF (SOLID_PHASE_ONLY) RETURN
IF (PERIODIC_TEST==3) RETURN
IF (PERIODIC_TEST==4) RETURN

RDT = 1._EB/DT

SELECT CASE(PREDICTOR)
   CASE(.TRUE.)
      DP => M%DS
      PBAR_P => M%PBAR_S
   CASE(.FALSE.)
      DP => M%D
      PBAR_P => M%PBAR
END SELECT

M%R_PBAR = 1._EB/PBAR_P

RTRM => M%WORK1

! Adjust volume flows (USUM) of pressure ZONEs that are connected to equalize background pressure

USUM_ADD = 0._EB

DO IPZ=1,N_ZONE
   SUM_P_PSUM = PBAR_P(1,IPZ)*PSUM(IPZ)
   OPEN_ZONE  = .FALSE.
   SUM_USUM = USUM(IPZ)
   SUM_DSUM = DSUM(IPZ)
   SUM_PSUM = PSUM(IPZ)
   DO IOPZ=N_ZONE,0,-1
      IF (IOPZ==IPZ) CYCLE
      IF (CONNECTED_ZONES(IPZ,IOPZ)>0) THEN
         IF (IOPZ==0) THEN
            OPEN_ZONE = .TRUE.
         ELSE
            SUM_P_PSUM = SUM_P_PSUM + PBAR_P(1,IOPZ)*PSUM(IOPZ)
            SUM_USUM = SUM_USUM + USUM(IOPZ)
            SUM_DSUM = SUM_DSUM + DSUM(IOPZ)
            SUM_PSUM = SUM_PSUM + PSUM(IOPZ)
         ENDIF
      ENDIF
   ENDDO
   IF (OPEN_ZONE) THEN
      P_EQ          = M%P_0(1)
      USUM_ADD(IPZ) = PSUM(IPZ)*(PBAR_P(1,IPZ)-P_EQ)/PRESSURE_RELAX_TIME + DSUM(IPZ) - USUM(IPZ)
   ELSE
      P_EQ          = SUM_P_PSUM/SUM_PSUM
      USUM_ADD(IPZ) = PSUM(IPZ)*(PBAR_P(1,IPZ)-P_EQ)/PRESSURE_RELAX_TIME + DSUM(IPZ) - USUM(IPZ) - &
                      PSUM(IPZ)*(SUM_DSUM-SUM_USUM)/SUM_PSUM
   ENDIF
ENDDO

DO IPZ=1,N_ZONE
   USUM(IPZ) = USUM(IPZ) + USUM_ADD(IPZ)
ENDDO

! Compute dP/dt for each pressure ZONE

IF_PRESSURE_ZONES: IF (N_ZONE>0) THEN

   IF (PREDICTOR) D_PBAR_DT_P => M%D_PBAR_DT_S
   IF (CORRECTOR) D_PBAR_DT_P => M%D_PBAR_DT

   ! Compute change in background pressure

   DO IPZ=1,N_ZONE
      IF (ABS(PSUM(IPZ)) > TWENTY_EPSILON_EB) D_PBAR_DT_P(IPZ) = (DSUM(IPZ) - USUM(IPZ))/PSUM(IPZ)
      IF (CORRECTOR) P_ZONE(IPZ)%DPSTAR =  D_PBAR_DT_P(IPZ)
   ENDDO

   ! Add pressure derivative to divergence

   DO K=1,M%KBAR
      DO J=1,M%JBAR
         DO I=1,M%IBAR
            IPZ = M%PRESSURE_ZONE(I,J,K)
            IF (IPZ<1) CYCLE
            IF (M%CELL(M%CELL_INDEX(I,J,K))%SOLID) CYCLE
            IF (CC_IBM) THEN
               IF (M%CCVAR(I,J,K,CC_CGSC) == CC_SOLID) THEN
                  CYCLE
               ELSEIF(M%CCVAR(I,J,K,CC_CGSC) == CC_CUTCFE) THEN
                  CALL ADD_CUTCELL_D_PBAR_DT(M,I,J,K, &
                     PBAR_P(K,IPZ), &
                     D_PBAR_DT_P(IPZ)); CYCLE
               ELSEIF(M%CCVAR(I,J,K,CC_UNKZ) > 0) THEN
                  CALL ADD_LINKEDCELL_D_PBAR_DT(M,I,J,K, &
                     PBAR_P(K,IPZ), &
                     D_PBAR_DT_P(IPZ), &
                     RTRM(I,J,K),DP(I,J,K)); CYCLE
               ENDIF
            ENDIF
            DP(I,J,K) = DP(I,J,K) - (M%R_PBAR(K,IPZ)-RTRM(I,J,K))*D_PBAR_DT_P(IPZ)
         ENDDO
      ENDDO
   ENDDO

ENDIF IF_PRESSURE_ZONES

! Zero out divergence in solid cells

SOLID_LOOP: DO IC=1,CELL_COUNT(NM)
   IF (.NOT.M%CELL(IC)%SOLID) CYCLE SOLID_LOOP
   I = M%CELL(IC)%I
   J = M%CELL(IC)%J
   K = M%CELL(IC)%K
   DP(I,J,K) = 0._EB
ENDDO SOLID_LOOP

! Zero out CC_IBM solid cells:
IF (CC_IBM) THEN
   DO K=1,M%KBAR
      DO J=1,M%JBAR
         DO I=1,M%IBAR
            IF (M%CCVAR(I,J,K,CC_CGSC) /= CC_SOLID) CYCLE
            DP(I,J,K) = 0._EB
         ENDDO
      ENDDO
   ENDDO
   CALL GET_LINKED_VELOCITIES(NM,CORRECTOR,CMP_FLG=.FALSE.)
ENDIF

! Specify divergence in boundary cells to account for volume being generated at the walls

BC_LOOP: DO IW=1,M%N_EXTERNAL_WALL_CELLS+M%N_INTERNAL_WALL_CELLS
   WC => M%WALL(IW)
   IF (WC%BOUNDARY_TYPE==NULL_BOUNDARY) CYCLE BC_LOOP
   BC=>M%BOUNDARY_COORD(WC%BC_INDEX)
   SELECT CASE (WC%BOUNDARY_TYPE)
      CASE (SOLID_BOUNDARY)
         IF (.NOT.M%CELL(M%CELL_INDEX(BC%II,BC%JJ,BC%KK))%SOLID) CYCLE BC_LOOP
         B1 => M%BOUNDARY_PROP1(WC%BC_INDEX)
         IF (PREDICTOR) THEN
            UN_P = B1%U_NORMAL_S
         ELSE
            UN_P = B1%U_NORMAL
         ENDIF
         SELECT CASE(BC%IOR)
            CASE( 1)
               DP(BC%II,BC%JJ,BC%KK) = DP(BC%II,BC%JJ,BC%KK) - UN_P*M%RDX(BC%II)*M%RRN(BC%II)*M%R(BC%II)
            CASE(-1)
               DP(BC%II,BC%JJ,BC%KK) = DP(BC%II,BC%JJ,BC%KK) - UN_P*M%RDX(BC%II)*M%RRN(BC%II)*M%R(BC%II-1)
            CASE( 2)
               DP(BC%II,BC%JJ,BC%KK) = DP(BC%II,BC%JJ,BC%KK) - UN_P*M%RDY(BC%JJ)
            CASE(-2)
               DP(BC%II,BC%JJ,BC%KK) = DP(BC%II,BC%JJ,BC%KK) - UN_P*M%RDY(BC%JJ)
            CASE( 3)
               DP(BC%II,BC%JJ,BC%KK) = DP(BC%II,BC%JJ,BC%KK) - UN_P*M%RDZ(BC%KK)
            CASE(-3)
               DP(BC%II,BC%JJ,BC%KK) = DP(BC%II,BC%JJ,BC%KK) - UN_P*M%RDZ(BC%KK)
         END SELECT
      CASE (OPEN_BOUNDARY,MIRROR_BOUNDARY,INTERPOLATED_BOUNDARY)
         DP(BC%II,BC%JJ,BC%KK) = DP(BC%IIG,BC%JJG,BC%KKG)
   END SELECT
ENDDO BC_LOOP

! Compute time derivative of the divergence, dD/dt

DIV=>M%WORK1

IF (PREDICTOR) THEN
   DO K = 1,M%KBAR
      DO J = 1,M%JBAR
         DO I = 1,M%IBAR
            DIV(I,J,K) = (M%R(I)*M%U(I,J,K)-M%R(I-1)*M%U(I-1,J,K))*M%RDX(I)*M%RRN(I) + (M%V(I,J,K)-M%V(I,J-1,K))*M%RDY(J) + &
                         (M%W(I,J,K)-M%W(I,J,K-1))*M%RDZ(K)
         ENDDO
      ENDDO
   ENDDO
   M%DDDT = (DP-DIV)*RDT
ELSEIF (CORRECTOR) THEN
   DO K = 1,M%KBAR
      DO J = 1,M%JBAR
         DO I = 1,M%IBAR
            DIV(I,J,K) = (M%R(I)*M%U(I,J,K) -M%R(I-1)*M%U(I-1,J,K)) *M%RDX(I)*M%RRN(I) + (M%V(I,J,K)- M%V(I,J-1,K)) *M%RDY(J) + &
                         (M%W(I,J,K) -M%W(I,J,K-1)) *M%RDZ(K) &
                       + (M%R(I)*M%US(I,J,K)-M%R(I-1)*M%US(I-1,J,K))*M%RDX(I)*M%RRN(I) + (M%VS(I,J,K)-M%VS(I,J-1,K))*M%RDY(J) + &
                         (M%WS(I,J,K)-M%WS(I,J,K-1))*M%RDZ(K)
         ENDDO
      ENDDO
   ENDDO
   M%DDDT = (2._EB*DP-DIV)*RDT
ENDIF

IF(CC_IBM) CALL GET_CUTCELL_DDDT(DT,NM)

END SUBROUTINE DIVERGENCE_PART_2_KERNEL


!> \brief Preprocessing for DIVERGENCE_PART_2 block decomposition.
!> Computes zone operations (USUM_ADD, D_PBAR_DT_P) and R_PBAR.
!> Must be called sequentially per mesh BEFORE block kernel dispatch.
!> \param M Mesh data structure
!> \param DT Time step (s)
!> \param NM Mesh number

RECURSIVE SUBROUTINE DIVERGENCE_PART_2_PREPROCESSING(M,DT,NM)

USE COMPLEX_GEOMETRY, ONLY : CC_CGSC, CC_UNKZ, CC_SOLID, CC_CUTCFE
USE CC_VELOCITY, ONLY : GET_LINKED_VELOCITIES

TYPE(MESH_TYPE), INTENT(INOUT), TARGET :: M
INTEGER, INTENT(IN) :: NM
REAL(EB), INTENT(IN) :: DT
REAL(EB) :: USUM_ADD(N_ZONE),RDT,P_EQ,SUM_P_PSUM,SUM_USUM,SUM_DSUM,SUM_PSUM
LOGICAL :: OPEN_ZONE
REAL(EB), POINTER, DIMENSION(:) :: D_PBAR_DT_P
REAL(EB), POINTER, DIMENSION(:,:) :: PBAR_P
INTEGER :: IPZ,IOPZ

IF (SOLID_PHASE_ONLY) RETURN
IF (PERIODIC_TEST==3) RETURN
IF (PERIODIC_TEST==4) RETURN

RDT = 1._EB/DT

SELECT CASE(PREDICTOR)
   CASE(.TRUE.)
      PBAR_P => M%PBAR_S
   CASE(.FALSE.)
      PBAR_P => M%PBAR
END SELECT

M%R_PBAR = 1._EB/PBAR_P

! Adjust volume flows (USUM) of pressure ZONEs that are connected to equalize background pressure

USUM_ADD = 0._EB

DO IPZ=1,N_ZONE
   SUM_P_PSUM = PBAR_P(1,IPZ)*PSUM(IPZ)
   OPEN_ZONE  = .FALSE.
   SUM_USUM = USUM(IPZ)
   SUM_DSUM = DSUM(IPZ)
   SUM_PSUM = PSUM(IPZ)
   DO IOPZ=N_ZONE,0,-1
      IF (IOPZ==IPZ) CYCLE
      IF (CONNECTED_ZONES(IPZ,IOPZ)>0) THEN
         IF (IOPZ==0) THEN
            OPEN_ZONE = .TRUE.
         ELSE
            SUM_P_PSUM = SUM_P_PSUM + PBAR_P(1,IOPZ)*PSUM(IOPZ)
            SUM_USUM = SUM_USUM + USUM(IOPZ)
            SUM_DSUM = SUM_DSUM + DSUM(IOPZ)
            SUM_PSUM = SUM_PSUM + PSUM(IOPZ)
         ENDIF
      ENDIF
   ENDDO
   IF (OPEN_ZONE) THEN
      P_EQ          = M%P_0(1)
      USUM_ADD(IPZ) = PSUM(IPZ)*(PBAR_P(1,IPZ)-P_EQ)/PRESSURE_RELAX_TIME + DSUM(IPZ) - USUM(IPZ)
   ELSE
      P_EQ          = SUM_P_PSUM/SUM_PSUM
      USUM_ADD(IPZ) = PSUM(IPZ)*(PBAR_P(1,IPZ)-P_EQ)/PRESSURE_RELAX_TIME + DSUM(IPZ) - USUM(IPZ) - &
                      PSUM(IPZ)*(SUM_DSUM-SUM_USUM)/SUM_PSUM
   ENDIF
ENDDO

DO IPZ=1,N_ZONE
   USUM(IPZ) = USUM(IPZ) + USUM_ADD(IPZ)
ENDDO

! Compute dP/dt for each pressure ZONE

IF (N_ZONE>0) THEN

   IF (PREDICTOR) D_PBAR_DT_P => M%D_PBAR_DT_S
   IF (CORRECTOR) D_PBAR_DT_P => M%D_PBAR_DT

   DO IPZ=1,N_ZONE
      IF (ABS(PSUM(IPZ)) > TWENTY_EPSILON_EB) D_PBAR_DT_P(IPZ) = (DSUM(IPZ) - USUM(IPZ))/PSUM(IPZ)
      IF (CORRECTOR) P_ZONE(IPZ)%DPSTAR =  D_PBAR_DT_P(IPZ)
   ENDDO

ENDIF

! CC_IBM: compute linked velocities
IF (CC_IBM) CALL GET_LINKED_VELOCITIES(NM,CORRECTOR,CMP_FLG=.FALSE.)

END SUBROUTINE DIVERGENCE_PART_2_PREPROCESSING


!> \brief Block kernel for DIVERGENCE_PART_2 — processes K-range [K1,K2].
!> Requires DIVERGENCE_PART_2_PREPROCESSING to have been called first.
!> Computes pressure zone DP contribution, solid cell zeroing, BC_LOOP,
!> DIV computation, and DDDT for the given K-range.
!> \param M Mesh data structure
!> \param DT Time step (s)
!> \param NM Mesh number
!> \param K1 K-range start (1-based inclusive)
!> \param K2 K-range end (1-based inclusive)

RECURSIVE SUBROUTINE DIVERGENCE_PART_2_BLOCK_KERNEL(M,DT,NM,K1,K2)

USE COMPLEX_GEOMETRY, ONLY : CC_CGSC, CC_UNKZ, CC_SOLID, CC_CUTCFE
USE CC_PRESSURE_KERNELS, ONLY : ADD_CUTCELL_D_PBAR_DT, &
   ADD_LINKEDCELL_D_PBAR_DT

TYPE(MESH_TYPE), INTENT(INOUT), TARGET :: M
INTEGER, INTENT(IN) :: NM,K1,K2
REAL(EB), INTENT(IN) :: DT
REAL(EB), POINTER, DIMENSION(:,:,:) :: DP,RTRM,DIV
REAL(EB) :: RDT,UN_P
REAL(EB), POINTER, DIMENSION(:) :: D_PBAR_DT_P
REAL(EB), POINTER, DIMENSION(:,:) :: PBAR_P
INTEGER :: IW,IC,I,J,K,IPZ,K_MIN
TYPE(WALL_TYPE), POINTER :: WC
TYPE(BOUNDARY_COORD_TYPE), POINTER :: BC
TYPE(BOUNDARY_PROP1_TYPE), POINTER :: B1

IF (SOLID_PHASE_ONLY) RETURN
IF (PERIODIC_TEST==3) RETURN
IF (PERIODIC_TEST==4) RETURN

RDT = 1._EB/DT

SELECT CASE(PREDICTOR)
   CASE(.TRUE.)
      DP => M%DS
      PBAR_P => M%PBAR_S
   CASE(.FALSE.)
      DP => M%D
      PBAR_P => M%PBAR
END SELECT

RTRM => M%WORK1

! Add pressure derivative to divergence (K-restricted)

IF (N_ZONE>0) THEN

   IF (PREDICTOR) D_PBAR_DT_P => M%D_PBAR_DT_S
   IF (CORRECTOR) D_PBAR_DT_P => M%D_PBAR_DT

   DO K=K1,K2
      DO J=1,M%JBAR
         DO I=1,M%IBAR
            IPZ = M%PRESSURE_ZONE(I,J,K)
            IF (IPZ<1) CYCLE
            IF (M%CELL(M%CELL_INDEX(I,J,K))%SOLID) CYCLE
            DP(I,J,K) = DP(I,J,K) - (M%R_PBAR(K,IPZ)-RTRM(I,J,K))*D_PBAR_DT_P(IPZ)
         ENDDO
      ENDDO
   ENDDO

ENDIF

! Zero out divergence in solid cells (K-restricted)

DO K=K1,K2
   DO J=1,M%JBAR
      DO I=1,M%IBAR
         IC = M%CELL_INDEX(I,J,K)
         IF (M%CELL(IC)%SOLID) DP(I,J,K) = 0._EB
      ENDDO
   ENDDO
ENDDO

! Specify divergence in boundary cells to account for volume being generated at the walls (K-filtered)
! First block includes K=0 ghost cells; last block includes K=KBP1 ghost cells.

K_MIN = MERGE(0, K1, K1==1)

BC_LOOP: DO IW=1,M%N_EXTERNAL_WALL_CELLS+M%N_INTERNAL_WALL_CELLS
   WC => M%WALL(IW)
   IF (WC%BOUNDARY_TYPE==NULL_BOUNDARY) CYCLE BC_LOOP
   BC=>M%BOUNDARY_COORD(WC%BC_INDEX)

   ! K-filter: skip wall cells outside this block's range
   IF (BC%KK < K_MIN .OR. BC%KK > K2) CYCLE BC_LOOP
   ! Also skip KBP1 ghost cells unless this is the last block
   IF (BC%KK > M%KBAR .AND. K2 < M%KBAR) CYCLE BC_LOOP

   SELECT CASE (WC%BOUNDARY_TYPE)
      CASE (SOLID_BOUNDARY)
         IF (.NOT.M%CELL(M%CELL_INDEX(BC%II,BC%JJ,BC%KK))%SOLID) CYCLE BC_LOOP
         B1 => M%BOUNDARY_PROP1(WC%BC_INDEX)
         IF (PREDICTOR) THEN
            UN_P = B1%U_NORMAL_S
         ELSE
            UN_P = B1%U_NORMAL
         ENDIF
         SELECT CASE(BC%IOR)
            CASE( 1)
               DP(BC%II,BC%JJ,BC%KK) = DP(BC%II,BC%JJ,BC%KK) - UN_P*M%RDX(BC%II)*M%RRN(BC%II)*M%R(BC%II)
            CASE(-1)
               DP(BC%II,BC%JJ,BC%KK) = DP(BC%II,BC%JJ,BC%KK) - UN_P*M%RDX(BC%II)*M%RRN(BC%II)*M%R(BC%II-1)
            CASE( 2)
               DP(BC%II,BC%JJ,BC%KK) = DP(BC%II,BC%JJ,BC%KK) - UN_P*M%RDY(BC%JJ)
            CASE(-2)
               DP(BC%II,BC%JJ,BC%KK) = DP(BC%II,BC%JJ,BC%KK) - UN_P*M%RDY(BC%JJ)
            CASE( 3)
               DP(BC%II,BC%JJ,BC%KK) = DP(BC%II,BC%JJ,BC%KK) - UN_P*M%RDZ(BC%KK)
            CASE(-3)
               DP(BC%II,BC%JJ,BC%KK) = DP(BC%II,BC%JJ,BC%KK) - UN_P*M%RDZ(BC%KK)
         END SELECT
      CASE (OPEN_BOUNDARY,MIRROR_BOUNDARY,INTERPOLATED_BOUNDARY)
         DP(BC%II,BC%JJ,BC%KK) = DP(BC%IIG,BC%JJG,BC%KKG)
   END SELECT
ENDDO BC_LOOP

! Compute time derivative of the divergence, dD/dt (K-restricted)

DIV=>M%WORK1

IF (PREDICTOR) THEN
   DO K = K1,K2
      DO J = 1,M%JBAR
         DO I = 1,M%IBAR
            DIV(I,J,K) = (M%R(I)*M%U(I,J,K)-M%R(I-1)*M%U(I-1,J,K))*M%RDX(I)*M%RRN(I) + (M%V(I,J,K)-M%V(I,J-1,K))*M%RDY(J) + &
                         (M%W(I,J,K)-M%W(I,J,K-1))*M%RDZ(K)
         ENDDO
      ENDDO
   ENDDO
   DO K = K1,K2
      DO J = 1,M%JBAR
         DO I = 1,M%IBAR
            M%DDDT(I,J,K) = (DP(I,J,K)-DIV(I,J,K))*RDT
         ENDDO
      ENDDO
   ENDDO
ELSEIF (CORRECTOR) THEN
   DO K = K1,K2
      DO J = 1,M%JBAR
         DO I = 1,M%IBAR
            DIV(I,J,K) = (M%R(I)*M%U(I,J,K) -M%R(I-1)*M%U(I-1,J,K)) *M%RDX(I)*M%RRN(I) + (M%V(I,J,K)- M%V(I,J-1,K)) *M%RDY(J) + &
                         (M%W(I,J,K) -M%W(I,J,K-1)) *M%RDZ(K) &
                       + (M%R(I)*M%US(I,J,K)-M%R(I-1)*M%US(I-1,J,K))*M%RDX(I)*M%RRN(I) + (M%VS(I,J,K)-M%VS(I,J-1,K))*M%RDY(J) + &
                         (M%WS(I,J,K)-M%WS(I,J,K-1))*M%RDZ(K)
         ENDDO
      ENDDO
   ENDDO
   DO K = K1,K2
      DO J = 1,M%JBAR
         DO I = 1,M%IBAR
            M%DDDT(I,J,K) = (2._EB*DP(I,J,K)-DIV(I,J,K))*RDT
         ENDDO
      ENDDO
   ENDDO
ENDIF

END SUBROUTINE DIVERGENCE_PART_2_BLOCK_KERNEL



RECURSIVE SUBROUTINE CHECK_DIVERGENCE_KERNEL(M)

! Computes maximum velocity divergence

TYPE(MESH_TYPE), INTENT(INOUT), TARGET :: M
INTEGER  :: I,J,K
REAL(EB) :: DIV,RES
REAL(EB), POINTER, DIMENSION(:,:,:) :: UU,VV,WW,DP

IF (PREDICTOR) THEN
   UU=>M%US
   VV=>M%VS
   WW=>M%WS
   DP=>M%DS
ELSEIF (CORRECTOR) THEN
   UU=>M%U
   VV=>M%V
   WW=>M%W
   DP=>M%D
ENDIF

IF(STORE_CARTESIAN_DIVERGENCE) M%CARTVELDIV = DP

M%RESMAX = 0._EB
M%DIVMX  = -10000._EB
M%DIVMN  =  10000._EB
M%IMX    = 0
M%JMX    = 0
M%KMX    = 0

DO K=1,M%KBAR
   DO J=1,M%JBAR
      LOOP1: DO I=1,M%IBAR
         IF (M%CELL(M%CELL_INDEX(I,J,K))%SOLID) CYCLE LOOP1
         SELECT CASE(CYLINDRICAL)
            CASE(.FALSE.)
               DIV = (UU(I,J,K)-UU(I-1,J,K))*M%RDX(I) + &
                     (VV(I,J,K)-VV(I,J-1,K))*M%RDY(J) + &
                     (WW(I,J,K)-WW(I,J,K-1))*M%RDZ(K)
            CASE(.TRUE.)
               DIV = (M%R(I)*UU(I,J,K)-M%R(I-1)*UU(I-1,J,K))*M%RDX(I)*M%RRN(I) +  &
                     (WW(I,J,K)-WW(I,J,K-1))*M%RDZ(K)
         END SELECT
         IF(STORE_CARTESIAN_DIVERGENCE) M%CARTVELDIV(I,J,K) = DIV
         RES = ABS(DIV-DP(I,J,K))
         IF (ABS(RES)>=M%RESMAX) THEN
            M%RESMAX = ABS(RES)
            M%IRM=I
            M%JRM=J
            M%KRM=K
         ENDIF
         M%RESMAX = MAX(RES,M%RESMAX)
         IF (DIV>=M%DIVMX) THEN
            M%DIVMX = DIV
            M%IMX=I
            M%JMX=J
            M%KMX=K
         ENDIF
         IF (DIV<M%DIVMN) THEN
            M%DIVMN = DIV
            M%IMN=I
            M%JMN=J
            M%KMN=K
         ENDIF
      ENDDO LOOP1
   ENDDO
ENDDO

END SUBROUTINE CHECK_DIVERGENCE_KERNEL


END MODULE DIVG_KERNELS
