!> \brief Divergence calculations

MODULE DIVG

USE PRECISION_PARAMETERS
USE GLOBAL_CONSTANTS
USE MESH_POINTERS
USE COMP_FUNCTIONS, ONLY: CURRENT_TIME

IMPLICIT NONE (TYPE,EXTERNAL)
PRIVATE

PUBLIC DIVERGENCE_PART_1,DIVERGENCE_PART_2,CHECK_DIVERGENCE

CONTAINS

!> \brief Compute contributions to the divergence term
!> \param T Time (s)
!> \param DT Time step (s)
!> \param NM Mesh number

SUBROUTINE DIVERGENCE_PART_1(T,DT,NM)

USE DIVG_KERNELS, ONLY: DIVERGENCE_PART_1_KERNEL

INTEGER, INTENT(IN) :: NM
REAL(EB), INTENT(IN) :: T,DT
REAL(EB) :: TNOW

TNOW=CURRENT_TIME()

CALL DIVERGENCE_PART_1_KERNEL(MESHES(NM),T,DT,NM)

T_USED(2)=T_USED(2)+CURRENT_TIME()-TNOW

END SUBROUTINE DIVERGENCE_PART_1


!> \brief Finish computing the divergence of the flow, D, and then compute its time derivative, DDDT
!> \param DT Time step (s)
!> \param NM Mesh number

SUBROUTINE DIVERGENCE_PART_2(DT,NM)

USE DIVG_KERNELS, ONLY: DIVERGENCE_PART_2_KERNEL

INTEGER, INTENT(IN) :: NM
REAL(EB), INTENT(IN) :: DT
REAL(EB) :: TNOW

TNOW=CURRENT_TIME()

CALL DIVERGENCE_PART_2_KERNEL(MESHES(NM),DT,NM)

T_USED(2)=T_USED(2)+CURRENT_TIME()-TNOW

END SUBROUTINE DIVERGENCE_PART_2


SUBROUTINE CHECK_DIVERGENCE(NM)

USE DIVG_KERNELS, ONLY: CHECK_DIVERGENCE_KERNEL

INTEGER, INTENT(IN) :: NM
REAL(EB) :: TNOW

TNOW=CURRENT_TIME()

CALL CHECK_DIVERGENCE_KERNEL(MESHES(NM))

T_USED(2)=T_USED(2)+CURRENT_TIME()-TNOW

END SUBROUTINE CHECK_DIVERGENCE


END MODULE DIVG
