!> \brief Routines for computing combustion

MODULE FIRE

USE PRECISION_PARAMETERS
USE GLOBAL_CONSTANTS
USE MESH_POINTERS
USE COMP_FUNCTIONS, ONLY: CURRENT_TIME
USE SOOT_ROUTINES, ONLY: SOOT_SURFACE_OXIDATION
USE FIRE_KERNELS, ONLY: COMBUSTION_MODEL,CHECK_REACTION,GET_FLAME_TEMPERATURE, &
                        CONDENSATION_EVAPORATION_KERNEL

IMPLICIT NONE (TYPE,EXTERNAL)


PRIVATE

REAL(EB) :: T_CHEM_ODE, T_CHEM_COMM


LOGICAL :: COMBUSTION_INIT=.FALSE.
!INTEGER :: I0,J0,K0, NM0

! Variables needed for chemistry load distribution
REAL(EB), ALLOCATABLE, DIMENSION(:,:) :: REALS_TO_SEND_ARRAY, REALS_TO_RECV_ARRAY, RESULTS_TO_SEND_ARRAY, &
                                       RESULTS_TO_RECV_ARRAY
INTEGER, ALLOCATABLE, DIMENSION(:) :: NCELLS_TO_SEND_ARRAY, NCELLS_TO_RECV_ARRAY, SEND_DISPS, REVC_DISPS, &
                                      INTEGERS_TEST_ARRAY, NEW_INDEX, REV_NEW_INDEX, CHEM_SEQ_ARR, &
                                      NCHEM_ACTIVE_CELLS_AND_CC_RANK_WISE
INTEGER :: NVAR_TO_SEND
INTEGER :: NVAR_TO_RECEIVE


PUBLIC COMBUSTION_LOAD_BALANCED,COMBUSTION_BC,CONDENSATION_EVAPORATION,GET_FLAME_TEMPERATURE,COMBUSTION_GENERAL_KERNEL

CONTAINS

SUBROUTINE COMBUSTION_LOAD_BALANCED(T,DT)

USE SOOT_ROUTINES, ONLY: SOOT_SURFACE_OXIDATION
USE COMP_FUNCTIONS, ONLY: CURRENT_TIME
USE CHEMCONS, ONLY: CVODE_WARNING_CELLS,INIT_CVODE_WARN_MESSAGES
REAL(EB), INTENT(IN) :: T,DT
INTEGER :: NM,ICC,JCC
REAL(EB) :: TNOW

TNOW=CURRENT_TIME()
T_CHEM_ODE = 0._EB ! Zero out time taken in chem.f90 for this call to COMBUSTION
T_CHEM_COMM = 0._EB ! Chemistry load distribution communication time


! Set CVODES options
IF (.NOT. COMBUSTION_INIT) THEN
   COMBUSTION_INIT = .TRUE.
   NVAR_TO_SEND = N_TRACKED_SPECIES +7 ! NS, TEMP, RHO, PRES, MU, DELTA, VOL, IGN_ZN
   NVAR_TO_RECEIVE = N_TRACKED_SPECIES +4 ! NS, Q_OUT, MIX_TIME_OUT, CHI_R_OUT, CHEM_SUBIT_TMP_OUT
   CALL INIT_CVODE_WARN_MESSAGES()
ENDIF

DO NM=LOWER_MESH_INDEX,UPPER_MESH_INDEX
   CALL POINT_TO_MESH(NM)
   Q     = 0._EB
   CHI_R = 0._EB
   CVODE_WARNING_CELLS = 0
   IF (CC_IBM) THEN
      DO ICC=1,MESHES(NM)%N_CUTCELL_MESH
         DO JCC=1,CUT_CELL(ICC)%NCELL
            CUT_CELL(ICC)%Q(JCC)=0._EB
         ENDDO
      ENDDO
   ENDIF
ENDDO

IF (N_REACTIONS==0) RETURN

!Call combustion ODE solver
CALL COMBUSTION_GENERAL_LOAD_BALANCED(T,DT)

DO NM=LOWER_MESH_INDEX,UPPER_MESH_INDEX
   CALL POINT_TO_MESH(NM)
   ! Soot oxidation routine
   IF (DEPOSITION .AND. SOOT_OXIDATION) CALL SOOT_SURFACE_OXIDATION(DT,NM)
ENDDO

T_USED(10)=T_USED(10)+CURRENT_TIME()-TNOW-T_CHEM_ODE -T_CHEM_COMM!subract off CHEM time so FIRE time doesn't double count
T_USED(11)=T_USED(11)+T_CHEM_COMM
T_USED(16)=T_USED(16)+T_CHEM_ODE

END SUBROUTINE COMBUSTION_LOAD_BALANCED


SUBROUTINE COMBUSTION_GENERAL_LOAD_BALANCED(T,DT)

! Generic combustion routine for multi-step reactions
USE MPI_F08
!$ USE OMP_LIB
USE PHYSICAL_FUNCTIONS, ONLY: GET_SPECIFIC_GAS_CONSTANT,GET_MASS_FRACTION_ALL,GET_SPECIFIC_HEAT,GET_MOLECULAR_WEIGHT, &
                              GET_SENSIBLE_ENTHALPY_Z,IS_REALIZABLE
USE CHEMCONS, ONLY: DO_CHEM_LOAD_BALANCE
USE MATH_FUNCTIONS, ONLY: EVALUATE_RAMP

INTEGER :: NM,I,J,K,NC, CHEM_SUBIT_TMP,CHEM_SUBIT_TMP_OUT,ICC,JCC,INDX,NRECEIVE_CELLS
INTEGER :: NCHEM_ACTIVE_CELLS_AND_CC, NCHEM_ACTIVE_CELLS_AND_CC_GLOBAL, IERR, NCHEM_ACTIVE_CELLS, NCHEM_ACTIVE_CC
REAL(EB), INTENT(IN) :: T,DT
REAL(EB) :: ZZ_GET(1:N_TRACKED_SPECIES),DZZ(1:N_TRACKED_SPECIES),&
            REAC_SOURCE_TERM_TMP(N_TRACKED_SPECIES),Q_REAC_TMP(N_REACTIONS),VCELL,PRES,ZETA_0,TSI
LOGICAL :: Q_EXISTS
TYPE (CC_CUTCELL_TYPE), POINTER :: CC
LOGICAL :: IS_CHEM_ACTIVE
REAL(EB) :: MIX_TIME_OUT, Q_OUT, CHI_R_OUT, MYTEMP, MYRHO, MYMU, DELTA, VOL, TNOW2
INTEGER :: IGN_ZN


Q_EXISTS =  .FALSE.

!------
!STEP1: Decide chemically active cells and cut-cells
!------
NCHEM_ACTIVE_CELLS_AND_CC=0
DO NM=LOWER_MESH_INDEX,UPPER_MESH_INDEX
   CALL POINT_TO_MESH(NM)
   NCHEM_ACTIVE_CELLS = 0
   NCHEM_ACTIVE_CC = 0
   CHEM_ACTIVE_CELLS = -1
   ! Decide chemically active cells
   DO K=1,KBAR
      DO J=1,JBAR
         DO I=1,IBAR
            ZZ_GET = ZZ(I,J,K,1:N_TRACKED_SPECIES)
            PRES = PBAR(K,PRESSURE_ZONE(I,J,K)) + RHO(I,J,K)*(H(I,J,K)-KRES(I,J,K))
            CALL CHECK_CHEMICALLY_ACTIVE_STATE(ZZ_GET, TMP(I,J,K), I, J, K, .FALSE., IS_CHEM_ACTIVE, IGN_ZN)
            IF (STOP_STATUS/=NO_STOP) RETURN
            IF (.NOT. IS_CHEM_ACTIVE) CYCLE
            NCHEM_ACTIVE_CELLS_AND_CC = NCHEM_ACTIVE_CELLS_AND_CC + 1
            NCHEM_ACTIVE_CELLS = NCHEM_ACTIVE_CELLS +1
            CHEM_ACTIVE_CELLS(NCHEM_ACTIVE_CELLS,1:3)=[I, J ,K]
            IF(IGN_ZN > 0) CHEM_ACTIVE_CELLS(NCHEM_ACTIVE_CELLS,4) = IGN_ZN
         ENDDO
      ENDDO
   ENDDO

   IF (REAC_SOURCE_CHECK) THEN
      REAC_SOURCE_TERM=0._EB
      Q_REAC=0._EB
      IF (CC_IBM) THEN
         DO ICC=1,MESHES(NM)%N_CUTCELL_MESH
            DO JCC=1,CUT_CELL(ICC)%NCELL
               CUT_CELL(ICC)%Q_REAC(:,JCC) = 0._EB
            ENDDO
         ENDDO
      ENDIF
   ENDIF

   ! Decide chemically active cut-cells
   IF (CC_IBM) THEN
      CHEM_ACTIVE_CC = -1
      DO ICC=1,MESHES(NM)%N_CUTCELL_MESH
         CC => CUT_CELL(ICC); I = CC%IJK(IAXIS); J = CC%IJK(JAXIS); K = CC%IJK(KAXIS)
         VCELL = DX(I)*DY(J)*DZ(K)
         DO JCC=1,CC%NCELL
            ! Drop if cut-cell is very small compared to Cartesian cells:
            IF ( ABS(CUT_CELL(ICC)%VOLUME(JCC)/VCELL) <  1.E-12_EB ) CYCLE
            ZZ_GET = CUT_CELL(ICC)%ZZ(1:N_TRACKED_SPECIES,JCC)
            PRES = PBAR(K,PRESSURE_ZONE(I,J,K)) + RHO(I,J,K)*(H(I,J,K)-KRES(I,J,K))
            CALL CHECK_CHEMICALLY_ACTIVE_STATE(ZZ_GET, CUT_CELL(ICC)%TMP(JCC), I, J, K, .TRUE., IS_CHEM_ACTIVE, IGN_ZN)
            IF (STOP_STATUS/=NO_STOP) RETURN
            IF (.NOT. IS_CHEM_ACTIVE) CYCLE
            NCHEM_ACTIVE_CELLS_AND_CC = NCHEM_ACTIVE_CELLS_AND_CC + 1
            NCHEM_ACTIVE_CC = NCHEM_ACTIVE_CC +1
            CHEM_ACTIVE_CC(NCHEM_ACTIVE_CC,1:2)=[ICC, JCC]
            IF(IGN_ZN > 0) CHEM_ACTIVE_CC(NCHEM_ACTIVE_CC,3) = IGN_ZN
         ENDDO
      ENDDO
   ENDIF
   MESHES(NM)%NCHEM_ACTIVE_CELLS=NCHEM_ACTIVE_CELLS
   MESHES(NM)%NCHEM_ACTIVE_CC=NCHEM_ACTIVE_CC
ENDDO



!------
!STEP2: Solve chemistry by distributing the chemistry load accross all MPI processes for parallel runs.
!       For 1 MPI process (serial) distribution is not needed.
!------

TSI = T-T_BEGIN
ZETA_0 = EVALUATE_RAMP(TSI,ZETA_0_RAMP_INDEX)*INITIAL_UNMIXED_FRACTION

CHEM_LOAD_BALANCE_IF : IF(N_MPI_PROCESSES > 1 .AND. DO_CHEM_LOAD_BALANCE) THEN
   IF (.NOT. ALLOCATED(NCHEM_ACTIVE_CELLS_AND_CC_RANK_WISE)) ALLOCATE(NCHEM_ACTIVE_CELLS_AND_CC_RANK_WISE(N_MPI_PROCESSES))
   NCHEM_ACTIVE_CELLS_AND_CC_RANK_WISE = 0
   CALL MPI_ALLGATHER(NCHEM_ACTIVE_CELLS_AND_CC,1,MPI_INTEGER,NCHEM_ACTIVE_CELLS_AND_CC_RANK_WISE,1,MPI_INTEGER,MPI_COMM_WORLD,IERR)
   NCHEM_ACTIVE_CELLS_AND_CC_GLOBAL = SUM(NCHEM_ACTIVE_CELLS_AND_CC_RANK_WISE(1:N_MPI_PROCESSES))

   IF (NCHEM_ACTIVE_CELLS_AND_CC_GLOBAL > 0) THEN
      ! Distribute chemically activated cell
      CALL DISTRIBUTE_CELLS_ACCROSS_MPI_PROCESSES(NRECEIVE_CELLS)
      
      IF (COMBUSTION_ODE_SOLVER == CVODE_SOLVER) TNOW2 = CURRENT_TIME()

      ! Call chemistry
      ALLOCATE(RESULTS_TO_SEND_ARRAY(NVAR_TO_RECEIVE, MAX(NRECEIVE_CELLS,1))); RESULTS_TO_SEND_ARRAY=0._EB
      DO INDX=1,NRECEIVE_CELLS

         ZZ_GET = REALS_TO_RECV_ARRAY(1:N_TRACKED_SPECIES,INDX)
         MYTEMP = REALS_TO_RECV_ARRAY(N_TRACKED_SPECIES+1,INDX)
         MYRHO  = REALS_TO_RECV_ARRAY(N_TRACKED_SPECIES+2,INDX)
         PRES   = REALS_TO_RECV_ARRAY(N_TRACKED_SPECIES+3,INDX)
         MYMU   = REALS_TO_RECV_ARRAY(N_TRACKED_SPECIES+4,INDX)
         DELTA  = REALS_TO_RECV_ARRAY(N_TRACKED_SPECIES+5,INDX)
         VOL    = REALS_TO_RECV_ARRAY(N_TRACKED_SPECIES+6,INDX)
         IGN_ZN = INT(REALS_TO_RECV_ARRAY(N_TRACKED_SPECIES+7,INDX))
         !***************************************************************************************
         ! Call combustion integration routine for Cartesian cell (I,J,K)
         CALL COMBUSTION_MODEL( T,DT,ZZ_GET,Q_OUT,MIX_TIME_OUT,CHI_R_OUT,&
                                CHEM_SUBIT_TMP_OUT,REAC_SOURCE_TERM_TMP,Q_REAC_TMP,&
                                MYTEMP,MYRHO,PRES,MYMU,DELTA,VOL,ZETA_0,IGN_ZN)
         !***************************************************************************************
         
         RESULTS_TO_SEND_ARRAY(1:N_TRACKED_SPECIES,INDX) = ZZ_GET
         RESULTS_TO_SEND_ARRAY(N_TRACKED_SPECIES+1,INDX) = Q_OUT
         RESULTS_TO_SEND_ARRAY(N_TRACKED_SPECIES+2,INDX) = MIX_TIME_OUT
         RESULTS_TO_SEND_ARRAY(N_TRACKED_SPECIES+3,INDX) = CHI_R_OUT
         RESULTS_TO_SEND_ARRAY(N_TRACKED_SPECIES+4,INDX) = REAL(CHEM_SUBIT_TMP_OUT,EB)

      ENDDO

      IF (COMBUSTION_ODE_SOLVER == CVODE_SOLVER) THEN
         T_CHEM_ODE = T_CHEM_ODE+CURRENT_TIME()-TNOW2
      ENDIF

      IF(ALLOCATED(REALS_TO_RECV_ARRAY))DEALLOCATE(REALS_TO_RECV_ARRAY)

      ! Reverse distribute chemically activated cell
      CALL GATHER_CELLS_FROM_MPI_PROCESSES(DT)
      IF (STOP_STATUS/=NO_STOP) RETURN
   ENDIF !NCHEM_ACTIVE_CELLS_AND_CC_GLOBAL >0

ELSE CHEM_LOAD_BALANCE_IF
   
   IF (NCHEM_ACTIVE_CELLS_AND_CC >0) THEN
      ! Serial chemistry:
      IF (COMBUSTION_ODE_SOLVER == CVODE_SOLVER) TNOW2 = CURRENT_TIME()

      MESH_LOOP_SERIAL : DO NM=LOWER_MESH_INDEX,UPPER_MESH_INDEX
         CALL POINT_TO_MESH(NM)

         NCHEM_ACTIVE_CELLS = MESHES(NM)%NCHEM_ACTIVE_CELLS
         NCHEM_ACTIVE_CC = MESHES(NM)%NCHEM_ACTIVE_CC

         DO NC=1,NCHEM_ACTIVE_CELLS
            I=CHEM_ACTIVE_CELLS(NC,1); J=CHEM_ACTIVE_CELLS(NC,2); K= CHEM_ACTIVE_CELLS(NC,3)
            IGN_ZN=CHEM_ACTIVE_CELLS(NC,4)
            ZZ_GET = ZZ(I,J,K,1:N_TRACKED_SPECIES)
            PRES = PBAR(K,PRESSURE_ZONE(I,J,K)) + RHO(I,J,K)*(H(I,J,K)-KRES(I,J,K))
            DZZ = ZZ_GET ! store old ZZ for divergence term
            !***************************************************************************************
            ! Call combustion integration routine for Cartesian cell (I,J,K)
            CALL COMBUSTION_MODEL( T,DT,ZZ_GET,Q(I,J,K),MIX_TIME(I,J,K),CHI_R(I,J,K),&
                                   CHEM_SUBIT_TMP,REAC_SOURCE_TERM_TMP,Q_REAC_TMP,&
                                   TMP(I,J,K),RHO(I,J,K),PRES, MU(I,J,K),&
                                   LES_FILTER_WIDTH(I,J,K),DX(I)*DY(J)*DZ(K),ZETA_0,IGN_ZN,XC_I=XC(I),YC_J=YC(J),ZC_K=ZC(K) )
            !***************************************************************************************
            !IF (STOP_STATUS/=NO_STOP) RETURN
            IF (OUTPUT_CHEM_IT) CHEM_SUBIT(I,J,K) = CHEM_SUBIT_TMP
            CALL SET_SPECIES_SOURCE_TERM_CELL(DT, I, J, K, ZZ_GET, DZZ, REAC_SOURCE_TERM_TMP, Q_REAC_TMP)
         ENDDO
         
         ! Call chemistry on chemically active cut-cells
         IF (CC_IBM) THEN
            DO NC=1,NCHEM_ACTIVE_CC
               ICC= CHEM_ACTIVE_CC(NC,1); JCC= CHEM_ACTIVE_CC(NC,2)
               IGN_ZN=CHEM_ACTIVE_CC(NC,3)
               CC => CUT_CELL(ICC); I = CC%IJK(IAXIS); J = CC%IJK(JAXIS); K = CC%IJK(KAXIS)
               CC%CHI_R(JCC)    = 0._EB
               ZZ_GET = CC%ZZ(1:N_TRACKED_SPECIES,JCC)
               PRES = PBAR(K,PRESSURE_ZONE(I,J,K)) + RHO(I,J,K)*(H(I,J,K)-KRES(I,J,K))
               DZZ = ZZ_GET ! store old ZZ for divergence term
               !***************************************************************************************
               ! Call combustion integration routine for CC%XX(JCC)
               ! Note AUTO_IGNITION_TEMPERATURE here will apply to all cut-cells in Cartesian cell, currently 1.
               CALL COMBUSTION_MODEL( T,DT,ZZ_GET,CC%Q(JCC),CC%MIX_TIME(JCC),&
                                      CC%CHI_R(JCC),&
                                      CHEM_SUBIT_TMP,REAC_SOURCE_TERM_TMP,Q_REAC_TMP,&
                                      CC%TMP(JCC),CC%RHO(JCC),PRES,MU(I,J,K),&
                                      LES_FILTER_WIDTH(I,J,K),CC%VOLUME(JCC),ZETA_0,IGN_ZN,XC_I=XC(I),YC_J=YC(J),ZC_K=ZC(K))
               !***************************************************************************************
               CALL SET_SPECIES_SOURCE_TERM_CUTCELL(DT, ICC, JCC, ZZ_GET, DZZ, REAC_SOURCE_TERM_TMP, Q_REAC_TMP)
            END DO
         ENDIF
         IF (STOP_STATUS/=NO_STOP) RETURN
      ENDDO  MESH_LOOP_SERIAL

      IF (COMBUSTION_ODE_SOLVER == CVODE_SOLVER) THEN
         T_CHEM_ODE = T_CHEM_ODE+CURRENT_TIME()-TNOW2
      ENDIF
   ENDIF !NCHEM_ACTIVE_CELLS_AND_CC >0
ENDIF CHEM_LOAD_BALANCE_IF

! This volume refactoring is needed for RADIATION_FVM (CHI_R, Q) and plotting slices:
IF(CC_IBM) THEN
   DO NM=LOWER_MESH_INDEX,UPPER_MESH_INDEX
      CALL POINT_TO_MESH(NM)
      DO ICC=1,MESHES(NM)%N_CUTCELL_MESH
         CC => CUT_CELL(ICC); I = CC%IJK(IAXIS); J = CC%IJK(JAXIS); K = CC%IJK(KAXIS)
         VCELL = DX(I)*DY(J)*DZ(K)
         IF (CELL(CELL_INDEX(I,J,K))%SOLID) CYCLE ! Cycle in case Cartesian cell inside OBSTS.
         DO JCC=1,CC%NCELL
            Q(I,J,K) = Q(I,J,K)+CC%Q(JCC)*CC%VOLUME(JCC)
            CHI_R(I,J,K) = CHI_R(I,J,K) + CC%CHI_R(JCC)*CC%Q(JCC)*CC%VOLUME(JCC)
         ENDDO
         IF(ABS(Q(I,J,K)) > TWENTY_EPSILON_EB) THEN
            CHI_R(I,J,K) = CHI_R(I,J,K)/Q(I,J,K)
         ELSE
            CHI_R(I,J,K) = 0._EB
            DO JCC=1,CC%NCELL
               CHI_R(I,J,K) = CHI_R(I,J,K) + CC%CHI_R(JCC)*CC%VOLUME(JCC)
            ENDDO
            CHI_R(I,J,K) = CHI_R(I,J,K)/VCELL
         ENDIF
         Q(I,J,K) = Q(I,J,K)/VCELL
      ENDDO
   ENDDO
ENDIF   

! Output accumulated CVODE warnings (instead of cell by cell) in verbose mode
#ifdef WITH_SUNDIALS
IF (COMBUSTION_ODE_SOLVER == CVODE_SOLVER .AND. VERBOSE) THEN
   CALL DUMP_CVODE_WARNING_SUMMARY(NCHEM_ACTIVE_CELLS_AND_CC)
ENDIF
#endif

END SUBROUTINE COMBUSTION_GENERAL_LOAD_BALANCED


SUBROUTINE CHECK_CHEMICALLY_ACTIVE_STATE (ZZ_GET, TMP, I, J , K, IS_CUT_CELL, CHEM_ACTIVE, IGN_ZN)

USE DEVICE_VARIABLES, ONLY: DEVICE
USE PHYSICAL_FUNCTIONS, ONLY: IS_REALIZABLE, CALC_EQUIV_RATIO
USE COMPLEX_GEOMETRY, ONLY : CC_CGSC, CC_GASPHASE
USE CHEMCONS, ONLY: EQUIV_RATIO_CHECK,MIN_EQUIV_RATIO,MAX_EQUIV_RATIO,N_IGNITION_ZONES,IGNITION_ZONES,USE_MIXED_ZN_AFT_TMP
                                  

REAL(EB), INTENT(IN) :: ZZ_GET(1:N_TRACKED_SPECIES)
REAL(EB), INTENT(IN) :: TMP
INTEGER, INTENT(IN), OPTIONAL :: I, J, K
LOGICAL, INTENT(IN) :: IS_CUT_CELL
LOGICAL, INTENT(INOUT) :: CHEM_ACTIVE
INTEGER, INTENT(INOUT) :: IGN_ZN
LOGICAL :: DO_REACTION, REALIZABLE, LES_EQUIV_CHECK
REAL(EB) :: EQUIV
INTEGER :: IZ

CHEM_ACTIVE = .TRUE.
IGN_ZN = -1
LES_EQUIV_CHECK = .FALSE.

IF (CELL(CELL_INDEX(I,J,K))%SOLID) THEN
   CHEM_ACTIVE = .FALSE.
   RETURN
ENDIF
IF (CC_IBM .AND. .NOT. IS_CUT_CELL) THEN ! Check if cell is regular gas phase cell, if not return.
   IF (CCVAR(I,J,K,CC_CGSC) /= CC_GASPHASE) THEN
      CHEM_ACTIVE = .FALSE.
      RETURN
   ENDIF
ENDIF

IF (.NOT.ALL(REACTION%FAST_CHEMISTRY)) THEN
   ! Check for ignition zones for detailed chemistry
   IF (COMBUSTION_ODE_SOLVER==CVODE_SOLVER) THEN 
      IF (N_IGNITION_ZONES > 0) THEN
         DO IZ=1,N_IGNITION_ZONES
            IF (IGNITION_ZONES(IZ)%DEVC_INDEX>0) THEN
               IF (.NOT.DEVICE(IGNITION_ZONES(IZ)%DEVC_INDEX)%CURRENT_STATE) THEN
                  CYCLE
               ENDIF   
            ENDIF
            IF (XC(I)>=IGNITION_ZONES(IZ)%X1 .AND. XC(I)<=IGNITION_ZONES(IZ)%X2 .AND. &
                YC(J)>=IGNITION_ZONES(IZ)%Y1 .AND. YC(J)<=IGNITION_ZONES(IZ)%Y2 .AND. &
                ZC(K)>=IGNITION_ZONES(IZ)%Z1 .AND. ZC(K)<=IGNITION_ZONES(IZ)%Z2) THEN
               CALL CALC_EQUIV_RATIO(ZZ_GET(1:N_TRACKED_SPECIES), EQUIV)
               ! No need to solve for no fuel (phi < MIN ) case and only fuel (phi is rich > MAX) case.
               IF (EQUIV .GT. MIN_EQUIV_RATIO .AND. EQUIV .LT. MAX_EQUIV_RATIO) THEN
                  IGN_ZN = IZ
                  EXIT
               ENDIF   
            ENDIF
         ENDDO
      ENDIF
   ENDIF   

   IF (IGN_ZN .LE. 0 .AND. SIM_MODE .NE. DNS_MODE .AND. USE_MIXED_ZN_AFT_TMP) THEN ! LES and other modes. Check equiv ratio
      CALL CALC_EQUIV_RATIO(ZZ_GET(1:N_TRACKED_SPECIES), EQUIV)
      ! No need to solve for no fuel (phi < MIN ) case and only fuel (phi is rich > MAX) case.
      IF (EQUIV .GT. MIN_EQUIV_RATIO .AND. EQUIV .LT. MAX_EQUIV_RATIO) THEN
         LES_EQUIV_CHECK = .TRUE. ! Chemically active
      ENDIF   
   ENDIF

   IF (IGN_ZN .LE. 0 .AND. .NOT. LES_EQUIV_CHECK .AND. TMP < FINITE_RATE_MIN_TEMP) THEN
      CHEM_ACTIVE = .FALSE.
      RETURN
   ENDIF
ENDIF

IF (CHECK_REALIZABILITY) THEN
   REALIZABLE=IS_REALIZABLE(ZZ_GET)
   IF (.NOT.REALIZABLE) THEN
      WRITE(LU_ERR,*) I,J,K
      WRITE(LU_ERR,*) ZZ_GET
      WRITE(LU_ERR,*) SUM(ZZ_GET)
      WRITE(LU_ERR,*) 'ERROR: Unrealizable mass fractions input to COMBUSTION_MODEL'
      STOP_STATUS=REALIZABILITY_STOP
      RETURN
   ENDIF
ENDIF
CALL CHECK_REACTION (ZZ_GET, DO_REACTION)
IF (.NOT.DO_REACTION) THEN
   CHEM_ACTIVE = .FALSE.
   RETURN
ENDIF

! Check equivalence ratio of the mixture. Avoid chemistry calculation for very lean and rich cases.
IF (COMBUSTION_ODE_SOLVER==CVODE_SOLVER .AND. EQUIV_RATIO_CHECK) THEN
   CALL CALC_EQUIV_RATIO(ZZ_GET(1:N_TRACKED_SPECIES), EQUIV)
   IF(EQUIV <  MIN_EQUIV_RATIO .OR. EQUIV > MAX_EQUIV_RATIO) THEN 
      CHEM_ACTIVE = .FALSE.
      RETURN
   ENDIF   
ENDIF
END SUBROUTINE CHECK_CHEMICALLY_ACTIVE_STATE


SUBROUTINE SET_SPECIES_SOURCE_TERM_CELL(DT, I, J, K, ZZ_NEW, ZZ_OLD, REAC_SOURCE_TERM_TMP, Q_REAC_TMP )

USE PHYSICAL_FUNCTIONS, ONLY: GET_SPECIFIC_GAS_CONSTANT,GET_SPECIFIC_HEAT, &
                              GET_SENSIBLE_ENTHALPY_Z,IS_REALIZABLE
REAL(EB), INTENT(IN) :: DT
REAL(EB), INTENT(INOUT) :: ZZ_NEW(N_TRACKED_SPECIES), ZZ_OLD(N_TRACKED_SPECIES)
REAL(EB), INTENT(IN) :: REAC_SOURCE_TERM_TMP(N_TRACKED_SPECIES), Q_REAC_TMP(N_REACTIONS)
INTEGER, INTENT(IN) :: I, J, K
REAL(EB) :: DZZ(1:N_TRACKED_SPECIES)
REAL(EB) :: RSUM_LOC, CP, H_S_N
LOGICAL :: Q_EXISTS, REALIZABLE
TYPE (SPECIES_MIXTURE_TYPE), POINTER :: SM
INTEGER :: N

IF (REAC_SOURCE_CHECK) THEN ! Store special diagnostic quantities
   REAC_SOURCE_TERM(I,J,K,:) = REAC_SOURCE_TERM_TMP
   Q_REAC(I,J,K,:) = Q_REAC_TMP
ENDIF
IF (CHECK_REALIZABILITY) THEN
   REALIZABLE=IS_REALIZABLE(ZZ_NEW)
   IF (.NOT.REALIZABLE) THEN
      WRITE(LU_ERR,*) ZZ_NEW,SUM(ZZ_NEW)
      WRITE(LU_ERR,*) 'ERROR: Unrealizable mass fractions after COMBUSTION_MODEL'
      STOP_STATUS=REALIZABILITY_STOP
      RETURN
   ENDIF
ENDIF
DZZ = ZZ_NEW - ZZ_OLD
! Update RSUM and ZZ
DZZ_IF: IF ( ANY(ABS(DZZ) > DZZ_CLIP) ) THEN
   IF (ABS(Q(I,J,K)) > TWENTY_EPSILON_EB) Q_EXISTS = .TRUE.
   ! Divergence term
   CALL GET_SPECIFIC_HEAT(ZZ_NEW,CP,TMP(I,J,K))
   CALL GET_SPECIFIC_GAS_CONSTANT(ZZ_NEW,RSUM_LOC)
   DO N=1,N_TRACKED_SPECIES
      SM => SPECIES_MIXTURE(N)
      CALL GET_SENSIBLE_ENTHALPY_Z(N,TMP(I,J,K),H_S_N)
      D_SOURCE(I,J,K) = D_SOURCE(I,J,K) + ( SM%RCON/RSUM_LOC - H_S_N/(CP*TMP(I,J,K)) )*DZZ(N)/DT
      M_DOT_PPP(I,J,K,N) = M_DOT_PPP(I,J,K,N) + RHO(I,J,K)*DZZ(N)/DT
   ENDDO
ENDIF DZZ_IF

END SUBROUTINE SET_SPECIES_SOURCE_TERM_CELL


SUBROUTINE SET_SPECIES_SOURCE_TERM_CUTCELL(DT, ICC, JCC, ZZ_NEW, ZZ_OLD, REAC_SOURCE_TERM_TMP, Q_REAC_TMP )

USE PHYSICAL_FUNCTIONS, ONLY: GET_SPECIFIC_GAS_CONSTANT,GET_SPECIFIC_HEAT, &
                              GET_SENSIBLE_ENTHALPY_Z,IS_REALIZABLE
REAL(EB), INTENT(IN) :: DT
REAL(EB), INTENT(INOUT) :: ZZ_NEW(N_TRACKED_SPECIES), ZZ_OLD(N_TRACKED_SPECIES)
REAL(EB), INTENT(IN) :: REAC_SOURCE_TERM_TMP(N_TRACKED_SPECIES), Q_REAC_TMP(N_REACTIONS)
INTEGER, INTENT(IN) :: ICC, JCC
REAL(EB) :: DZZ(1:N_TRACKED_SPECIES)
REAL(EB) :: CP, H_S_N
LOGICAL :: Q_EXISTS, REALIZABLE
TYPE (SPECIES_MIXTURE_TYPE), POINTER :: SM
INTEGER :: N

IF (REAC_SOURCE_CHECK) THEN ! Store special diagnostic quantities
    CUT_CELL(ICC)%REAC_SOURCE_TERM(1:N_TRACKED_SPECIES,JCC)=REAC_SOURCE_TERM_TMP(1:N_TRACKED_SPECIES)
    CUT_CELL(ICC)%Q_REAC(1:N_REACTIONS,JCC)=Q_REAC_TMP(1:N_REACTIONS)
ENDIF

IF (CHECK_REALIZABILITY) THEN
   REALIZABLE=IS_REALIZABLE(ZZ_NEW)
   IF (.NOT.REALIZABLE) THEN
      WRITE(LU_ERR,*) ZZ_NEW,SUM(ZZ_NEW)
      WRITE(LU_ERR,*) 'ERROR: Unrealizable mass fractions after COMBUSTION_MODEL'
      STOP_STATUS=REALIZABILITY_STOP
   ENDIF
ENDIF
DZZ = ZZ_NEW - ZZ_OLD

! Update RSUM and ZZ
DZZ_IF2: IF ( ANY(ABS(DZZ) > DZZ_CLIP) ) THEN
   IF (ABS(CUT_CELL(ICC)%Q(JCC)) > TWENTY_EPSILON_EB) Q_EXISTS = .TRUE.
   ! Divergence term
   CALL GET_SPECIFIC_HEAT(ZZ_NEW,CP,CUT_CELL(ICC)%TMP(JCC))
   CALL GET_SPECIFIC_GAS_CONSTANT(ZZ_NEW,CUT_CELL(ICC)%RSUM(JCC))
   DO N=1,N_TRACKED_SPECIES
      SM => SPECIES_MIXTURE(N)
      CALL GET_SENSIBLE_ENTHALPY_Z(N,CUT_CELL(ICC)%TMP(JCC),H_S_N)
      CUT_CELL(ICC)%D_SOURCE(JCC) = CUT_CELL(ICC)%D_SOURCE(JCC) + &
      ( SM%RCON/CUT_CELL(ICC)%RSUM(JCC) - H_S_N/(CP*CUT_CELL(ICC)%TMP(JCC)) )*DZZ(N)/DT
      CUT_CELL(ICC)%M_DOT_PPP(N,JCC) = CUT_CELL(ICC)%M_DOT_PPP(N,JCC) + &
      CUT_CELL(ICC)%RHO(JCC)*DZZ(N)/DT
   ENDDO
ENDIF DZZ_IF2

END SUBROUTINE SET_SPECIES_SOURCE_TERM_CUTCELL


!> \brief Thread-safe per-mesh combustion kernel for parallel execution.
!> Combines pre-chemistry zeroing, active cell identification, chemistry ODE solve,
!> and CC_IBM volume averaging for a single mesh. Does NOT call POINT_TO_MESH.

RECURSIVE SUBROUTINE COMBUSTION_GENERAL_KERNEL(NM, T, DT)

USE MATH_FUNCTIONS, ONLY: EVALUATE_RAMP
USE PHYSICAL_FUNCTIONS, ONLY: GET_SPECIFIC_GAS_CONSTANT, GET_SPECIFIC_HEAT, &
                              GET_SENSIBLE_ENTHALPY_Z, IS_REALIZABLE, CALC_EQUIV_RATIO
USE DEVICE_VARIABLES, ONLY: DEVICE
USE COMPLEX_GEOMETRY, ONLY: CC_CGSC, CC_GASPHASE
USE CHEMCONS, ONLY: EQUIV_RATIO_CHECK, MIN_EQUIV_RATIO, MAX_EQUIV_RATIO, N_IGNITION_ZONES, &
                    IGNITION_ZONES, USE_MIXED_ZN_AFT_TMP

INTEGER, INTENT(IN) :: NM
REAL(EB), INTENT(IN) :: T, DT
TYPE(MESH_TYPE), POINTER :: M
INTEGER :: I, J, K, NC, ICC, JCC, IGN_ZN, NCHEM_ACTIVE_CELLS_K, NCHEM_ACTIVE_CC_K, CHEM_SUBIT_TMP
REAL(EB) :: ZZ_GET(1:N_TRACKED_SPECIES), DZZ(1:N_TRACKED_SPECIES)
REAL(EB) :: REAC_SOURCE_TERM_TMP(N_TRACKED_SPECIES), Q_REAC_TMP(N_REACTIONS)
REAL(EB) :: PRES, ZETA_0, TSI, VCELL
LOGICAL :: IS_CHEM_ACTIVE
TYPE(CC_CUTCELL_TYPE), POINTER :: CC

M => MESHES(NM)

! --- Pre-chemistry: zero Q and CHI_R ---

M%Q = 0._EB
M%CHI_R = 0._EB
IF (CC_IBM) THEN
   DO ICC=1,M%N_CUTCELL_MESH
      DO JCC=1,M%CUT_CELL(ICC)%NCELL
         M%CUT_CELL(ICC)%Q(JCC) = 0._EB
      ENDDO
   ENDDO
ENDIF

IF (N_REACTIONS==0) RETURN

! --- STEP 1: Identify chemically active cells ---

NCHEM_ACTIVE_CELLS_K = 0
NCHEM_ACTIVE_CC_K = 0
M%CHEM_ACTIVE_CELLS = -1

DO K=1,M%KBAR
   DO J=1,M%JBAR
      DO I=1,M%IBAR
         ZZ_GET = M%ZZ(I,J,K,1:N_TRACKED_SPECIES)
         CALL CHECK_ACTIVE_STATE_K(ZZ_GET, M%TMP(I,J,K), I, J, K, .FALSE., IS_CHEM_ACTIVE, IGN_ZN)
         IF (STOP_STATUS/=NO_STOP) RETURN
         IF (.NOT. IS_CHEM_ACTIVE) CYCLE
         NCHEM_ACTIVE_CELLS_K = NCHEM_ACTIVE_CELLS_K + 1
         M%CHEM_ACTIVE_CELLS(NCHEM_ACTIVE_CELLS_K,1:3) = [I, J, K]
         IF (IGN_ZN > 0) M%CHEM_ACTIVE_CELLS(NCHEM_ACTIVE_CELLS_K,4) = IGN_ZN
      ENDDO
   ENDDO
ENDDO

IF (REAC_SOURCE_CHECK) THEN
   M%REAC_SOURCE_TERM = 0._EB
   M%Q_REAC = 0._EB
   IF (CC_IBM) THEN
      DO ICC=1,M%N_CUTCELL_MESH
         DO JCC=1,M%CUT_CELL(ICC)%NCELL
            M%CUT_CELL(ICC)%Q_REAC(:,JCC) = 0._EB
         ENDDO
      ENDDO
   ENDIF
ENDIF

! Decide chemically active cut-cells
IF (CC_IBM) THEN
   M%CHEM_ACTIVE_CC = -1
   DO ICC=1,M%N_CUTCELL_MESH
      CC => M%CUT_CELL(ICC); I = CC%IJK(IAXIS); J = CC%IJK(JAXIS); K = CC%IJK(KAXIS)
      VCELL = M%DX(I)*M%DY(J)*M%DZ(K)
      DO JCC=1,CC%NCELL
         IF (ABS(M%CUT_CELL(ICC)%VOLUME(JCC)/VCELL) < 1.E-12_EB) CYCLE
         ZZ_GET = M%CUT_CELL(ICC)%ZZ(1:N_TRACKED_SPECIES,JCC)
         CALL CHECK_ACTIVE_STATE_K(ZZ_GET, M%CUT_CELL(ICC)%TMP(JCC), I, J, K, .TRUE., IS_CHEM_ACTIVE, IGN_ZN)
         IF (STOP_STATUS/=NO_STOP) RETURN
         IF (.NOT. IS_CHEM_ACTIVE) CYCLE
         NCHEM_ACTIVE_CC_K = NCHEM_ACTIVE_CC_K + 1
         M%CHEM_ACTIVE_CC(NCHEM_ACTIVE_CC_K,1:2) = [ICC, JCC]
         IF (IGN_ZN > 0) M%CHEM_ACTIVE_CC(NCHEM_ACTIVE_CC_K,3) = IGN_ZN
      ENDDO
   ENDDO
ENDIF

M%NCHEM_ACTIVE_CELLS = NCHEM_ACTIVE_CELLS_K
M%NCHEM_ACTIVE_CC = NCHEM_ACTIVE_CC_K

IF (NCHEM_ACTIVE_CELLS_K + NCHEM_ACTIVE_CC_K == 0) RETURN

! --- STEP 2: Chemistry ODE solve ---

TSI = T - T_BEGIN
ZETA_0 = EVALUATE_RAMP(TSI, ZETA_0_RAMP_INDEX) * INITIAL_UNMIXED_FRACTION

DO NC=1,NCHEM_ACTIVE_CELLS_K
   I = M%CHEM_ACTIVE_CELLS(NC,1); J = M%CHEM_ACTIVE_CELLS(NC,2); K = M%CHEM_ACTIVE_CELLS(NC,3)
   IGN_ZN = M%CHEM_ACTIVE_CELLS(NC,4)
   ZZ_GET = M%ZZ(I,J,K,1:N_TRACKED_SPECIES)
   PRES = M%PBAR(K,M%PRESSURE_ZONE(I,J,K)) + M%RHO(I,J,K)*(M%H(I,J,K)-M%KRES(I,J,K))
   DZZ = ZZ_GET
   CALL COMBUSTION_MODEL(T,DT,ZZ_GET,M%Q(I,J,K),M%MIX_TIME(I,J,K),M%CHI_R(I,J,K),&
                         CHEM_SUBIT_TMP,REAC_SOURCE_TERM_TMP,Q_REAC_TMP,&
                         M%TMP(I,J,K),M%RHO(I,J,K),PRES,M%MU(I,J,K),&
                         M%LES_FILTER_WIDTH(I,J,K),M%DX(I)*M%DY(J)*M%DZ(K),ZETA_0,IGN_ZN,&
                         XC_I=M%XC(I),YC_J=M%YC(J),ZC_K=M%ZC(K))
   IF (OUTPUT_CHEM_IT) M%CHEM_SUBIT(I,J,K) = CHEM_SUBIT_TMP
   CALL SET_SOURCE_TERM_CELL_K(DT, I, J, K, ZZ_GET, DZZ, REAC_SOURCE_TERM_TMP, Q_REAC_TMP)
ENDDO

! Chemistry on cut-cells
IF (CC_IBM) THEN
   DO NC=1,NCHEM_ACTIVE_CC_K
      ICC = M%CHEM_ACTIVE_CC(NC,1); JCC = M%CHEM_ACTIVE_CC(NC,2)
      IGN_ZN = M%CHEM_ACTIVE_CC(NC,3)
      CC => M%CUT_CELL(ICC); I = CC%IJK(IAXIS); J = CC%IJK(JAXIS); K = CC%IJK(KAXIS)
      CC%CHI_R(JCC) = 0._EB
      ZZ_GET = CC%ZZ(1:N_TRACKED_SPECIES,JCC)
      PRES = M%PBAR(K,M%PRESSURE_ZONE(I,J,K)) + M%RHO(I,J,K)*(M%H(I,J,K)-M%KRES(I,J,K))
      DZZ = ZZ_GET
      CALL COMBUSTION_MODEL(T,DT,ZZ_GET,CC%Q(JCC),CC%MIX_TIME(JCC),CC%CHI_R(JCC),&
                            CHEM_SUBIT_TMP,REAC_SOURCE_TERM_TMP,Q_REAC_TMP,&
                            CC%TMP(JCC),CC%RHO(JCC),PRES,M%MU(I,J,K),&
                            M%LES_FILTER_WIDTH(I,J,K),CC%VOLUME(JCC),ZETA_0,IGN_ZN,&
                            XC_I=M%XC(I),YC_J=M%YC(J),ZC_K=M%ZC(K))
      CALL SET_SOURCE_TERM_CUTCELL_K(DT, ICC, JCC, ZZ_GET, DZZ, REAC_SOURCE_TERM_TMP, Q_REAC_TMP)
   ENDDO
ENDIF

! --- CC_IBM volume averaging ---

IF (CC_IBM) THEN
   DO ICC=1,M%N_CUTCELL_MESH
      CC => M%CUT_CELL(ICC); I = CC%IJK(IAXIS); J = CC%IJK(JAXIS); K = CC%IJK(KAXIS)
      VCELL = M%DX(I)*M%DY(J)*M%DZ(K)
      IF (M%CELL(M%CELL_INDEX(I,J,K))%SOLID) CYCLE
      DO JCC=1,CC%NCELL
         M%Q(I,J,K) = M%Q(I,J,K) + CC%Q(JCC)*CC%VOLUME(JCC)
         M%CHI_R(I,J,K) = M%CHI_R(I,J,K) + CC%CHI_R(JCC)*CC%Q(JCC)*CC%VOLUME(JCC)
      ENDDO
      IF (ABS(M%Q(I,J,K)) > TWENTY_EPSILON_EB) THEN
         M%CHI_R(I,J,K) = M%CHI_R(I,J,K)/M%Q(I,J,K)
      ELSE
         M%CHI_R(I,J,K) = 0._EB
         DO JCC=1,CC%NCELL
            M%CHI_R(I,J,K) = M%CHI_R(I,J,K) + CC%CHI_R(JCC)*CC%VOLUME(JCC)
         ENDDO
         M%CHI_R(I,J,K) = M%CHI_R(I,J,K)/VCELL
      ENDIF
      M%Q(I,J,K) = M%Q(I,J,K)/VCELL
   ENDDO
ENDIF

CONTAINS

SUBROUTINE CHECK_ACTIVE_STATE_K(ZZ_GET_IN, TMP_IN, I, J, K, IS_CUT_CELL, CHEM_ACTIVE, IGN_ZN_OUT)
! Thread-safe version of CHECK_CHEMICALLY_ACTIVE_STATE using M from host association
REAL(EB), INTENT(IN) :: ZZ_GET_IN(1:N_TRACKED_SPECIES)
REAL(EB), INTENT(IN) :: TMP_IN
INTEGER, INTENT(IN) :: I, J, K
LOGICAL, INTENT(IN) :: IS_CUT_CELL
LOGICAL, INTENT(INOUT) :: CHEM_ACTIVE
INTEGER, INTENT(INOUT) :: IGN_ZN_OUT
LOGICAL :: DO_REACTION, REALIZABLE, LES_EQUIV_CHECK
REAL(EB) :: EQUIV
INTEGER :: IZ

CHEM_ACTIVE = .TRUE.
IGN_ZN_OUT = -1
LES_EQUIV_CHECK = .FALSE.

IF (M%CELL(M%CELL_INDEX(I,J,K))%SOLID) THEN
   CHEM_ACTIVE = .FALSE.
   RETURN
ENDIF
IF (CC_IBM .AND. .NOT. IS_CUT_CELL) THEN
   IF (M%CCVAR(I,J,K,CC_CGSC) /= CC_GASPHASE) THEN
      CHEM_ACTIVE = .FALSE.
      RETURN
   ENDIF
ENDIF

IF (.NOT.ALL(REACTION%FAST_CHEMISTRY)) THEN
   IF (COMBUSTION_ODE_SOLVER==CVODE_SOLVER) THEN
      IF (N_IGNITION_ZONES > 0) THEN
         DO IZ=1,N_IGNITION_ZONES
            IF (IGNITION_ZONES(IZ)%DEVC_INDEX>0) THEN
               IF (.NOT.DEVICE(IGNITION_ZONES(IZ)%DEVC_INDEX)%CURRENT_STATE) CYCLE
            ENDIF
            IF (M%XC(I)>=IGNITION_ZONES(IZ)%X1 .AND. M%XC(I)<=IGNITION_ZONES(IZ)%X2 .AND. &
                M%YC(J)>=IGNITION_ZONES(IZ)%Y1 .AND. M%YC(J)<=IGNITION_ZONES(IZ)%Y2 .AND. &
                M%ZC(K)>=IGNITION_ZONES(IZ)%Z1 .AND. M%ZC(K)<=IGNITION_ZONES(IZ)%Z2) THEN
               CALL CALC_EQUIV_RATIO(ZZ_GET_IN(1:N_TRACKED_SPECIES), EQUIV)
               IF (EQUIV > MIN_EQUIV_RATIO .AND. EQUIV < MAX_EQUIV_RATIO) THEN
                  IGN_ZN_OUT = IZ
                  EXIT
               ENDIF
            ENDIF
         ENDDO
      ENDIF
   ENDIF

   IF (IGN_ZN_OUT <= 0 .AND. SIM_MODE /= DNS_MODE .AND. USE_MIXED_ZN_AFT_TMP) THEN
      CALL CALC_EQUIV_RATIO(ZZ_GET_IN(1:N_TRACKED_SPECIES), EQUIV)
      IF (EQUIV > MIN_EQUIV_RATIO .AND. EQUIV < MAX_EQUIV_RATIO) LES_EQUIV_CHECK = .TRUE.
   ENDIF

   IF (IGN_ZN_OUT <= 0 .AND. .NOT. LES_EQUIV_CHECK .AND. TMP_IN < FINITE_RATE_MIN_TEMP) THEN
      CHEM_ACTIVE = .FALSE.
      RETURN
   ENDIF
ENDIF

IF (CHECK_REALIZABILITY) THEN
   REALIZABLE = IS_REALIZABLE(ZZ_GET_IN)
   IF (.NOT.REALIZABLE) THEN
      WRITE(LU_ERR,*) I,J,K
      WRITE(LU_ERR,*) ZZ_GET_IN
      WRITE(LU_ERR,*) SUM(ZZ_GET_IN)
      WRITE(LU_ERR,*) 'ERROR: Unrealizable mass fractions input to COMBUSTION_MODEL'
      STOP_STATUS = REALIZABILITY_STOP
      RETURN
   ENDIF
ENDIF
CALL CHECK_REACTION(ZZ_GET_IN, DO_REACTION)
IF (.NOT.DO_REACTION) THEN
   CHEM_ACTIVE = .FALSE.
   RETURN
ENDIF

IF (COMBUSTION_ODE_SOLVER==CVODE_SOLVER .AND. EQUIV_RATIO_CHECK) THEN
   CALL CALC_EQUIV_RATIO(ZZ_GET_IN(1:N_TRACKED_SPECIES), EQUIV)
   IF (EQUIV < MIN_EQUIV_RATIO .OR. EQUIV > MAX_EQUIV_RATIO) THEN
      CHEM_ACTIVE = .FALSE.
      RETURN
   ENDIF
ENDIF
END SUBROUTINE CHECK_ACTIVE_STATE_K


SUBROUTINE SET_SOURCE_TERM_CELL_K(DT_IN, I, J, K, ZZ_NEW, ZZ_OLD, REAC_SRC_TMP, Q_REAC_TMP_IN)
! Thread-safe version of SET_SPECIES_SOURCE_TERM_CELL using M from host association
REAL(EB), INTENT(IN) :: DT_IN
REAL(EB), INTENT(INOUT) :: ZZ_NEW(N_TRACKED_SPECIES), ZZ_OLD(N_TRACKED_SPECIES)
REAL(EB), INTENT(IN) :: REAC_SRC_TMP(N_TRACKED_SPECIES), Q_REAC_TMP_IN(N_REACTIONS)
INTEGER, INTENT(IN) :: I, J, K
REAL(EB) :: DZZ_L(1:N_TRACKED_SPECIES), RSUM_LOC, CP, H_S_N
LOGICAL :: REALIZABLE
TYPE(SPECIES_MIXTURE_TYPE), POINTER :: SM
INTEGER :: N

IF (REAC_SOURCE_CHECK) THEN
   M%REAC_SOURCE_TERM(I,J,K,:) = REAC_SRC_TMP
   M%Q_REAC(I,J,K,:) = Q_REAC_TMP_IN
ENDIF
IF (CHECK_REALIZABILITY) THEN
   REALIZABLE = IS_REALIZABLE(ZZ_NEW)
   IF (.NOT.REALIZABLE) THEN
      WRITE(LU_ERR,*) ZZ_NEW,SUM(ZZ_NEW)
      WRITE(LU_ERR,*) 'ERROR: Unrealizable mass fractions after COMBUSTION_MODEL'
      STOP_STATUS = REALIZABILITY_STOP
      RETURN
   ENDIF
ENDIF
DZZ_L = ZZ_NEW - ZZ_OLD
IF (ANY(ABS(DZZ_L) > DZZ_CLIP)) THEN
   CALL GET_SPECIFIC_HEAT(ZZ_NEW,CP,M%TMP(I,J,K))
   CALL GET_SPECIFIC_GAS_CONSTANT(ZZ_NEW,RSUM_LOC)
   DO N=1,N_TRACKED_SPECIES
      SM => SPECIES_MIXTURE(N)
      CALL GET_SENSIBLE_ENTHALPY_Z(N,M%TMP(I,J,K),H_S_N)
      M%D_SOURCE(I,J,K) = M%D_SOURCE(I,J,K) + (SM%RCON/RSUM_LOC - H_S_N/(CP*M%TMP(I,J,K)))*DZZ_L(N)/DT_IN
      M%M_DOT_PPP(I,J,K,N) = M%M_DOT_PPP(I,J,K,N) + M%RHO(I,J,K)*DZZ_L(N)/DT_IN
   ENDDO
ENDIF
END SUBROUTINE SET_SOURCE_TERM_CELL_K


SUBROUTINE SET_SOURCE_TERM_CUTCELL_K(DT_IN, ICC_IN, JCC_IN, ZZ_NEW, ZZ_OLD, REAC_SRC_TMP, Q_REAC_TMP_IN)
! Thread-safe version of SET_SPECIES_SOURCE_TERM_CUTCELL using M from host association
REAL(EB), INTENT(IN) :: DT_IN
REAL(EB), INTENT(INOUT) :: ZZ_NEW(N_TRACKED_SPECIES), ZZ_OLD(N_TRACKED_SPECIES)
REAL(EB), INTENT(IN) :: REAC_SRC_TMP(N_TRACKED_SPECIES), Q_REAC_TMP_IN(N_REACTIONS)
INTEGER, INTENT(IN) :: ICC_IN, JCC_IN
REAL(EB) :: DZZ_L(1:N_TRACKED_SPECIES), CP, H_S_N
LOGICAL :: REALIZABLE
TYPE(SPECIES_MIXTURE_TYPE), POINTER :: SM
INTEGER :: N

IF (REAC_SOURCE_CHECK) THEN
   M%CUT_CELL(ICC_IN)%REAC_SOURCE_TERM(1:N_TRACKED_SPECIES,JCC_IN) = REAC_SRC_TMP(1:N_TRACKED_SPECIES)
   M%CUT_CELL(ICC_IN)%Q_REAC(1:N_REACTIONS,JCC_IN) = Q_REAC_TMP_IN(1:N_REACTIONS)
ENDIF
IF (CHECK_REALIZABILITY) THEN
   REALIZABLE = IS_REALIZABLE(ZZ_NEW)
   IF (.NOT.REALIZABLE) THEN
      WRITE(LU_ERR,*) ZZ_NEW,SUM(ZZ_NEW)
      WRITE(LU_ERR,*) 'ERROR: Unrealizable mass fractions after COMBUSTION_MODEL'
      STOP_STATUS = REALIZABILITY_STOP
   ENDIF
ENDIF
DZZ_L = ZZ_NEW - ZZ_OLD
IF (ANY(ABS(DZZ_L) > DZZ_CLIP)) THEN
   CALL GET_SPECIFIC_HEAT(ZZ_NEW,CP,M%CUT_CELL(ICC_IN)%TMP(JCC_IN))
   CALL GET_SPECIFIC_GAS_CONSTANT(ZZ_NEW,M%CUT_CELL(ICC_IN)%RSUM(JCC_IN))
   DO N=1,N_TRACKED_SPECIES
      SM => SPECIES_MIXTURE(N)
      CALL GET_SENSIBLE_ENTHALPY_Z(N,M%CUT_CELL(ICC_IN)%TMP(JCC_IN),H_S_N)
      M%CUT_CELL(ICC_IN)%D_SOURCE(JCC_IN) = M%CUT_CELL(ICC_IN)%D_SOURCE(JCC_IN) + &
         (SM%RCON/M%CUT_CELL(ICC_IN)%RSUM(JCC_IN) - H_S_N/(CP*M%CUT_CELL(ICC_IN)%TMP(JCC_IN)))*DZZ_L(N)/DT_IN
      M%CUT_CELL(ICC_IN)%M_DOT_PPP(N,JCC_IN) = M%CUT_CELL(ICC_IN)%M_DOT_PPP(N,JCC_IN) + &
         M%CUT_CELL(ICC_IN)%RHO(JCC_IN)*DZZ_L(N)/DT_IN
   ENDDO
ENDIF
END SUBROUTINE SET_SOURCE_TERM_CUTCELL_K

END SUBROUTINE COMBUSTION_GENERAL_KERNEL


SUBROUTINE DISTRIBUTE_CELLS_ACCROSS_MPI_PROCESSES (NRECEIVE_CELLS)
INTEGER, INTENT(OUT) :: NRECEIVE_CELLS
INTEGER :: NCHEM_ACTIVE_CELLS_AND_CC, NCHEM_ACTIVE_CELLS, NCHEM_ACTIVE_CC, NC
INTEGER :: I, J , K, NM, INDX, ICC, JCC, RANK_TO, SEQ,IERR
INTEGER :: CELLS_PER_RANK, CELLS_ALLOC
INTEGER :: TEMPARR1(N_MPI_PROCESSES), TEMPARR2(N_MPI_PROCESSES)
REAL(EB) :: ZZ_GET(1:N_TRACKED_SPECIES)
REAL(EB) :: PRES, TNOW
TYPE (CC_CUTCELL_TYPE), POINTER :: CC

TNOW = CURRENT_TIME()

NCHEM_ACTIVE_CELLS_AND_CC = NCHEM_ACTIVE_CELLS_AND_CC_RANK_WISE(MY_RANK+1)
CELLS_PER_RANK = CEILING(REAL(NCHEM_ACTIVE_CELLS_AND_CC,EB)/REAL(N_MPI_PROCESSES,EB))
CELLS_ALLOC    = CELLS_PER_RANK * N_MPI_PROCESSES

IF (.NOT. ALLOCATED(NCELLS_TO_SEND_ARRAY)) ALLOCATE(NCELLS_TO_SEND_ARRAY(N_MPI_PROCESSES)) 
IF (.NOT. ALLOCATED(NCELLS_TO_RECV_ARRAY)) ALLOCATE(NCELLS_TO_RECV_ARRAY(N_MPI_PROCESSES)) 
IF (.NOT. ALLOCATED(SEND_DISPS)) ALLOCATE(SEND_DISPS(N_MPI_PROCESSES))
IF (.NOT. ALLOCATED(REVC_DISPS)) ALLOCATE(REVC_DISPS(N_MPI_PROCESSES))
NCELLS_TO_SEND_ARRAY=0
NCELLS_TO_RECV_ARRAY=0
SEND_DISPS = 0 
REVC_DISPS = 0

ALLOCATE(REALS_TO_SEND_ARRAY(NVAR_TO_SEND,MAX(CELLS_ALLOC,1))); REALS_TO_SEND_ARRAY=0._EB
ALLOCATE(CHEM_SEQ_ARR(MAX(CELLS_ALLOC,1)));
   
SEQ = 0 ! Store the sequence
! Prepare the Send buffer data. Note RANK_TO here is 1-based i.e. 1 to N_MPI_PROCESS
IF (NCHEM_ACTIVE_CELLS_AND_CC > 0) THEN
   ALLOCATE(INTEGERS_TEST_ARRAY(CELLS_ALLOC)); INTEGERS_TEST_ARRAY=-1

   IF (MY_RANK == 0) THEN
      RANK_TO = 1
   ELSE
      RANK_TO = MOD(SUM(NCHEM_ACTIVE_CELLS_AND_CC_RANK_WISE(1:MY_RANK)), N_MPI_PROCESSES)+1
   ENDIF
   DO NM=LOWER_MESH_INDEX,UPPER_MESH_INDEX
      CALL POINT_TO_MESH(NM)

      NCHEM_ACTIVE_CELLS = MESHES(NM)%NCHEM_ACTIVE_CELLS
      NCHEM_ACTIVE_CC = MESHES(NM)%NCHEM_ACTIVE_CC

      DO NC=1,NCHEM_ACTIVE_CELLS
         I=CHEM_ACTIVE_CELLS(NC,1); J=CHEM_ACTIVE_CELLS(NC,2); K= CHEM_ACTIVE_CELLS(NC,3)
         SEQ = SEQ+1
         NCELLS_TO_SEND_ARRAY(RANK_TO)=NCELLS_TO_SEND_ARRAY(RANK_TO)+1
         INDX= CELLS_PER_RANK*(RANK_TO-1) + NCELLS_TO_SEND_ARRAY(RANK_TO)
         INTEGERS_TEST_ARRAY(INDX) = NM
         CHEM_SEQ_ARR(SEQ) = INDX
         ! Reals to send:
         ZZ_GET = ZZ(I,J,K,1:N_TRACKED_SPECIES)
         PRES = PBAR(K,PRESSURE_ZONE(I,J,K)) + RHO(I,J,K)*(H(I,J,K)-KRES(I,J,K))
         REALS_TO_SEND_ARRAY(1:N_TRACKED_SPECIES,INDX) = ZZ_GET
         REALS_TO_SEND_ARRAY(N_TRACKED_SPECIES+1,INDX) = TMP(I,J,K)
         REALS_TO_SEND_ARRAY(N_TRACKED_SPECIES+2,INDX) = RHO(I,J,K)
         REALS_TO_SEND_ARRAY(N_TRACKED_SPECIES+3,INDX) = PRES
         REALS_TO_SEND_ARRAY(N_TRACKED_SPECIES+4,INDX) = MU(I,J,K)
         REALS_TO_SEND_ARRAY(N_TRACKED_SPECIES+5,INDX) = LES_FILTER_WIDTH(I,J,K)
         REALS_TO_SEND_ARRAY(N_TRACKED_SPECIES+6,INDX) = DX(I)*DY(J)*DZ(K)
         REALS_TO_SEND_ARRAY(N_TRACKED_SPECIES+7,INDX) = REAL(CHEM_ACTIVE_CELLS(NC,4),EB) ! Is ignition zone
         RANK_TO=RANK_TO+1; IF(RANK_TO==N_MPI_PROCESSES+1) RANK_TO=1
      ENDDO
      IF (CC_IBM) THEN
         DO NC=1,NCHEM_ACTIVE_CC
            ICC= CHEM_ACTIVE_CC(NC,1); JCC= CHEM_ACTIVE_CC(NC,2)
            CC => CUT_CELL(ICC); I = CC%IJK(IAXIS); J = CC%IJK(JAXIS); K = CC%IJK(KAXIS)
            SEQ = SEQ+1
            NCELLS_TO_SEND_ARRAY(RANK_TO)=NCELLS_TO_SEND_ARRAY(RANK_TO)+1
            INDX= CELLS_PER_RANK*(RANK_TO-1) + NCELLS_TO_SEND_ARRAY(RANK_TO)
            INTEGERS_TEST_ARRAY(INDX) = NM
            CHEM_SEQ_ARR(SEQ) = INDX
            ! Reals to send:
            ZZ_GET = CC%ZZ(1:N_TRACKED_SPECIES,JCC)
            PRES = PBAR(K,PRESSURE_ZONE(I,J,K)) + RHO(I,J,K)*(H(I,J,K)-KRES(I,J,K))
            REALS_TO_SEND_ARRAY(1:N_TRACKED_SPECIES,INDX) = ZZ_GET
            REALS_TO_SEND_ARRAY(N_TRACKED_SPECIES+1,INDX) = CC%TMP(JCC)
            REALS_TO_SEND_ARRAY(N_TRACKED_SPECIES+2,INDX) = CC%RHO(JCC)
            REALS_TO_SEND_ARRAY(N_TRACKED_SPECIES+3,INDX) = PRES
            REALS_TO_SEND_ARRAY(N_TRACKED_SPECIES+4,INDX) = MU(I,J,K)
            REALS_TO_SEND_ARRAY(N_TRACKED_SPECIES+5,INDX) = LES_FILTER_WIDTH(I,J,K)
            REALS_TO_SEND_ARRAY(N_TRACKED_SPECIES+6,INDX) = CC%VOLUME(JCC)
            REALS_TO_SEND_ARRAY(N_TRACKED_SPECIES+7,INDX) = REAL(CHEM_ACTIVE_CC(NC,3),EB)
            RANK_TO=RANK_TO+1; IF(RANK_TO==N_MPI_PROCESSES+1) RANK_TO=1
         ENDDO
      ENDIF
   ENDDO

   
   ! Remove the empty rows.   
   ALLOCATE(NEW_INDEX(NCHEM_ACTIVE_CELLS_AND_CC)); NEW_INDEX=-1
   ALLOCATE(REV_NEW_INDEX(CELLS_ALLOC)); REV_NEW_INDEX=-1
   SEQ=0
   DO INDX=1,CELLS_ALLOC
      IF(INTEGERS_TEST_ARRAY(INDX) == -1) CYCLE
      SEQ=SEQ+1
      NEW_INDEX(SEQ)=INDX
      REV_NEW_INDEX(INDX) = SEQ
   ENDDO
   DO SEQ=1,NCHEM_ACTIVE_CELLS_AND_CC
      CHEM_SEQ_ARR(SEQ) = REV_NEW_INDEX(CHEM_SEQ_ARR(SEQ))
      REALS_TO_SEND_ARRAY(1:NVAR_TO_SEND,SEQ) = REALS_TO_SEND_ARRAY(1:NVAR_TO_SEND,NEW_INDEX(SEQ))
   ENDDO
   DEALLOCATE(NEW_INDEX,REV_NEW_INDEX, INTEGERS_TEST_ARRAY)
   
ENDIF

! Send and recieve cell data:
! First send the number of cells to send to each rank:
CALL MPI_ALLTOALL(NCELLS_TO_SEND_ARRAY,1,MPI_INTEGER,NCELLS_TO_RECV_ARRAY,1,MPI_INTEGER,MPI_COMM_WORLD,IERR)

 
! Now send the actual data:
DO I=2,N_MPI_PROCESSES
   SEND_DISPS(I) = SEND_DISPS(I-1) + NCELLS_TO_SEND_ARRAY(I-1)*NVAR_TO_SEND
   REVC_DISPS(I) = REVC_DISPS(I-1) + NCELLS_TO_RECV_ARRAY(I-1)*NVAR_TO_SEND
ENDDO
NRECEIVE_CELLS=SUM(NCELLS_TO_RECV_ARRAY)
ALLOCATE(REALS_TO_RECV_ARRAY(NVAR_TO_SEND,MAX(NRECEIVE_CELLS,1))); REALS_TO_RECV_ARRAY=0._EB
TEMPARR1 = NCELLS_TO_SEND_ARRAY*NVAR_TO_SEND
TEMPARR2 = NCELLS_TO_RECV_ARRAY*NVAR_TO_SEND
CALL MPI_ALLTOALLV(REALS_TO_SEND_ARRAY,TEMPARR1,SEND_DISPS,MPI_DOUBLE_PRECISION,&
                   REALS_TO_RECV_ARRAY,TEMPARR2,REVC_DISPS,MPI_DOUBLE_PRECISION,&
                   MPI_COMM_WORLD,IERR)

DEALLOCATE(REALS_TO_SEND_ARRAY)
T_CHEM_COMM = T_CHEM_COMM+CURRENT_TIME() - TNOW

END SUBROUTINE DISTRIBUTE_CELLS_ACCROSS_MPI_PROCESSES


SUBROUTINE GATHER_CELLS_FROM_MPI_PROCESSES(DT)
REAL(EB), INTENT(IN) :: DT
INTEGER :: NCHEM_ACTIVE_CELLS_AND_CC, NCHEM_ACTIVE_CELLS, NCHEM_ACTIVE_CC, NC
INTEGER :: I, J , K, NM, INDX, ICC, JCC, IERR, SEQ
INTEGER :: TEMPARR1(N_MPI_PROCESSES), TEMPARR2(N_MPI_PROCESSES)
INTEGER :: CHEM_SUBIT_TMP
REAL(EB) :: ZZ_GET(1:N_TRACKED_SPECIES),DZZ(1:N_TRACKED_SPECIES), &
            REAC_SOURCE_TERM_TMP(N_TRACKED_SPECIES),Q_REAC_TMP(N_REACTIONS)
REAL(EB) :: TNOW
TYPE (CC_CUTCELL_TYPE), POINTER :: CC

TNOW = CURRENT_TIME()

NCHEM_ACTIVE_CELLS_AND_CC = NCHEM_ACTIVE_CELLS_AND_CC_RANK_WISE(MY_RANK+1)

SEND_DISPS(1) = 0; REVC_DISPS(1) = 0
DO I=2,N_MPI_PROCESSES
   SEND_DISPS(I) = SEND_DISPS(I-1) + NCELLS_TO_RECV_ARRAY(I-1)*NVAR_TO_RECEIVE
   REVC_DISPS(I) = REVC_DISPS(I-1) + NCELLS_TO_SEND_ARRAY(I-1)*NVAR_TO_RECEIVE
ENDDO
ALLOCATE(RESULTS_TO_RECV_ARRAY(NVAR_TO_RECEIVE,MAX(NCHEM_ACTIVE_CELLS_AND_CC,1))); RESULTS_TO_RECV_ARRAY=0._EB
TEMPARR1 = NCELLS_TO_RECV_ARRAY*NVAR_TO_RECEIVE
TEMPARR2 = NCELLS_TO_SEND_ARRAY*NVAR_TO_RECEIVE
CALL MPI_ALLTOALLV(RESULTS_TO_SEND_ARRAY(1,1),TEMPARR1,SEND_DISPS,MPI_DOUBLE_PRECISION,&
                   RESULTS_TO_RECV_ARRAY(1,1),TEMPARR2,REVC_DISPS,MPI_DOUBLE_PRECISION,&
                   MPI_COMM_WORLD,IERR)
DEALLOCATE(RESULTS_TO_SEND_ARRAY)

T_CHEM_COMM = T_CHEM_COMM+CURRENT_TIME() - TNOW

! Set appropriate variables
!---------------------------------------------
REAC_SOURCE_TERM_TMP = 0._EB
Q_REAC_TMP           = 0._EB
SEQ = 0
DO NM=LOWER_MESH_INDEX,UPPER_MESH_INDEX
   CALL POINT_TO_MESH(NM)
   NCHEM_ACTIVE_CELLS = MESHES(NM)%NCHEM_ACTIVE_CELLS
   NCHEM_ACTIVE_CC = MESHES(NM)%NCHEM_ACTIVE_CC

   ! Call chemistry on chemically active cells
   DO NC=1,NCHEM_ACTIVE_CELLS
      I=CHEM_ACTIVE_CELLS(NC,1); J=CHEM_ACTIVE_CELLS(NC,2); K= CHEM_ACTIVE_CELLS(NC,3)
      SEQ=SEQ+1
      INDX = CHEM_SEQ_ARR(SEQ)
      DZZ                  = ZZ(I,J,K,1:N_TRACKED_SPECIES)
      ZZ_GET               = RESULTS_TO_RECV_ARRAY(1:N_TRACKED_SPECIES,INDX)
      Q(I,J,K)             = RESULTS_TO_RECV_ARRAY(N_TRACKED_SPECIES+1,INDX)
      MIX_TIME(I,J,K)      = RESULTS_TO_RECV_ARRAY(N_TRACKED_SPECIES+2,INDX)
      CHI_R(I,J,K)         = RESULTS_TO_RECV_ARRAY(N_TRACKED_SPECIES+3,INDX)
      CHEM_SUBIT_TMP       = INT(RESULTS_TO_RECV_ARRAY(N_TRACKED_SPECIES+4,INDX))
      IF (OUTPUT_CHEM_IT) CHEM_SUBIT(I,J,K) = CHEM_SUBIT_TMP
      CALL SET_SPECIES_SOURCE_TERM_CELL(DT, I, J, K, ZZ_GET, DZZ, REAC_SOURCE_TERM_TMP, Q_REAC_TMP)
      IF (STOP_STATUS/=NO_STOP) RETURN
   ENDDO

   ! Call chemistry on chemically active cut-cells
   IF (CC_IBM) THEN
      DO NC=1,NCHEM_ACTIVE_CC
         ICC= CHEM_ACTIVE_CC(NC,1); JCC= CHEM_ACTIVE_CC(NC,2)
         CC => CUT_CELL(ICC); I = CC%IJK(IAXIS); J = CC%IJK(JAXIS); K = CC%IJK(KAXIS)
         SEQ=SEQ+1
         INDX = CHEM_SEQ_ARR(SEQ)
         DZZ                  = CC%ZZ(1:N_TRACKED_SPECIES,JCC)
         ZZ_GET               = RESULTS_TO_RECV_ARRAY(1:N_TRACKED_SPECIES,INDX);
         CC%Q(JCC)            = RESULTS_TO_RECV_ARRAY(N_TRACKED_SPECIES+1,INDX)
         CC%MIX_TIME(JCC)     = RESULTS_TO_RECV_ARRAY(N_TRACKED_SPECIES+2,INDX)
         CC%CHI_R(JCC)        = RESULTS_TO_RECV_ARRAY(N_TRACKED_SPECIES+3,INDX)
         CHEM_SUBIT_TMP       = INT(RESULTS_TO_RECV_ARRAY(N_TRACKED_SPECIES+4,INDX))
         CALL SET_SPECIES_SOURCE_TERM_CUTCELL(DT, ICC, JCC, ZZ_GET, DZZ, REAC_SOURCE_TERM_TMP, Q_REAC_TMP)
      ENDDO
   ENDIF ! CC_IBM
ENDDO  ! NM

DEALLOCATE(RESULTS_TO_RECV_ARRAY, CHEM_SEQ_ARR)

END SUBROUTINE GATHER_CELLS_FROM_MPI_PROCESSES



#ifdef WITH_SUNDIALS
!> \brief Dump CVODE warning summary
SUBROUTINE DUMP_CVODE_WARNING_SUMMARY(NCHEM_ACTIVE_CELLS_AND_CC)
   USE CHEMCONS, ONLY: CVODE_WARNING_CELLS,CVODE_ERR_CODE_MIN,CVODE_ERR_CODE_MAX,CVODE_WARN_MESSAGES

   INTEGER, INTENT(IN) :: NCHEM_ACTIVE_CELLS_AND_CC
   INTEGER :: NCHEM_ACTIVE_CELLS_AND_CC_GLOBAL,IERR, CVODE_ERR_CODE, TOT_WARN_CELLS
   REAL(EB) :: PCNT,TNOW
   CHARACTER(LEN=16) :: CELL_STR, PCNT_STR
   CHARACTER(LEN=40) :: CELL_INFO

   TNOW = CURRENT_TIME()

   IF (N_MPI_PROCESSES > 1) THEN
      CALL MPI_ALLREDUCE(MPI_IN_PLACE, CVODE_WARNING_CELLS, SIZE(CVODE_WARNING_CELLS), &
                         MPI_INTEGER, MPI_SUM, MPI_COMM_WORLD, IERR)

      CALL MPI_ALLREDUCE(NCHEM_ACTIVE_CELLS_AND_CC, NCHEM_ACTIVE_CELLS_AND_CC_GLOBAL, &
                         1, MPI_INTEGER, MPI_SUM, MPI_COMM_WORLD, IERR)
   ELSE
      NCHEM_ACTIVE_CELLS_AND_CC_GLOBAL = NCHEM_ACTIVE_CELLS_AND_CC
   END IF
   TOT_WARN_CELLS = SUM(CVODE_WARNING_CELLS)

   IF (TOT_WARN_CELLS > 0 .AND. NCHEM_ACTIVE_CELLS_AND_CC_GLOBAL > 0 .AND. MY_RANK == 0) THEN

      WRITE(LU_ERR, '(A)') '--------------- CVODE Warning Summary ----------------'
      WRITE(LU_ERR, '(A)') ' Code     Cells (% Chem)             Message'
      
      DO CVODE_ERR_CODE = CVODE_ERR_CODE_MIN, CVODE_ERR_CODE_MAX
         IF (CVODE_WARNING_CELLS(CVODE_ERR_CODE) > 0) THEN

            PCNT = REAL(CVODE_WARNING_CELLS(CVODE_ERR_CODE)) / &
                   REAL(NCHEM_ACTIVE_CELLS_AND_CC_GLOBAL) * 100.0_EB

            ! Convert to strings and left-align
            WRITE(CELL_STR, '(I0)') CVODE_WARNING_CELLS(CVODE_ERR_CODE)
            WRITE(PCNT_STR, '(F6.2)') PCNT
            CELL_STR = ADJUSTL(CELL_STR)
            PCNT_STR = ADJUSTL(PCNT_STR)

            ! Combine count + percentage into one left-aligned string
            WRITE(CELL_INFO, '(A, " (", A, " %)")') TRIM(CELL_STR), TRIM(PCNT_STR)
            CELL_INFO = ADJUSTL(CELL_INFO)

            ! Print one line of summary
            WRITE(LU_ERR, '(1X, I4, 5X, A, 5X, A)') CVODE_ERR_CODE, &
                 TRIM(CELL_INFO), TRIM(CVODE_WARN_MESSAGES(CVODE_ERR_CODE))
         END IF
      END DO

      WRITE(LU_ERR, '(A)') '------------------------------------------------------'

   END IF
   T_CHEM_COMM = T_CHEM_COMM+CURRENT_TIME() - TNOW

END SUBROUTINE DUMP_CVODE_WARNING_SUMMARY

#endif


SUBROUTINE COMBUSTION_BC(NM)

! Specify ghost cell values of the HRRPUV, Q

USE COMP_FUNCTIONS, ONLY: CURRENT_TIME
INTEGER, INTENT(IN) :: NM
REAL(EB) :: Q_OTHER,TNOW
INTEGER :: IW,IIO,JJO,KKO,NOM,N_INT_CELLS
TYPE(WALL_TYPE),POINTER :: WC
TYPE(BOUNDARY_COORD_TYPE),POINTER :: BC
TYPE(EXTERNAL_WALL_TYPE),POINTER :: EWC

TNOW=CURRENT_TIME()

CALL POINT_TO_MESH(NM)

WALL_LOOP: DO IW=1,N_EXTERNAL_WALL_CELLS
   WC =>WALL(IW)
   EWC=>EXTERNAL_WALL(IW)
   IF (EWC%NOM==0) CYCLE WALL_LOOP
   BC => BOUNDARY_COORD(WC%BC_INDEX)
   NOM = EWC%NOM
   Q_OTHER   = 0._EB
   DO KKO=EWC%KKO_MIN,EWC%KKO_MAX
      DO JJO=EWC%JJO_MIN,EWC%JJO_MAX
         DO IIO=EWC%IIO_MIN,EWC%IIO_MAX
            Q_OTHER = Q_OTHER + OMESH(NOM)%Q(IIO,JJO,KKO)
         ENDDO
      ENDDO
   ENDDO
   N_INT_CELLS = (EWC%IIO_MAX-EWC%IIO_MIN+1) * (EWC%JJO_MAX-EWC%JJO_MIN+1) * (EWC%KKO_MAX-EWC%KKO_MIN+1)
   Q(BC%II,BC%JJ,BC%KK) = Q_OTHER/REAL(N_INT_CELLS,EB)
ENDDO WALL_LOOP

T_USED(10)=T_USED(10)+CURRENT_TIME()-TNOW
END SUBROUTINE COMBUSTION_BC


SUBROUTINE CONDENSATION_EVAPORATION(DT,NM)

INTEGER, INTENT(IN):: NM
REAL(EB), INTENT(IN):: DT

CALL CONDENSATION_EVAPORATION_KERNEL(MESHES(NM),DT,NM)

END SUBROUTINE CONDENSATION_EVAPORATION



END MODULE FIRE

