!> \brief Mass transport equations

MODULE MASS

USE PRECISION_PARAMETERS
USE GLOBAL_CONSTANTS
USE MESH_POINTERS
USE COMP_FUNCTIONS, ONLY: CURRENT_TIME

IMPLICIT NONE (TYPE,EXTERNAL)
PRIVATE
PUBLIC MASS_FINITE_DIFFERENCES_NEW,DENSITY

CONTAINS


!> \brief Compute spatial differences for mass transport equations
!> \param NM Mesh index

SUBROUTINE MASS_FINITE_DIFFERENCES_NEW(NM)

USE MASS_KERNELS, ONLY: MASS_FINITE_DIFFERENCES_NEW_KERNEL

INTEGER, INTENT(IN) :: NM
REAL(EB) :: TNOW

TNOW=CURRENT_TIME()

CALL MASS_FINITE_DIFFERENCES_NEW_KERNEL(MESHES(NM))

T_USED(3)=T_USED(3)+CURRENT_TIME()-TNOW

END SUBROUTINE MASS_FINITE_DIFFERENCES_NEW


!> \brief Update the species mass fractions and density
!> \param T Simulation time (s)
!> \param DT Time step (s)
!> \param NM Mesh index

SUBROUTINE DENSITY(T,DT,NM)

USE MASS_KERNELS, ONLY: DENSITY_KERNEL

INTEGER, INTENT(IN) :: NM
REAL(EB), INTENT(IN) :: T,DT
REAL(EB) :: TNOW

TNOW=CURRENT_TIME()

CALL DENSITY_KERNEL(MESHES(NM),T,DT,NM)

T_USED(3)=T_USED(3)+CURRENT_TIME()-TNOW

END SUBROUTINE DENSITY

END MODULE MASS
